/* Generated by Nim Compiler v0.12.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nim -o /home/marco/saus/advent-of-code-2019/17.nim/nimcache/os.o /home/marco/saus/advent-of-code-2019/17.nim/nimcache/os.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <stdlib.h>
#include <time.h>
#include <errno.h>
typedef struct TY17205 TY17205;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Cell49347 Cell49347;
typedef struct Cellseq49363 Cellseq49363;
typedef struct Gcheap51418 Gcheap51418;
typedef struct Gcstack51416 Gcstack51416;
typedef struct Cellset49359 Cellset49359;
typedef struct Pagedesc49355 Pagedesc49355;
typedef struct Memregion31291 Memregion31291;
typedef struct Smallchunk31243 Smallchunk31243;
typedef struct Llchunk31285 Llchunk31285;
typedef struct Bigchunk31245 Bigchunk31245;
typedef struct Intset31217 Intset31217;
typedef struct Trunk31213 Trunk31213;
typedef struct Avlnode31289 Avlnode31289;
typedef struct Gcstat51414 Gcstat51414;
typedef struct Oserror4033 Oserror4033;
typedef struct Systemerror4029 Systemerror4029;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct Basechunk31241 Basechunk31241;
typedef struct Freecell31233 Freecell31233;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_NIMCALL_PTR(void, TY3889) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3894) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3889 marker;
TY3894 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Cell49347  {
NI refcount;
TNimType* typ;
};
struct  Cellseq49363  {
NI len;
NI cap;
Cell49347** d;
};
struct  Cellset49359  {
NI counter;
NI max;
Pagedesc49355* head;
Pagedesc49355** data;
};
typedef Smallchunk31243* TY31306[512];
typedef Trunk31213* Trunkbuckets31215[256];
struct  Intset31217  {
Trunkbuckets31215 data;
};
struct  Memregion31291  {
NI minlargeobj;
NI maxlargeobj;
TY31306 freesmallchunks;
Llchunk31285* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk31245* freechunkslist;
Intset31217 chunkstarts;
Avlnode31289* root;
Avlnode31289* deleted;
Avlnode31289* last;
Avlnode31289* freeavlnodes;
};
struct  Gcstat51414  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Gcheap51418  {
Gcstack51416* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq49363 zct;
Cellseq49363 decstack;
Cellset49359 cycleroots;
Cellseq49363 tempstack;
NI recgclock;
Memregion31291 region;
Gcstat51414 stat;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  Systemerror4029  {
  Exception Sup;
};
struct  Oserror4033  {
  Systemerror4029 Sup;
NI32 errorcode;
};
struct  Gcstack51416  {
Gcstack51416* prev;
Gcstack51416* next;
void* starts;
void* pos;
NI maxstacksize;
};
typedef NI TY31222[8];
struct  Pagedesc49355  {
Pagedesc49355* next;
NI key;
TY31222 bits;
};
struct  Basechunk31241  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk31243  {
  Basechunk31241 Sup;
Smallchunk31243* next;
Smallchunk31243* prev;
Freecell31233* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk31285  {
NI size;
NI acc;
Llchunk31285* next;
};
struct  Bigchunk31245  {
  Basechunk31241 Sup;
Bigchunk31245* next;
Bigchunk31245* prev;
NI align;
NF data;
};
struct  Trunk31213  {
Trunk31213* next;
NI key;
TY31222 bits;
};
typedef Avlnode31289* TY31296[2];
struct  Avlnode31289  {
TY31296 link;
NI key;
NI upperbound;
NI level;
};
struct  Freecell31233  {
Freecell31233* next;
NI zerofield;
};
struct TY17205 {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
static N_INLINE(NimStringDesc*, pop_133071)(TY17205** s);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(TGenericSeq*, setLengthSeq)(TGenericSeq* seq, NI elemsize, NI newlen);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_23601)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NI, findenvvar_132005)(NimStringDesc* key);
N_NIMCALL(void, getenvvarsc_131602)(void);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(Cell49347*, usrtocell_53046)(void* usr);
static N_INLINE(void, rtladdzct_54604)(Cell49347* c);
N_NOINLINE(void, addzct_53017)(Cellseq49363* s, Cell49347* c);
N_NIMCALL(void*, newSeqRC1)(TNimType* typ, NI len);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq, NI elemsize);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(NI, addInt)(NI a, NI b);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(NIM_BOOL, nsuStartsWith)(NimStringDesc* s, NimStringDesc* prefix);
N_NIMCALL(NimStringDesc*, copyStr)(NimStringDesc* s, NI start);
N_NIMCALL(NimStringDesc*, copyStr)(NimStringDesc* s, NI first);
N_NIMCALL(NI, nsuFindChar)(NimStringDesc* s, NIM_CHAR sub, NI start);
static N_INLINE(NI, divInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
static N_INLINE(NI, modInt)(NI a, NI b);
N_NIMCALL(NI, mulInt)(NI a, NI b);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, oserrormsg_126820)(NI32 errorcode);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_NIMCALL(NimStringDesc*, nososErrorMsg)(void);
STRING_LITERAL(TMP575, "", 0);
STRING_LITERAL(TMP694, " ", 1);
STRING_LITERAL(TMP695, "unknown OS error", 16);
NIM_BOOL envcomputed_131407;
TY17205* environment_131409;
extern NCSTRING* environ;
extern TFrame* frameptr_20842;
extern int cmdCount;
extern NCSTRING* cmdLine;
extern TNimType NTI17205; /* seq[string] */
extern Gcheap51418 gch_51459;
extern TNimType NTI127013; /* ref OSError */
extern TNimType NTI4033; /* OSError */

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (a <= i);
		if (!(LOC3)) goto LA4;
		LOC3 = (i <= b);
		LA4: ;
		if (!LOC3) goto LA5;
		result = i;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	}BeforeRet: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_20842 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_20842).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_20842;
	frameptr_20842 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_23601();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_20842 = (*frameptr_20842).prev;
}

static N_INLINE(NimStringDesc*, pop_133071)(TY17205** s) {
	NimStringDesc* result;
	NI L;
	NI TMP528;
	nimfr("pop", "system.nim")
	result = 0;
	nimln(2202, "system.nim");
	TMP528 = subInt(((*s) ? (*s)->Sup.len : 0), ((NI) 1));
	L = (NI)(TMP528);
	nimln(2203, "system.nim");
	if ((NU)(L) >= (NU)((*s)->Sup.len)) raiseIndexError();
	result = copyString((*s)->data[L]);
	nimln(2204, "system.nim");
	(*s) = (TY17205*) setLengthSeq(&((*s))->Sup, sizeof(NimStringDesc*), ((NI)chckRange(L, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	popFrame();
	return result;
}

static N_INLINE(Cell49347*, usrtocell_53046)(void* usr) {
	Cell49347* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(131, "gc.nim");
	result = ((Cell49347*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell49347))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_54604)(Cell49347* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(212, "gc.nim");
	addzct_53017((&gch_51459.zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	Cell49347* c;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(246, "gc.nim");
	c = usrtocell_53046(p);
	nimln(248, "gc.nim");
	{
		nimln(180, "gc.nim");
		(*c).refcount -= ((NI) 8);
		nimln(181, "gc.nim");
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3;
		nimln(249, "gc.nim");
		rtladdzct_54604(c);
	}
	LA3: ;
	popFrame();
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

N_NIMCALL(void, getenvvarsc_131602)(void) {
	nimfr("getEnvVarsC", "os.nim")
	nimln(692, "os.nim");
	{
		NI i;
		if (!!(envcomputed_131407)) goto LA3;
		nimln(693, "os.nim");
		if (environment_131409) nimGCunrefNoCycle(environment_131409);
		environment_131409 = (TY17205*) newSeqRC1((&NTI17205), 0);
		nimln(696, "os.nim");
		i = ((NI) 0);
		{
			nimln(697, "os.nim");
			while (1) {
				NimStringDesc* LOC11;
				NimStringDesc* LOC12;
				NI TMP572;
				nimln(698, "os.nim");
				{
					if ((NU)(i) > (NU)(100000000)) raiseIndexError();
					if (!(environ[(i)- 0] == NIM_NIL)) goto LA9;
					goto LA5;
				}
				LA9: ;
				nimln(699, "os.nim");
				if ((NU)(i) > (NU)(100000000)) raiseIndexError();
				LOC11 = 0;
				LOC11 = cstrToNimstr(environ[(i)- 0]);
				environment_131409 = (TY17205*) incrSeqV2(&(environment_131409)->Sup, sizeof(NimStringDesc*));
				LOC12 = 0;
				LOC12 = environment_131409->data[environment_131409->Sup.len]; environment_131409->data[environment_131409->Sup.len] = copyStringRC1(LOC11);
				if (LOC12) nimGCunrefNoCycle(LOC12);
				++environment_131409->Sup.len;
				nimln(700, "os.nim");
				TMP572 = addInt(i, ((NI) 1));
				i = (NI)(TMP572);
			}
		} LA5: ;
		nimln(701, "os.nim");
		envcomputed_131407 = NIM_TRUE;
	}
	LA3: ;
	popFrame();
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI)((*src).Sup.len + ((NI) 1)));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c) {
	(*dest).data[((*dest).Sup.len)- 0] = c;
	(*dest).data[((NI)((*dest).Sup.len + ((NI) 1)))- 0] = 0;
	(*dest).Sup.len += ((NI) 1);
}

N_NIMCALL(NI, findenvvar_132005)(NimStringDesc* key) {
	NI result;
	NimStringDesc* temp;
	NimStringDesc* LOC1;
	nimfr("findEnvVar", "os.nim")
{	result = 0;
	nimln(704, "os.nim");
	getenvvarsc_131602();
	nimln(705, "os.nim");
	LOC1 = 0;
	LOC1 = rawNewString(key->Sup.len + 1);
appendString(LOC1, key);
appendChar(LOC1, 61);
	temp = LOC1;
	{
		NI i_132020;
		NI HEX3Atmp_132022;
		NI res_132025;
		i_132020 = 0;
		HEX3Atmp_132022 = 0;
		nimln(706, "os.nim");
		HEX3Atmp_132022 = (environment_131409 ? (environment_131409->Sup.len-1) : -1);
		nimln(1874, "system.nim");
		res_132025 = ((NI) 0);
		{
			nimln(1875, "system.nim");
			while (1) {
				NI TMP573;
				if (!(res_132025 <= HEX3Atmp_132022)) goto LA4;
				nimln(1876, "system.nim");
				i_132020 = res_132025;
				nimln(707, "os.nim");
				{
					NIM_BOOL LOC7;
					if ((NU)(i_132020) >= (NU)(environment_131409->Sup.len)) raiseIndexError();
					LOC7 = 0;
					LOC7 = nsuStartsWith(environment_131409->data[i_132020], temp);
					if (!LOC7) goto LA8;
					result = i_132020;
					goto BeforeRet;
				}
				LA8: ;
				nimln(1895, "system.nim");
				TMP573 = addInt(res_132025, ((NI) 1));
				res_132025 = (NI)(TMP573);
			} LA4: ;
		}
	}
	nimln(708, "os.nim");
	result = ((NI) -1);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, getenv_132044)(NimStringDesc* key) {
	NimStringDesc* result;
	NI i;
	nimfr("getEnv", "os.nim")
{	result = 0;
	nimln(716, "os.nim");
	i = findenvvar_132005(key);
	nimln(717, "os.nim");
	{
		NI LOC5;
		NI TMP574;
		nimln(353, "system.nim");
		if (!(((NI) 0) <= i)) goto LA3;
		nimln(718, "os.nim");
		if ((NU)(i) >= (NU)(environment_131409->Sup.len)) raiseIndexError();
		if ((NU)(i) >= (NU)(environment_131409->Sup.len)) raiseIndexError();
		LOC5 = 0;
		LOC5 = nsuFindChar(environment_131409->data[i], 61, ((NI) 0));
		TMP574 = addInt(LOC5, ((NI) 1));
		result = copyStr(environment_131409->data[i], (NI)(TMP574));
		goto BeforeRet;
	}
	goto LA1;
	LA3: ;
	{
		NCSTRING env;
		nimln(720, "os.nim");
		env = getenv(key->data);
		nimln(721, "os.nim");
		{
			if (!(env == NIM_NIL)) goto LA9;
			result = copyString(((NimStringDesc*) &TMP575));
			goto BeforeRet;
		}
		LA9: ;
		nimln(722, "os.nim");
		result = cstrToNimstr(env);
	}
	LA1: ;
	}BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(NI, divInt)(NI a, NI b) {
	NI result;
{	result = 0;
	{
		if (!(b == ((NI) 0))) goto LA3;
		raiseDivByZero();
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == ((NI) (IL64(-9223372036854775807) - IL64(1))));
		if (!(LOC7)) goto LA8;
		LOC7 = (b == ((NI) -1));
		LA8: ;
		if (!LOC7) goto LA9;
		raiseOverflow();
	}
	LA9: ;
	result = (NI)(a / b);
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, modInt)(NI a, NI b) {
	NI result;
{	result = 0;
	{
		if (!(b == ((NI) 0))) goto LA3;
		raiseDivByZero();
	}
	LA3: ;
	result = (NI)(a % b);
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(void, nossleep)(NI milsecs) {
	struct timespec a;
	struct timespec b;
	NI TMP656;
	NI TMP657;
	NI TMP658;
	NI TMP659;
	int LOC1;
	nimfr("sleep", "os.nim")
	memset((void*)(&a), 0, sizeof(a));
	memset((void*)(&b), 0, sizeof(b));
	nimln(1408, "os.nim");
	TMP656 = divInt(milsecs, ((NI) 1000));
	a.tv_sec = (NI)(TMP656);
	nimln(1409, "os.nim");
	TMP657 = modInt(milsecs, ((NI) 1000));
	TMP658 = mulInt(((NI) ((NI)(TMP657))), ((NI) 1000));
	TMP659 = mulInt(((NI) ((NI)(TMP658))), ((NI) 1000));
	a.tv_nsec = ((NI) ((NI)(TMP659)));
	nimln(1410, "os.nim");
	LOC1 = 0;
	LOC1 = nanosleep((&a), (&b));
	popFrame();
}

N_NIMCALL(NimStringDesc*, oserrormsg_126820)(NI32 errorcode) {
	NimStringDesc* result;
	nimfr("osErrorMsg", "os.nim")
	result = 0;
	nimln(100, "os.nim");
	result = copyString(((NimStringDesc*) &TMP575));
	nimln(116, "os.nim");
	{
		NCSTRING LOC5;
		nimln(349, "system.nim");
		if (!!((errorcode == ((NI32) 0)))) goto LA3;
		nimln(117, "os.nim");
		LOC5 = 0;
		LOC5 = strerror(errorcode);
		result = cstrToNimstr(LOC5);
	}
	LA3: ;
	popFrame();
	return result;
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(264, "gc.nim");
	{
		Cell49347* c;
		nimln(349, "system.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(265, "gc.nim");
		c = usrtocell_53046(src);
		nimln(182, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3: ;
	nimln(267, "gc.nim");
	{
		Cell49347* c;
		nimln(349, "system.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(268, "gc.nim");
		c = usrtocell_53046((*dest));
		nimln(269, "gc.nim");
		{
			nimln(180, "gc.nim");
			(*c).refcount -= ((NI) 8);
			nimln(181, "gc.nim");
			if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA11;
			nimln(270, "gc.nim");
			rtladdzct_54604(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(271, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NOINLINE(void, raiseoserror_127009)(NI32 errorcode, NimStringDesc* additionalinfo) {
	Oserror4033* e;
	nimfr("raiseOSError", "os.nim")
	e = 0;
	nimln(127, "os.nim");
	e = (Oserror4033*) newObj((&NTI127013), sizeof(Oserror4033));
	(*e).Sup.Sup.Sup.m_type = (&NTI4033);
	nimln(128, "os.nim");
	(*e).errorcode = errorcode;
	nimln(129, "os.nim");
	{
		if (!((additionalinfo ? additionalinfo->Sup.len : 0) == ((NI) 0))) goto LA3;
		nimln(130, "os.nim");
		asgnRefNoCycle((void**) (&(*e).Sup.Sup.message), oserrormsg_126820(errorcode));
	}
	goto LA1;
	LA3: ;
	{
		NimStringDesc* LOC6;
		NimStringDesc* LOC7;
		nimln(132, "os.nim");
		LOC6 = 0;
		LOC7 = 0;
		LOC7 = oserrormsg_126820(errorcode);
		LOC6 = rawNewString(additionalinfo->Sup.len + LOC7->Sup.len + 1);
appendString(LOC6, additionalinfo);
appendString(LOC6, ((NimStringDesc*) &TMP694));
appendString(LOC6, LOC7);
		asgnRefNoCycle((void**) (&(*e).Sup.Sup.message), LOC6);
	}
	LA1: ;
	nimln(133, "os.nim");
	{
		NimStringDesc* LOC12;
		if (!(((*e).Sup.Sup.message) && ((*e).Sup.Sup.message)->Sup.len == 0)) goto LA10;
		nimln(134, "os.nim");
		LOC12 = 0;
		LOC12 = (*e).Sup.Sup.message; (*e).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TMP695));
		if (LOC12) nimGCunrefNoCycle(LOC12);
	}
	LA10: ;
	nimln(135, "os.nim");
	raiseException((Exception*)e, "OSError");
	popFrame();
}

N_NIMCALL(NI32, oslasterror_127034)(void) {
	NI32 result;
	result = 0;
	result = errno;
	return result;
}

N_NIMCALL(NimStringDesc*, nososErrorMsg)(void) {
	NimStringDesc* result;
	nimfr("osErrorMsg", "os.nim")
	result = 0;
	nimln(47, "os.nim");
	result = copyString(((NimStringDesc*) &TMP575));
	nimln(63, "os.nim");
	{
		NCSTRING LOC5;
		nimln(349, "system.nim");
		if (!!((errno == ((NI32) 0)))) goto LA3;
		nimln(64, "os.nim");
		LOC5 = 0;
		LOC5 = strerror(errno);
		result = cstrToNimstr(LOC5);
	}
	LA3: ;
	popFrame();
	return result;
}

N_NOINLINE(void, nosraiseOSError)(NimStringDesc* msg) {
	nimfr("raiseOSError", "os.nim")
	nimln(76, "os.nim");
	{
		NimStringDesc* m;
		Oserror4033* e_126617;
		if (!((msg ? msg->Sup.len : 0) == ((NI) 0))) goto LA3;
		nimln(77, "os.nim");
		m = nososErrorMsg();
		e_126617 = 0;
		nimln(2507, "system.nim");
		e_126617 = (Oserror4033*) newObj((&NTI127013), sizeof(Oserror4033));
		(*e_126617).Sup.Sup.Sup.m_type = (&NTI4033);
		nimln(2508, "system.nim");
		nimln(78, "os.nim");
		{
			NimStringDesc* LOC9;
			nimln(357, "system.nim");
			nimln(78, "os.nim");
			if (!(((NI) 0) < (m ? m->Sup.len : 0))) goto LA7;
			LOC9 = 0;
			LOC9 = (*e_126617).Sup.Sup.message; (*e_126617).Sup.Sup.message = copyStringRC1(m);
			if (LOC9) nimGCunrefNoCycle(LOC9);
		}
		goto LA5;
		LA7: ;
		{
			NimStringDesc* LOC11;
			LOC11 = 0;
			LOC11 = (*e_126617).Sup.Sup.message; (*e_126617).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TMP695));
			if (LOC11) nimGCunrefNoCycle(LOC11);
		}
		LA5: ;
		raiseException((Exception*)e_126617, "OSError");
	}
	goto LA1;
	LA3: ;
	{
		Oserror4033* e_126630;
		NimStringDesc* LOC13;
		e_126630 = 0;
		nimln(2507, "system.nim");
		e_126630 = (Oserror4033*) newObj((&NTI127013), sizeof(Oserror4033));
		(*e_126630).Sup.Sup.Sup.m_type = (&NTI4033);
		nimln(2508, "system.nim");
		LOC13 = 0;
		LOC13 = (*e_126630).Sup.Sup.message; (*e_126630).Sup.Sup.message = copyStringRC1(msg);
		if (LOC13) nimGCunrefNoCycle(LOC13);
		nimln(80, "os.nim");
		raiseException((Exception*)e_126630, "OSError");
	}
	LA1: ;
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, HEX00_osInit000)(void) {
	nimfr("os", "os.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, HEX00_osDatInit000)(void) {
}

