/* Generated by Nim Compiler v0.12.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nim -o /home/marco/saus/advent-of-code-2019/17.nim/nimcache/osproc.o /home/marco/saus/advent-of-code-2019/17.nim/nimcache/osproc.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <sys/types.h>
#include <unistd.h>
#include <setjmp.h>
#include <errno.h>
#include <fcntl.h>
#include <stdio.h>
#include <signal.h>
#include <sys/wait.h>
#include <stdlib.h>
#include <sys/select.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Processobj155407 Processobj155407;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Streamobj148227 Streamobj148227;
typedef struct TY156201 TY156201;
typedef struct Cell49347 Cell49347;
typedef struct Cellset49359 Cellset49359;
typedef struct Gcheap51418 Gcheap51418;
typedef struct Gcstack51416 Gcstack51416;
typedef struct Cellseq49363 Cellseq49363;
typedef struct Pagedesc49355 Pagedesc49355;
typedef struct Memregion31291 Memregion31291;
typedef struct Smallchunk31243 Smallchunk31243;
typedef struct Llchunk31285 Llchunk31285;
typedef struct Bigchunk31245 Bigchunk31245;
typedef struct Intset31217 Intset31217;
typedef struct Trunk31213 Trunk31213;
typedef struct Avlnode31289 Avlnode31289;
typedef struct Gcstat51414 Gcstat51414;
typedef struct Stringtableobj145212 Stringtableobj145212;
typedef struct Keyvaluepairseq145210 Keyvaluepairseq145210;
typedef struct TY109772 TY109772;
typedef struct TY17205 TY17205;
typedef struct Startprocessdata156948 Startprocessdata156948;
typedef struct Exception Exception;
typedef struct TSafePoint TSafePoint;
typedef struct Filestreamobj149467 Filestreamobj149467;
typedef struct TY159410 TY159410;
typedef struct Basechunk31241 Basechunk31241;
typedef struct Freecell31233 Freecell31233;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 TY82458[32];
typedef NimStringDesc* TY155637[1];
typedef N_NIMCALL_PTR(void, TY3889) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3894) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3889 marker;
TY3894 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Processobj155407  {
  TNimObject Sup;
int inhandle;
int outhandle;
int errhandle;
Streamobj148227* instream;
Streamobj148227* outstream;
Streamobj148227* errstream;
pid_t id;
int exitcode;
NU8 options;
};
typedef struct {
N_NIMCALL_PTR(void, ClPrc) (NI idx, void* ClEnv);
void* ClEnv;
} TY155795;
typedef struct {
N_NIMCALL_PTR(void, ClPrc) (NI idx, Processobj155407* p, void* ClEnv);
void* ClEnv;
} TY155799;
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_CLOSURE_PTR(void, TMP654) (NI idx);
struct  Cell49347  {
NI refcount;
TNimType* typ;
};
struct  Cellseq49363  {
NI len;
NI cap;
Cell49347** d;
};
struct  Cellset49359  {
NI counter;
NI max;
Pagedesc49355* head;
Pagedesc49355** data;
};
typedef Smallchunk31243* TY31306[512];
typedef Trunk31213* Trunkbuckets31215[256];
struct  Intset31217  {
Trunkbuckets31215 data;
};
struct  Memregion31291  {
NI minlargeobj;
NI maxlargeobj;
TY31306 freesmallchunks;
Llchunk31285* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk31245* freechunkslist;
Intset31217 chunkstarts;
Avlnode31289* root;
Avlnode31289* deleted;
Avlnode31289* last;
Avlnode31289* freeavlnodes;
};
struct  Gcstat51414  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Gcheap51418  {
Gcstack51416* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq49363 zct;
Cellseq49363 decstack;
Cellset49359 cycleroots;
Cellseq49363 tempstack;
NI recgclock;
Memregion31291 region;
Gcstat51414 stat;
};
typedef N_CLOSURE_PTR(void, TMP662) (NI idx, Processobj155407* p);
typedef N_CLOSURE_PTR(void, TMP663) (NI idx);
typedef N_CLOSURE_PTR(void, TMP667) (NI idx, Processobj155407* p);
typedef N_CLOSURE_PTR(void, TMP669) (NI idx);
typedef N_CLOSURE_PTR(void, TMP670) (NI idx, Processobj155407* p);
struct  Stringtableobj145212  {
  TNimObject Sup;
NI counter;
Keyvaluepairseq145210* data;
NU8 mode;
};
struct TY109772 {
NimStringDesc* Field0;
NimStringDesc* Field1;
};
typedef int TY156954[2];
struct  Startprocessdata156948  {
NCSTRING syscommand;
NCSTRING* sysargs;
NCSTRING* sysenv;
NCSTRING workingdir;
TY156954 pstdin;
TY156954 pstdout;
TY156954 pstderr;
TY156954 perrorpipe;
NIM_BOOL optionpousepath;
NIM_BOOL optionpoparentstreams;
NIM_BOOL optionpostderrtostdout;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClPrc) (Exception* e, void* ClEnv);
void* ClEnv;
} TY19211;
struct  TSafePoint  {
TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
TY19211 raiseAction;
};
typedef NimStringDesc* TY157812[2];
typedef NimStringDesc* TY157060[3];
typedef NimStringDesc* TY157201[1];
struct TY159410 {
NimStringDesc* Field0;
NI Field1;
};
typedef N_NIMCALL_PTR(void, TY148228) (Streamobj148227* s);
typedef N_NIMCALL_PTR(NIM_BOOL, TY148232) (Streamobj148227* s);
typedef N_NIMCALL_PTR(void, TY148236) (Streamobj148227* s, NI pos);
typedef N_NIMCALL_PTR(NI, TY148241) (Streamobj148227* s);
typedef N_NIMCALL_PTR(NI, TY148245) (Streamobj148227* s, void* buffer, NI buflen);
typedef N_NIMCALL_PTR(NI, TY148251) (Streamobj148227* s, void* buffer, NI buflen);
typedef N_NIMCALL_PTR(void, TY148257) (Streamobj148227* s, void* buffer, NI buflen);
typedef N_NIMCALL_PTR(void, TY148263) (Streamobj148227* s);
struct  Streamobj148227  {
  TNimObject Sup;
TY148228 closeimpl;
TY148232 atendimpl;
TY148236 setpositionimpl;
TY148241 getpositionimpl;
TY148245 readdataimpl;
TY148251 peekdataimpl;
TY148257 writedataimpl;
TY148263 flushimpl;
};
struct  Gcstack51416  {
Gcstack51416* prev;
Gcstack51416* next;
void* starts;
void* pos;
NI maxstacksize;
};
typedef NI TY31222[8];
struct  Pagedesc49355  {
Pagedesc49355* next;
NI key;
TY31222 bits;
};
struct  Basechunk31241  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk31243  {
  Basechunk31241 Sup;
Smallchunk31243* next;
Smallchunk31243* prev;
Freecell31233* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk31285  {
NI size;
NI acc;
Llchunk31285* next;
};
struct  Bigchunk31245  {
  Basechunk31241 Sup;
Bigchunk31245* next;
Bigchunk31245* prev;
NI align;
NF data;
};
struct  Trunk31213  {
Trunk31213* next;
NI key;
TY31222 bits;
};
typedef Avlnode31289* TY31296[2];
struct  Avlnode31289  {
TY31296 link;
NI key;
NI upperbound;
NI level;
};
struct  Filestreamobj149467  {
  Streamobj148227 Sup;
FILE* f;
};
struct  Freecell31233  {
Freecell31233* next;
NI zerofield;
};
struct TY156201 {
  TGenericSeq Sup;
  Processobj155407* data[SEQ_DECL_SIZE];
};
struct TY17205 {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct Keyvaluepairseq145210 {
  TGenericSeq Sup;
  TY109772 data[SEQ_DECL_SIZE];
};
N_NIMCALL(NimStringDesc*, nospquoteShellWindows)(NimStringDesc* s);
N_NIMCALL(NIM_BOOL, contains_103975)(NimStringDesc* s, TY82458 chars);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newlen);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(void, failedassertimpl_91603)(NimStringDesc* msg);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_23601)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NimStringDesc*, nospquoteShellPosix)(NimStringDesc* s);
N_NIMCALL(NIM_BOOL, allcharsinset_103130)(NimStringDesc* s, TY82458 theset);
N_NIMCALL(NimStringDesc*, nsuReplaceStr)(NimStringDesc* s, NimStringDesc* sub, NimStringDesc* by);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(NimStringDesc*, nospquoteShell)(NimStringDesc* s);
N_NIMCALL(Processobj155407*, startcmd_155646)(NimStringDesc* command, NU8 options);
N_NIMCALL(NI, nospprocessID)(Processobj155407* p);
N_NIMCALL(int, nospinputHandle)(Processobj155407* p);
N_NIMCALL(int, nospoutputHandle)(Processobj155407* p);
N_NIMCALL(int, nosperrorHandle)(Processobj155407* p);
N_NIMCALL(NI, nospcountProcessors)(void);
N_NIMCALL(NI, ncpicountProcessors)(void);
N_NIMCALL(NI, nospexecProcesses)(NimStringDesc** cmds, NI cmdsLen0, NU8 options_155793, NI n, TY155795 beforerunevent, TY155799 afterrunevent);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP650)(void* p, NI op);
N_NIMCALL(void, TMP651)(void* p, NI op);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
static N_INLINE(NI, subInt)(NI a, NI b);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incref_55422)(Cell49347* c);
static N_INLINE(NIM_BOOL, canbecycleroot_53067)(Cell49347* c);
static N_INLINE(void, rtladdcycleroot_53823)(Cell49347* c);
N_NOINLINE(void, incl_50065)(Cellset49359* s, Cell49347* cell);
static N_INLINE(Cell49347*, usrtocell_53046)(void* usr);
static N_INLINE(void, decref_55004)(Cell49347* c);
static N_INLINE(void, rtladdzct_54604)(Cell49347* c);
N_NOINLINE(void, addzct_53017)(Cellseq49363* s, Cell49347* c);
N_NIMCALL(void, nossleep)(NI milsecs);
N_NIMCALL(NimStringDesc*, nospexecProcess)(NimStringDesc* command, NimStringDesc** args, NI argsLen0, Stringtableobj145212* env, NU8 options);
N_NIMCALL(NimStringDesc*, rawNewString)(NI cap);
N_NIMCALL(NIM_BOOL, readline_149242)(Streamobj148227* s, NimStringDesc** line);
N_NIMCALL(NCSTRING*, envtocstringarray_156806)(Stringtableobj145212* t);
N_NOCONV(void*, alloc0_8417)(NI size);
N_NIMCALL(NI, nstlen)(Stringtableobj145212* t);
N_NIMCALL(NI, mulInt)(NI a, NI b);
N_NOCONV(void*, alloc_8401)(NI size);
N_NIMCALL(NCSTRING*, envtocstringarray_156854)(void);
N_NIMCALL(void, getenvvarsc_131602)(void);
N_NIMCALL(NI, nsuFindChar)(NimStringDesc* s, NIM_CHAR sub, NI start);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start_81416, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
N_NIMCALL(NimStringDesc*, copyStr)(NimStringDesc* s, NI start);
N_NIMCALL(NimStringDesc*, copyStr)(NimStringDesc* s, NI first);
N_NIMCALL(pid_t, startprocessauxfork_157001)(Startprocessdata156948* data);
N_NOINLINE(void, raiseoserror_127009)(NI32 errorcode, NimStringDesc* additionalinfo);
N_NIMCALL(NI32, oslasterror_127034)(void);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
N_CDECL(void, startprocessafterfork_157004)(Startprocessdata156948* data);
N_NIMCALL(void, startprocessfail_157819)(Startprocessdata156948* data);
N_NOINLINE(void, nosraiseOSError)(NimStringDesc* msg);
N_NIMCALL(NimStringDesc*, nsuFormatOpenArray)(NimStringDesc* formatstr, NimStringDesc** a, NI aLen0);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
static N_INLINE(void, popSafePoint)(void);
static N_INLINE(void, setFrame)(TFrame* s);
N_NIMCALL(void, reraiseException)(void);
N_NIMCALL(Processobj155407*, nospstartProcess)(NimStringDesc* command, NimStringDesc* workingdir, NimStringDesc** args, NI argsLen0, Stringtableobj145212* env, NU8 options);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq, NI elemsize);
N_NIMCALL(NCSTRING*, alloccstringarray_17601)(NimStringDesc** a, NI aLen0);
N_NIMCALL(NimStringDesc*, nsuJoinSep)(NimStringDesc** a, NI aLen0, NimStringDesc* sep);
N_NIMCALL(void, dealloccstringarray_17850)(NCSTRING* a);
N_NIMCALL(void, nospclose)(Processobj155407* p);
N_NIMCALL(void, close_148291)(Streamobj148227* s);
N_NIMCALL(void, nospsuspend)(Processobj155407* p);
N_NIMCALL(void, nospresume)(Processobj155407* p);
N_NIMCALL(NIM_BOOL, nosprunning)(Processobj155407* p);
N_NIMCALL(void, nospterminate)(Processobj155407* p);
N_NIMCALL(void, nospkill)(Processobj155407* p);
N_NIMCALL(NI, nospwaitForExit)(Processobj155407* p, NI timeout);
N_NIMCALL(NI, peekexitcode_155725)(Processobj155407* p);
N_NIMCALL(void, createstream_158641)(Streamobj148227** stream, int* handle, NU8 filemode);
N_NIMCALL(NIM_BOOL, open_16811)(FILE** f, int filehandle, NU8 mode);
N_NIMCALL(Filestreamobj149467*, newfilestream_149544)(FILE* f);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(Streamobj148227*, nospinputStream)(Processobj155407* p);
N_NIMCALL(Streamobj148227*, nospoutputStream)(Processobj155407* p);
N_NIMCALL(Streamobj148227*, nosperrorStream)(Processobj155407* p);
N_NIMCALL(NI, nospexecCmd)(NimStringDesc* command);
N_NIMCALL(void, createfdset_158804)(fd_set* fd, TY156201* s, NI* m);
N_NIMCALL(void, pruneprocessset_159044)(TY156201** s, fd_set* fd);
N_NIMCALL(TGenericSeq*, setLengthSeq)(TGenericSeq* seq, NI elemsize, NI newlen);
N_NIMCALL(NI, select_156635)(TY156201** readfds, NI timeout);
N_NIMCALL(NIM_BOOL, hasdata_159164)(Processobj155407* p);
N_NIMCALL(void, execcmdex_159404)(NimStringDesc* command, NU8 options, TY159410* Result);
static NIM_CONST TY82458 TMP632 = {
0x00, 0x02, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
STRING_LITERAL(TMP633, "", 0);
STRING_LITERAL(TMP634, "\"", 1);
STRING_LITERAL(TMP635, "\\\"", 2);
STRING_LITERAL(TMP637, "len(a) == L string modified while iterating over it", 51);
NIM_CONST TY82458 safeunixchars_155475 = {
0x00, 0x00, 0x00, 0x00, 0x20, 0xE8, 0xFF, 0x27,
0xFF, 0xFF, 0xFF, 0x87, 0xFE, 0xFF, 0xFF, 0x07,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
STRING_LITERAL(TMP638, "\'\'", 2);
static NIM_CONST TY82458 TMP640 = {
0x00, 0x00, 0x00, 0x00, 0x20, 0xE8, 0xFF, 0x27,
0xFF, 0xFF, 0xFF, 0x87, 0xFE, 0xFF, 0xFF, 0x07,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
STRING_LITERAL(TMP641, "\'", 1);
STRING_LITERAL(TMP643, "\'\"\'\"\'", 5);
STRING_LITERAL(TMP644, "\012  0 < n ", 9);
static NIM_CONST TY155795 TMP653 = {NIM_NIL,NIM_NIL};
static NIM_CONST TY155799 TMP661 = {NIM_NIL,NIM_NIL};
STRING_LITERAL(TMP672, "", 0);
STRING_LITERAL(TMP673, "\012", 1);
STRING_LITERAL(TMP676, "=", 1);
STRING_LITERAL(TMP698, "Could not find command: \'$1\'. OS error: $2", 42);
STRING_LITERAL(TMP699, "/bin/sh", 7);
STRING_LITERAL(TMP700, "-c", 2);
STRING_LITERAL(TMP701, "len(args) == 0 `args` has to be empty when using poEvalCommand.", 63);
STRING_LITERAL(TMP705, " ", 1);
STRING_LITERAL(TMP707, "len(a) == L seq modified while iterating over it", 48);
NIM_CONST TY159410 TMP715 = {((NimStringDesc*) &TMP672),
((NI) -1)}
;
extern TFrame* frameptr_20842;
extern TNimType NTI4011; /* RootObj */
TNimType NTI155407; /* ProcessObj */
extern TNimType NTI16408; /* FileHandle */
extern TNimType NTI148225; /* Stream */
extern TNimType NTI114289; /* Pid */
extern TNimType NTI8211; /* cint */
TNimType NTI155405; /* ProcessOption */
TNimType NTI155649; /* set[ProcessOption] */
TNimType NTI155409; /* Process */
TNimType NTI156201; /* seq[Process] */
extern Gcheap51418 gch_51459;
extern TY17205* environment_131409;
extern TSafePoint* exchandler_20843;
extern TNimType NTI17205; /* seq[string] */

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI)((*src).Sup.len + ((NI) 1)));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_20842 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_20842).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_20842;
	frameptr_20842 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_23601();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_20842 = (*frameptr_20842).prev;
}

N_NIMCALL(NimStringDesc*, nospquoteShellWindows)(NimStringDesc* s) {
	NimStringDesc* result;
	NIM_BOOL needquote;
	NIM_BOOL LOC1;
	NimStringDesc* backslashbuff;
	nimfr("quoteShellWindows", "osproc.nim")
	result = 0;
	nimln(67, "osproc.nim");
	LOC1 = 0;
	nimln(1098, "system.nim");
	LOC1 = contains_103975(s, TMP632);
	if (LOC1) goto LA2;
	nimln(67, "osproc.nim");
	LOC1 = ((s ? s->Sup.len : 0) == ((NI) 0));
	LA2: ;
	needquote = LOC1;
	nimln(69, "osproc.nim");
	result = copyString(((NimStringDesc*) &TMP633));
	nimln(70, "osproc.nim");
	backslashbuff = copyString(((NimStringDesc*) &TMP633));
	nimln(71, "osproc.nim");
	{
		if (!needquote) goto LA5;
		nimln(72, "osproc.nim");
		result = resizeString(result, 1);
appendString(result, ((NimStringDesc*) &TMP634));
	}
	LA5: ;
	{
		NIM_CHAR c_155449;
		NI i_155453;
		NI L_155455;
		c_155449 = 0;
		nimln(3383, "system.nim");
		i_155453 = ((NI) 0);
		nimln(3384, "system.nim");
		L_155455 = (s ? s->Sup.len : 0);
		{
			nimln(3385, "system.nim");
			while (1) {
				NI TMP636;
				if (!(i_155453 < L_155455)) goto LA9;
				nimln(3386, "system.nim");
				if ((NU)(i_155453) > (NU)(s->Sup.len)) raiseIndexError();
				c_155449 = s->data[i_155453];
				nimln(75, "osproc.nim");
				{
					if (!((NU8)(c_155449) == (NU8)(92))) goto LA12;
					nimln(76, "osproc.nim");
					backslashbuff = addChar(backslashbuff, c_155449);
				}
				goto LA10;
				LA12: ;
				{
					nimln(77, "osproc.nim");
					if (!((NU8)(c_155449) == (NU8)(34))) goto LA15;
					nimln(78, "osproc.nim");
					result = resizeString(result, backslashbuff->Sup.len + 0);
appendString(result, backslashbuff);
					nimln(79, "osproc.nim");
					result = resizeString(result, backslashbuff->Sup.len + 0);
appendString(result, backslashbuff);
					nimln(80, "osproc.nim");
					backslashbuff = setLengthStr(backslashbuff, ((NI) 0));
					nimln(81, "osproc.nim");
					result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TMP635));
				}
				goto LA10;
				LA15: ;
				{
					nimln(83, "osproc.nim");
					{
						nimln(349, "system.nim");
						nimln(83, "osproc.nim");
						if (!!(((backslashbuff ? backslashbuff->Sup.len : 0) == ((NI) 0)))) goto LA20;
						nimln(84, "osproc.nim");
						result = resizeString(result, backslashbuff->Sup.len + 0);
appendString(result, backslashbuff);
						nimln(85, "osproc.nim");
						backslashbuff = setLengthStr(backslashbuff, ((NI) 0));
					}
					LA20: ;
					nimln(86, "osproc.nim");
					result = addChar(result, c_155449);
				}
				LA10: ;
				nimln(3387, "system.nim");
				TMP636 = addInt(i_155453, ((NI) 1));
				i_155453 = (NI)(TMP636);
				nimln(3388, "system.nim");
				{
					if (!!(((s ? s->Sup.len : 0) == L_155455))) goto LA24;
					failedassertimpl_91603(((NimStringDesc*) &TMP637));
				}
				LA24: ;
			} LA9: ;
		}
	}
	nimln(88, "osproc.nim");
	{
		if (!needquote) goto LA28;
		nimln(89, "osproc.nim");
		result = resizeString(result, 1);
appendString(result, ((NimStringDesc*) &TMP634));
	}
	LA28: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, nospquoteShellPosix)(NimStringDesc* s) {
	NimStringDesc* result;
	NIM_BOOL safe;
	nimfr("quoteShellPosix", "osproc.nim")
{	result = 0;
	nimln(96, "osproc.nim");
	{
		if (!((s ? s->Sup.len : 0) == ((NI) 0))) goto LA3;
		nimln(97, "osproc.nim");
		result = copyString(((NimStringDesc*) &TMP638));
		goto BeforeRet;
	}
	LA3: ;
	nimln(99, "osproc.nim");
	safe = allcharsinset_103130(s, TMP640);
	nimln(101, "osproc.nim");
	{
		if (!safe) goto LA7;
		nimln(102, "osproc.nim");
		result = copyString(s);
		goto BeforeRet;
	}
	goto LA5;
	LA7: ;
	{
		NimStringDesc* LOC10;
		NimStringDesc* LOC11;
		nimln(104, "osproc.nim");
		LOC10 = 0;
		LOC11 = 0;
		LOC11 = nsuReplaceStr(s, ((NimStringDesc*) &TMP641), ((NimStringDesc*) &TMP643));
		LOC10 = rawNewString(LOC11->Sup.len + 2);
appendString(LOC10, ((NimStringDesc*) &TMP641));
appendString(LOC10, LOC11);
appendString(LOC10, ((NimStringDesc*) &TMP641));
		result = LOC10;
		goto BeforeRet;
	}
	LA5: ;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, nospquoteShell)(NimStringDesc* s) {
	NimStringDesc* result;
	nimfr("quoteShell", "osproc.nim")
{	result = 0;
	nimln(111, "osproc.nim");
	result = nospquoteShellPosix(s);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(Processobj155407*, startcmd_155646)(NimStringDesc* command, NU8 options) {
	Processobj155407* result;
	TY155637 LOC1;
	nimfr("startCmd", "osproc.nim")
	result = 0;
	nimln(175, "osproc.nim");
	memset((void*)LOC1, 0, sizeof(LOC1));
	result = nospstartProcess(command, ((NimStringDesc*) &TMP633), LOC1, 0, NIM_NIL, (options | 4));
	popFrame();
	return result;
}

N_NIMCALL(NI, nospprocessID)(Processobj155407* p) {
	NI result;
	nimfr("processID", "osproc.nim")
{	result = 0;
	nimln(200, "osproc.nim");
	result = (*p).id;
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(int, nospinputHandle)(Processobj155407* p) {
	int result;
	nimfr("inputHandle", "osproc.nim")
	result = 0;
	nimln(236, "osproc.nim");
	result = (*p).inhandle;
	popFrame();
	return result;
}

N_NIMCALL(int, nospoutputHandle)(Processobj155407* p) {
	int result;
	nimfr("outputHandle", "osproc.nim")
	result = 0;
	nimln(244, "osproc.nim");
	result = (*p).outhandle;
	popFrame();
	return result;
}

N_NIMCALL(int, nosperrorHandle)(Processobj155407* p) {
	int result;
	nimfr("errorHandle", "osproc.nim")
	result = 0;
	nimln(252, "osproc.nim");
	result = (*p).errhandle;
	popFrame();
	return result;
}

N_NIMCALL(NI, nospcountProcessors)(void) {
	NI result;
	nimfr("countProcessors", "osproc.nim")
	result = 0;
	nimln(257, "osproc.nim");
	result = ncpicountProcessors();
	popFrame();
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (a <= i);
		if (!(LOC3)) goto LA4;
		LOC3 = (i <= b);
		LA4: ;
		if (!LOC3) goto LA5;
		result = i;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	}BeforeRet: ;
	return result;
}
N_NIMCALL(void, TMP650)(void* p, NI op) {
	Processobj155407* a;
	a = (Processobj155407*)p;
	nimGCvisit((void*)(*a).instream, op);
	nimGCvisit((void*)(*a).outstream, op);
	nimGCvisit((void*)(*a).errstream, op);
}
N_NIMCALL(void, TMP651)(void* p, NI op) {
	TY156201* a;
	NI LOC1;
	a = (TY156201*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1], op);
	}
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(NIM_BOOL, canbecycleroot_53067)(Cell49347* c) {
	NIM_BOOL result;
	nimfr("canBeCycleRoot", "gc.nim")
	result = 0;
	nimln(134, "gc.nim");
	nimln(1104, "system.nim");
	result = !((((*(*c).typ).flags &(1<<((((NU8) 1))&7)))!=0));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdcycleroot_53823)(Cell49347* c) {
	nimfr("rtlAddCycleRoot", "gc.nim")
	nimln(202, "gc.nim");
	{
		nimln(349, "system.nim");
		nimln(147, "gc.nim");
		if (!!((((NI) ((NI)((*c).refcount & ((NI) 3)))) == ((NI) 3)))) goto LA3;
		nimln(152, "gc.nim");
		(*c).refcount = (NI)((NI)((*c).refcount & ((NI) -4)) | ((NI) 3));
		nimln(204, "gc.nim");
		incl_50065((&gch_51459.cycleroots), c);
	}
	LA3: ;
	popFrame();
}

static N_INLINE(void, incref_55422)(Cell49347* c) {
	nimfr("incRef", "gc.nim")
	nimln(229, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	nimln(232, "gc.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = canbecycleroot_53067(c);
		if (!LOC3) goto LA4;
		nimln(233, "gc.nim");
		rtladdcycleroot_53823(c);
	}
	LA4: ;
	popFrame();
}

static N_INLINE(Cell49347*, usrtocell_53046)(void* usr) {
	Cell49347* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(131, "gc.nim");
	result = ((Cell49347*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell49347))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_54604)(Cell49347* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(212, "gc.nim");
	addzct_53017((&gch_51459.zct), c);
	popFrame();
}

static N_INLINE(void, decref_55004)(Cell49347* c) {
	nimfr("decRef", "gc.nim")
	nimln(219, "gc.nim");
	{
		nimln(180, "gc.nim");
		(*c).refcount -= ((NI) 8);
		nimln(181, "gc.nim");
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3;
		nimln(220, "gc.nim");
		rtladdzct_54604(c);
	}
	goto LA1;
	LA3: ;
	{
		NIM_BOOL LOC6;
		nimln(221, "gc.nim");
		LOC6 = 0;
		LOC6 = canbecycleroot_53067(c);
		if (!LOC6) goto LA7;
		nimln(224, "gc.nim");
		rtladdcycleroot_53823(c);
	}
	goto LA1;
	LA7: ;
	LA1: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr("asgnRef", "gc.nim")
	nimln(257, "gc.nim");
	{
		Cell49347* LOC5;
		nimln(349, "system.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(257, "gc.nim");
		LOC5 = 0;
		LOC5 = usrtocell_53046(src);
		incref_55422(LOC5);
	}
	LA3: ;
	nimln(258, "gc.nim");
	{
		Cell49347* LOC10;
		nimln(349, "system.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8;
		nimln(258, "gc.nim");
		LOC10 = 0;
		LOC10 = usrtocell_53046((*dest));
		decref_55004(LOC10);
	}
	LA8: ;
	nimln(259, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(NI, nospexecProcesses)(NimStringDesc** cmds, NI cmdsLen0, NU8 options_155793, NI n, TY155795 beforerunevent, TY155799 afterrunevent) {
	NI result;
	NU8 options;
	nimfr("execProcesses", "osproc.nim")
	result = 0;
	nimln(271, "osproc.nim");
	options = (options_155793 & ~ 16);
	nimln(273, "osproc.nim");
	{
		if (!!((((NI) 0) < n))) goto LA3;
		failedassertimpl_91603(((NimStringDesc*) &TMP644));
	}
	LA3: ;
	nimln(274, "osproc.nim");
	{
		TY156201* q;
		NI m;
		NI i;
		nimln(357, "system.nim");
		if (!(((NI) 1) < n)) goto LA7;
		q = 0;
		nimln(276, "osproc.nim");
		q = (TY156201*) newSeq((&NTI156201), ((NI)chckRange(n, ((NI) 0), ((NI) IL64(9223372036854775807)))));
		nimln(277, "osproc.nim");
		m = ((n <= cmdsLen0) ? n : cmdsLen0);
		{
			NI i_156235;
			NI HEX3Atmp_156555;
			NI TMP652;
			NI res_156558;
			i_156235 = 0;
			HEX3Atmp_156555 = 0;
			nimln(278, "osproc.nim");
			TMP652 = subInt(m, ((NI) 1));
			HEX3Atmp_156555 = (NI)(TMP652);
			nimln(1874, "system.nim");
			res_156558 = ((NI) 0);
			{
				nimln(1875, "system.nim");
				while (1) {
					TY155637 LOC16;
					NI TMP655;
					if (!(res_156558 <= HEX3Atmp_156555)) goto LA11;
					nimln(1876, "system.nim");
					i_156235 = res_156558;
					nimln(279, "osproc.nim");
					{
						nimln(349, "system.nim");
						if (!!((beforerunevent.ClPrc == TMP653.ClPrc && beforerunevent.ClEnv == TMP653.ClEnv))) goto LA14;
						nimln(280, "osproc.nim");
						beforerunevent.ClEnv? beforerunevent.ClPrc(i_156235, beforerunevent.ClEnv):((TMP654)(beforerunevent.ClPrc))(i_156235);
					}
					LA14: ;
					nimln(281, "osproc.nim");
					if ((NU)(i_156235) >= (NU)(q->Sup.len)) raiseIndexError();
					if ((NU)(i_156235) >= (NU)(cmdsLen0)) raiseIndexError();
					memset((void*)LOC16, 0, sizeof(LOC16));
					asgnRef((void**) (&q->data[i_156235]), nospstartProcess(cmds[i_156235], ((NimStringDesc*) &TMP633), LOC16, 0, NIM_NIL, (options | 4)));
					nimln(1895, "system.nim");
					TMP655 = addInt(res_156558, ((NI) 1));
					res_156558 = (NI)(TMP655);
				} LA11: ;
			}
		}
		nimln(300, "osproc.nim");
		i = m;
		{
			nimln(301, "osproc.nim");
			while (1) {
				if (!(i <= (cmdsLen0-1))) goto LA18;
				nimln(302, "osproc.nim");
				nossleep(((NI) 50));
				{
					NI r_156413;
					NI HEX3Atmp_156564;
					NI TMP660;
					NI res_156567;
					r_156413 = 0;
					HEX3Atmp_156564 = 0;
					nimln(303, "osproc.nim");
					TMP660 = subInt(n, ((NI) 1));
					HEX3Atmp_156564 = (NI)(TMP660);
					nimln(1874, "system.nim");
					res_156567 = ((NI) 0);
					{
						nimln(1875, "system.nim");
						while (1) {
							NI TMP665;
							if (!(res_156567 <= HEX3Atmp_156564)) goto LA21;
							nimln(1876, "system.nim");
							r_156413 = res_156567;
							nimln(304, "osproc.nim");
							{
								NIM_BOOL LOC24;
								NI LOC27;
								TY155637 LOC40;
								NI TMP664;
								if ((NU)(r_156413) >= (NU)(q->Sup.len)) raiseIndexError();
								LOC24 = 0;
								LOC24 = nosprunning(q->data[r_156413]);
								if (!!(LOC24)) goto LA25;
								nimln(306, "osproc.nim");
								if ((NU)(r_156413) >= (NU)(q->Sup.len)) raiseIndexError();
								LOC27 = 0;
								LOC27 = nospwaitForExit(q->data[r_156413], ((NI) -1));
								result = ((LOC27 >= result) ? LOC27 : result);
								nimln(307, "osproc.nim");
								{
									nimln(349, "system.nim");
									if (!!((afterrunevent.ClPrc == TMP661.ClPrc && afterrunevent.ClEnv == TMP661.ClEnv))) goto LA30;
									nimln(307, "osproc.nim");
									if ((NU)(r_156413) >= (NU)(q->Sup.len)) raiseIndexError();
									afterrunevent.ClEnv? afterrunevent.ClPrc(r_156413, q->data[r_156413], afterrunevent.ClEnv):((TMP662)(afterrunevent.ClPrc))(r_156413, q->data[r_156413]);
								}
								LA30: ;
								nimln(308, "osproc.nim");
								{
									nimln(349, "system.nim");
									if ((NU)(r_156413) >= (NU)(q->Sup.len)) raiseIndexError();
									if (!!((q->data[r_156413] == NIM_NIL))) goto LA34;
									nimln(308, "osproc.nim");
									if ((NU)(r_156413) >= (NU)(q->Sup.len)) raiseIndexError();
									nospclose(q->data[r_156413]);
								}
								LA34: ;
								nimln(309, "osproc.nim");
								{
									nimln(349, "system.nim");
									if (!!((beforerunevent.ClPrc == TMP653.ClPrc && beforerunevent.ClEnv == TMP653.ClEnv))) goto LA38;
									nimln(310, "osproc.nim");
									beforerunevent.ClEnv? beforerunevent.ClPrc(i, beforerunevent.ClEnv):((TMP663)(beforerunevent.ClPrc))(i);
								}
								LA38: ;
								nimln(311, "osproc.nim");
								if ((NU)(r_156413) >= (NU)(q->Sup.len)) raiseIndexError();
								if ((NU)(i) >= (NU)(cmdsLen0)) raiseIndexError();
								memset((void*)LOC40, 0, sizeof(LOC40));
								asgnRef((void**) (&q->data[r_156413]), nospstartProcess(cmds[i], ((NimStringDesc*) &TMP633), LOC40, 0, NIM_NIL, (options | 4)));
								nimln(312, "osproc.nim");
								TMP664 = addInt(i, ((NI) 1));
								i = (NI)(TMP664);
								nimln(313, "osproc.nim");
								{
									nimln(357, "system.nim");
									nimln(313, "osproc.nim");
									if (!((cmdsLen0-1) < i)) goto LA43;
									goto LA19;
								}
								LA43: ;
							}
							LA25: ;
							nimln(1895, "system.nim");
							TMP665 = addInt(res_156567, ((NI) 1));
							res_156567 = (NI)(TMP665);
						} LA21: ;
					}
				} LA19: ;
			} LA18: ;
		}
		{
			NI j_156480;
			NI HEX3Atmp_156572;
			NI TMP666;
			NI res_156575;
			j_156480 = 0;
			HEX3Atmp_156572 = 0;
			nimln(314, "osproc.nim");
			TMP666 = subInt(m, ((NI) 1));
			HEX3Atmp_156572 = (NI)(TMP666);
			nimln(1874, "system.nim");
			res_156575 = ((NI) 0);
			{
				nimln(1875, "system.nim");
				while (1) {
					NI LOC48;
					NI TMP668;
					if (!(res_156575 <= HEX3Atmp_156572)) goto LA47;
					nimln(1876, "system.nim");
					j_156480 = res_156575;
					nimln(315, "osproc.nim");
					if ((NU)(j_156480) >= (NU)(q->Sup.len)) raiseIndexError();
					LOC48 = 0;
					LOC48 = nospwaitForExit(q->data[j_156480], ((NI) -1));
					result = ((LOC48 >= result) ? LOC48 : result);
					nimln(316, "osproc.nim");
					{
						nimln(349, "system.nim");
						if (!!((afterrunevent.ClPrc == TMP661.ClPrc && afterrunevent.ClEnv == TMP661.ClEnv))) goto LA51;
						nimln(316, "osproc.nim");
						if ((NU)(j_156480) >= (NU)(q->Sup.len)) raiseIndexError();
						afterrunevent.ClEnv? afterrunevent.ClPrc(j_156480, q->data[j_156480], afterrunevent.ClEnv):((TMP667)(afterrunevent.ClPrc))(j_156480, q->data[j_156480]);
					}
					LA51: ;
					nimln(317, "osproc.nim");
					{
						nimln(349, "system.nim");
						if ((NU)(j_156480) >= (NU)(q->Sup.len)) raiseIndexError();
						if (!!((q->data[j_156480] == NIM_NIL))) goto LA55;
						nimln(317, "osproc.nim");
						if ((NU)(j_156480) >= (NU)(q->Sup.len)) raiseIndexError();
						nospclose(q->data[j_156480]);
					}
					LA55: ;
					nimln(1895, "system.nim");
					TMP668 = addInt(res_156575, ((NI) 1));
					res_156575 = (NI)(TMP668);
				} LA47: ;
			}
		}
	}
	goto LA5;
	LA7: ;
	{
		{
			NI i_156516;
			NI HEX3Atmp_156580;
			NI res_156583;
			i_156516 = 0;
			HEX3Atmp_156580 = 0;
			nimln(319, "osproc.nim");
			HEX3Atmp_156580 = (cmdsLen0-1);
			nimln(1874, "system.nim");
			res_156583 = ((NI) 0);
			{
				nimln(1875, "system.nim");
				while (1) {
					Processobj155407* p;
					TY155637 LOC65;
					NI LOC66;
					NI TMP671;
					if (!(res_156583 <= HEX3Atmp_156580)) goto LA60;
					nimln(1876, "system.nim");
					i_156516 = res_156583;
					nimln(320, "osproc.nim");
					{
						nimln(349, "system.nim");
						if (!!((beforerunevent.ClPrc == TMP653.ClPrc && beforerunevent.ClEnv == TMP653.ClEnv))) goto LA63;
						nimln(321, "osproc.nim");
						beforerunevent.ClEnv? beforerunevent.ClPrc(i_156516, beforerunevent.ClEnv):((TMP669)(beforerunevent.ClPrc))(i_156516);
					}
					LA63: ;
					nimln(322, "osproc.nim");
					if ((NU)(i_156516) >= (NU)(cmdsLen0)) raiseIndexError();
					memset((void*)LOC65, 0, sizeof(LOC65));
					p = nospstartProcess(cmds[i_156516], ((NimStringDesc*) &TMP633), LOC65, 0, NIM_NIL, (options | 4));
					nimln(323, "osproc.nim");
					LOC66 = 0;
					LOC66 = nospwaitForExit(p, ((NI) -1));
					result = ((LOC66 >= result) ? LOC66 : result);
					nimln(324, "osproc.nim");
					{
						nimln(349, "system.nim");
						if (!!((afterrunevent.ClPrc == TMP661.ClPrc && afterrunevent.ClEnv == TMP661.ClEnv))) goto LA69;
						nimln(324, "osproc.nim");
						afterrunevent.ClEnv? afterrunevent.ClPrc(i_156516, p, afterrunevent.ClEnv):((TMP670)(afterrunevent.ClPrc))(i_156516, p);
					}
					LA69: ;
					nimln(325, "osproc.nim");
					nospclose(p);
					nimln(1895, "system.nim");
					TMP671 = addInt(res_156583, ((NI) 1));
					res_156583 = (NI)(TMP671);
				} LA60: ;
			}
		}
	}
	LA5: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, nospexecProcess)(NimStringDesc* command, NimStringDesc** args, NI argsLen0, Stringtableobj145212* env, NU8 options) {
	NimStringDesc* result;
	Processobj155407* p;
	Streamobj148227* outp;
	NimStringDesc* line;
	nimfr("execProcess", "osproc.nim")
	result = 0;
	nimln(343, "osproc.nim");
	p = nospstartProcess(command, ((NimStringDesc*) &TMP633), args, argsLen0, env, options);
	nimln(344, "osproc.nim");
	outp = nospoutputStream(p);
	nimln(345, "osproc.nim");
	result = copyString(((NimStringDesc*) &TMP672));
	nimln(346, "osproc.nim");
	line = rawNewString(((NI) 120));
	{
		nimln(347, "osproc.nim");
		while (1) {
			nimln(349, "osproc.nim");
			{
				NIM_BOOL LOC5;
				LOC5 = 0;
				LOC5 = readline_149242(outp, (&line));
				if (!LOC5) goto LA6;
				nimln(350, "osproc.nim");
				result = resizeString(result, line->Sup.len + 0);
appendString(result, line);
				nimln(351, "osproc.nim");
				result = resizeString(result, 1);
appendString(result, ((NimStringDesc*) &TMP673));
			}
			goto LA3;
			LA6: ;
			{
				NIM_BOOL LOC9;
				nimln(352, "osproc.nim");
				LOC9 = 0;
				LOC9 = nosprunning(p);
				if (!!(LOC9)) goto LA10;
				goto LA1;
			}
			goto LA3;
			LA10: ;
			LA3: ;
		}
	} LA1: ;
	nimln(353, "osproc.nim");
	nospclose(p);
	popFrame();
	return result;
}

N_NIMCALL(NCSTRING*, envtocstringarray_156806)(Stringtableobj145212* t) {
	NCSTRING* result;
	NI LOC1;
	NI TMP674;
	NI TMP675;
	void* LOC2;
	NI i;
	nimfr("envToCStringArray", "osproc.nim")
	result = 0;
	nimln(675, "osproc.nim");
	LOC1 = 0;
	LOC1 = nstlen(t);
	TMP674 = addInt(LOC1, ((NI) 1));
	TMP675 = mulInt((NI)(TMP674), ((NI) 8));
	LOC2 = 0;
	LOC2 = alloc0_8417(((NI)chckRange((NI)(TMP675), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	result = ((NCSTRING*) (LOC2));
	nimln(676, "osproc.nim");
	i = ((NI) 0);
	{
		NimStringDesc* key_156812;
		NimStringDesc* val_156813;
		key_156812 = 0;
		val_156813 = 0;
		{
			NI h_156832;
			NI HEX3Atmp_156834;
			NI res_156836;
			h_156832 = 0;
			HEX3Atmp_156834 = 0;
			nimln(43, "strtabs.nim");
			HEX3Atmp_156834 = ((*t).data ? ((*t).data->Sup.len-1) : -1);
			nimln(1874, "system.nim");
			res_156836 = ((NI) 0);
			{
				nimln(1875, "system.nim");
				while (1) {
					NI TMP680;
					if (!(res_156836 <= HEX3Atmp_156834)) goto LA6;
					nimln(1876, "system.nim");
					h_156832 = res_156836;
					nimln(44, "strtabs.nim");
					{
						NimStringDesc* x;
						NimStringDesc* LOC11;
						NI TMP677;
						void* LOC12;
						NI TMP678;
						NI TMP679;
						if ((NU)(h_156832) >= (NU)((*t).data->Sup.len)) raiseIndexError();
						if (!!((*t).data->data[h_156832].Field0 == 0)) goto LA9;
						nimln(45, "strtabs.nim");
						if ((NU)(h_156832) >= (NU)((*t).data->Sup.len)) raiseIndexError();
						key_156812 = (*t).data->data[h_156832].Field0;
						if ((NU)(h_156832) >= (NU)((*t).data->Sup.len)) raiseIndexError();
						val_156813 = (*t).data->data[h_156832].Field1;
						nimln(678, "osproc.nim");
						LOC11 = 0;
						LOC11 = rawNewString(key_156812->Sup.len + val_156813->Sup.len + 1);
appendString(LOC11, key_156812);
appendString(LOC11, ((NimStringDesc*) &TMP676));
appendString(LOC11, val_156813);
						x = LOC11;
						nimln(679, "osproc.nim");
						if ((NU)(i) > (NU)(100000000)) raiseIndexError();
						TMP677 = addInt((x ? x->Sup.len : 0), ((NI) 1));
						LOC12 = 0;
						LOC12 = alloc_8401(((NI)chckRange((NI)(TMP677), ((NI) 0), ((NI) IL64(9223372036854775807)))));
						result[(i)- 0] = ((NCSTRING) (LOC12));
						nimln(680, "osproc.nim");
						if ((NU)(i) > (NU)(100000000)) raiseIndexError();
						if ((NU)(((NI) 0)) > (NU)(x->Sup.len)) raiseIndexError();
						TMP678 = addInt((x ? x->Sup.len : 0), ((NI) 1));
						memcpy(((void*) (result[(i)- 0])), ((void*) ((&x->data[((NI) 0)]))), ((NI)chckRange((NI)(TMP678), ((NI) 0), ((NI) IL64(9223372036854775807)))));
						nimln(681, "osproc.nim");
						TMP679 = addInt(i, ((NI) 1));
						i = (NI)(TMP679);
					}
					LA9: ;
					nimln(1895, "system.nim");
					TMP680 = addInt(res_156836, ((NI) 1));
					res_156836 = (NI)(TMP680);
				} LA6: ;
			}
		}
	}
	popFrame();
	return result;
}

N_NIMCALL(NCSTRING*, envtocstringarray_156854)(void) {
	NCSTRING* result;
	NI counter;
	NI TMP685;
	NI TMP686;
	void* LOC5;
	NI i;
	nimfr("envToCStringArray", "osproc.nim")
	result = 0;
	nimln(684, "osproc.nim");
	counter = ((NI) 0);
	{
		NimStringDesc* key_156858;
		NimStringDesc* val_156859;
		key_156858 = 0;
		val_156859 = 0;
		nimln(759, "os.nim");
		getenvvarsc_131602();
		{
			NI i_156888;
			NI HEX3Atmp_156890;
			NI res_156892;
			i_156888 = 0;
			HEX3Atmp_156890 = 0;
			nimln(760, "os.nim");
			HEX3Atmp_156890 = (environment_131409 ? (environment_131409->Sup.len-1) : -1);
			nimln(1874, "system.nim");
			res_156892 = ((NI) 0);
			{
				nimln(1875, "system.nim");
				while (1) {
					NI p_156896;
					NI TMP681;
					NI TMP682;
					NI TMP683;
					NI TMP684;
					if (!(res_156892 <= HEX3Atmp_156890)) goto LA4;
					nimln(1876, "system.nim");
					i_156888 = res_156892;
					nimln(761, "os.nim");
					if ((NU)(i_156888) >= (NU)(environment_131409->Sup.len)) raiseIndexError();
					p_156896 = nsuFindChar(environment_131409->data[i_156888], 61, ((NI) 0));
					nimln(762, "os.nim");
					if ((NU)(i_156888) >= (NU)(environment_131409->Sup.len)) raiseIndexError();
					TMP681 = subInt(p_156896, ((NI) 1));
					key_156858 = copyStrLast(environment_131409->data[i_156888], ((NI) 0), (NI)(TMP681));
					nimln(763, "os.nim");
					if ((NU)(i_156888) >= (NU)(environment_131409->Sup.len)) raiseIndexError();
					TMP682 = addInt(p_156896, ((NI) 1));
					val_156859 = copyStr(environment_131409->data[i_156888], (NI)(TMP682));
					nimln(685, "osproc.nim");
					TMP683 = addInt(counter, ((NI) 1));
					counter = (NI)(TMP683);
					nimln(1895, "system.nim");
					TMP684 = addInt(res_156892, ((NI) 1));
					res_156892 = (NI)(TMP684);
				} LA4: ;
			}
		}
	}
	nimln(686, "osproc.nim");
	TMP685 = addInt(counter, ((NI) 1));
	TMP686 = mulInt((NI)(TMP685), ((NI) 8));
	LOC5 = 0;
	LOC5 = alloc0_8417(((NI)chckRange((NI)(TMP686), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	result = ((NCSTRING*) (LOC5));
	nimln(687, "osproc.nim");
	i = ((NI) 0);
	{
		NimStringDesc* key_156871;
		NimStringDesc* val_156872;
		key_156871 = 0;
		val_156872 = 0;
		nimln(759, "os.nim");
		getenvvarsc_131602();
		{
			NI i_156909;
			NI HEX3Atmp_156911;
			NI res_156913;
			i_156909 = 0;
			HEX3Atmp_156911 = 0;
			nimln(760, "os.nim");
			HEX3Atmp_156911 = (environment_131409 ? (environment_131409->Sup.len-1) : -1);
			nimln(1874, "system.nim");
			res_156913 = ((NI) 0);
			{
				nimln(1875, "system.nim");
				while (1) {
					NI p_156917;
					NI TMP687;
					NI TMP688;
					NimStringDesc* x;
					NimStringDesc* LOC10;
					NI TMP689;
					void* LOC11;
					NI TMP690;
					NI TMP691;
					NI TMP692;
					if (!(res_156913 <= HEX3Atmp_156911)) goto LA9;
					nimln(1876, "system.nim");
					i_156909 = res_156913;
					nimln(761, "os.nim");
					if ((NU)(i_156909) >= (NU)(environment_131409->Sup.len)) raiseIndexError();
					p_156917 = nsuFindChar(environment_131409->data[i_156909], 61, ((NI) 0));
					nimln(762, "os.nim");
					if ((NU)(i_156909) >= (NU)(environment_131409->Sup.len)) raiseIndexError();
					TMP687 = subInt(p_156917, ((NI) 1));
					key_156871 = copyStrLast(environment_131409->data[i_156909], ((NI) 0), (NI)(TMP687));
					nimln(763, "os.nim");
					if ((NU)(i_156909) >= (NU)(environment_131409->Sup.len)) raiseIndexError();
					TMP688 = addInt(p_156917, ((NI) 1));
					val_156872 = copyStr(environment_131409->data[i_156909], (NI)(TMP688));
					nimln(689, "osproc.nim");
					LOC10 = 0;
					LOC10 = rawNewString(key_156871->Sup.len + val_156872->Sup.len + 1);
appendString(LOC10, key_156871);
appendString(LOC10, ((NimStringDesc*) &TMP676));
appendString(LOC10, val_156872);
					x = LOC10;
					nimln(690, "osproc.nim");
					if ((NU)(i) > (NU)(100000000)) raiseIndexError();
					TMP689 = addInt((x ? x->Sup.len : 0), ((NI) 1));
					LOC11 = 0;
					LOC11 = alloc_8401(((NI)chckRange((NI)(TMP689), ((NI) 0), ((NI) IL64(9223372036854775807)))));
					result[(i)- 0] = ((NCSTRING) (LOC11));
					nimln(691, "osproc.nim");
					if ((NU)(i) > (NU)(100000000)) raiseIndexError();
					if ((NU)(((NI) 0)) > (NU)(x->Sup.len)) raiseIndexError();
					TMP690 = addInt((x ? x->Sup.len : 0), ((NI) 1));
					memcpy(((void*) (result[(i)- 0])), ((void*) ((&x->data[((NI) 0)]))), ((NI)chckRange((NI)(TMP690), ((NI) 0), ((NI) IL64(9223372036854775807)))));
					nimln(692, "osproc.nim");
					TMP691 = addInt(i, ((NI) 1));
					i = (NI)(TMP691);
					nimln(1895, "system.nim");
					TMP692 = addInt(res_156913, ((NI) 1));
					res_156913 = (NI)(TMP692);
				} LA9: ;
			}
		}
	}
	popFrame();
	return result;
}

static N_INLINE(void, pushSafePoint)(TSafePoint* s) {
	(*s).hasRaiseAction = NIM_FALSE;
	(*s).prev = exchandler_20843;
	exchandler_20843 = s;
}

N_NIMCALL(void, startprocessfail_157819)(Startprocessdata156948* data) {
	int error;
	NI LOC1;
	error = errno;
	LOC1 = 0;
	LOC1 = write((*data).perrorpipe[(((NI) 1))- 0], ((void*) ((&error))), ((NI) 4));
	_exit(((NI) 1));
}

N_CDECL(void, startprocessafterfork_157004)(Startprocessdata156948* data) {
	int LOC42;
	int LOC43;
	{
		int LOC5;
		int LOC11;
		int LOC17;
		if (!!((*data).optionpoparentstreams)) goto LA3;
		LOC5 = 0;
		LOC5 = close((*data).pstdin[(((NI) 1))- 0]);
		{
			int LOC8;
			LOC8 = 0;
			LOC8 = dup2((*data).pstdin[(((NI) 0))- 0], ((int) 0));
			if (!(LOC8 < ((NI32) 0))) goto LA9;
			startprocessfail_157819(data);
		}
		LA9: ;
		LOC11 = 0;
		LOC11 = close((*data).pstdout[(((NI) 0))- 0]);
		{
			int LOC14;
			LOC14 = 0;
			LOC14 = dup2((*data).pstdout[(((NI) 1))- 0], ((int) 1));
			if (!(LOC14 < ((NI32) 0))) goto LA15;
			startprocessfail_157819(data);
		}
		LA15: ;
		LOC17 = 0;
		LOC17 = close((*data).pstderr[(((NI) 0))- 0]);
		{
			if (!(*data).optionpostderrtostdout) goto LA20;
			{
				int LOC24;
				LOC24 = 0;
				LOC24 = dup2((*data).pstdout[(((NI) 1))- 0], ((int) 2));
				if (!(LOC24 < ((NI32) 0))) goto LA25;
				startprocessfail_157819(data);
			}
			LA25: ;
		}
		goto LA18;
		LA20: ;
		{
			{
				int LOC30;
				LOC30 = 0;
				LOC30 = dup2((*data).pstderr[(((NI) 1))- 0], ((int) 2));
				if (!(LOC30 < ((NI32) 0))) goto LA31;
				startprocessfail_157819(data);
			}
			LA31: ;
		}
		LA18: ;
	}
	LA3: ;
	{
		if (!(((NI) 0) < ((*data).workingdir ? strlen((*data).workingdir) : 0))) goto LA35;
		{
			int LOC39;
			LOC39 = 0;
			LOC39 = chdir((*data).workingdir);
			if (!(LOC39 < ((NI32) 0))) goto LA40;
			startprocessfail_157819(data);
		}
		LA40: ;
	}
	LA35: ;
	LOC42 = 0;
	LOC42 = close((*data).perrorpipe[(((NI) 0))- 0]);
	LOC43 = 0;
	LOC43 = fcntl((*data).perrorpipe[(((NI) 1))- 0], F_SETFD, FD_CLOEXEC);
	{
		int LOC48;
		if (!(*data).optionpousepath) goto LA46;
		LOC48 = 0;
		LOC48 = execvpe((*data).syscommand, (*data).sysargs, (*data).sysenv);
	}
	goto LA44;
	LA46: ;
	{
		int LOC50;
		LOC50 = 0;
		LOC50 = execve((*data).syscommand, (*data).sysargs, (*data).sysenv);
	}
	LA44: ;
	startprocessfail_157819(data);
}

static N_INLINE(void, popSafePoint)(void) {
	exchandler_20843 = (*exchandler_20843).prev;
}

static N_INLINE(void, setFrame)(TFrame* s) {
	frameptr_20842 = s;
}

N_NIMCALL(pid_t, startprocessauxfork_157001)(Startprocessdata156948* data) {
	pid_t volatile result;
	TSafePoint TMP696;
	nimfr("startProcessAuxFork", "osproc.nim")
{	result = 0;
	nimln(847, "osproc.nim");
	{
		int LOC3;
		NI32 LOC6;
		nimln(349, "system.nim");
		nimln(847, "osproc.nim");
		LOC3 = 0;
		LOC3 = pipe((*data).perrorpipe);
		if (!!((LOC3 == ((NI32) 0)))) goto LA4;
		nimln(848, "osproc.nim");
		LOC6 = 0;
		LOC6 = oslasterror_127034();
		raiseoserror_127009(LOC6, ((NimStringDesc*) &TMP633));
	}
	LA4: ;
	nimln(850, "osproc.nim");
	pushSafePoint(&TMP696);
	TMP696.status = setjmp(TMP696.context);
	if (TMP696.status == 0) {
		pid_t volatile pid;
		Startprocessdata156948 datacopy;
		int LOC12;
		int error;
		NI sizeread;
		int LOC25;
		pid = 0;
		nimln(854, "osproc.nim");
		datacopy = (*data);
		nimln(867, "osproc.nim");
		pid = fork();
		nimln(868, "osproc.nim");
		{
			if (!(pid == ((NI) 0))) goto LA10;
			nimln(869, "osproc.nim");
			startprocessafterfork_157004((&datacopy));
			nimln(870, "osproc.nim");
			_exit(((NI) 1));
		}
		LA10: ;
		nimln(872, "osproc.nim");
		LOC12 = 0;
		LOC12 = close((*data).perrorpipe[(((NI) 1))- 0]);
		nimln(873, "osproc.nim");
		{
			NI32 LOC17;
			if (!(pid < ((NI) 0))) goto LA15;
			LOC17 = 0;
			LOC17 = oslasterror_127034();
			raiseoserror_127009(LOC17, ((NimStringDesc*) &TMP633));
		}
		LA15: ;
		error = 0;
		nimln(876, "osproc.nim");
		sizeread = read((*data).perrorpipe[(((NI) 0))- 0], ((void*) ((&error))), ((NI) 4));
		nimln(877, "osproc.nim");
		{
			TY157812 LOC22;
			NCSTRING LOC23;
			NimStringDesc* LOC24;
			if (!(sizeread == ((NI) 4))) goto LA20;
			nimln(878, "osproc.nim");
			memset((void*)LOC22, 0, sizeof(LOC22));
			nimln(879, "osproc.nim");
			LOC22[0] = cstrToNimstr((*data).syscommand);
			LOC23 = 0;
			LOC23 = strerror(error);
			LOC22[1] = cstrToNimstr(LOC23);
			LOC24 = 0;
			LOC24 = nsuFormatOpenArray(((NimStringDesc*) &TMP698), LOC22, 2);
			nosraiseOSError(LOC24);
		}
		LA20: ;
		nimln(881, "osproc.nim");
		result = pid;
		popSafePoint();
		nimln(851, "osproc.nim");
		LOC25 = 0;
		LOC25 = close((*data).perrorpipe[(((NI) 0))- 0]);
		goto BeforeRet;
		popSafePoint();
	}
	else {
		popSafePoint();
		setFrame((TFrame*)&FR);
	}
	{
		int LOC28;
		LOC28 = 0;
		LOC28 = close((*data).perrorpipe[(((NI) 0))- 0]);
	}
	if (TMP696.status != 0) reraiseException();
	}BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	Cell49347* c;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(246, "gc.nim");
	c = usrtocell_53046(p);
	nimln(248, "gc.nim");
	{
		nimln(180, "gc.nim");
		(*c).refcount -= ((NI) 8);
		nimln(181, "gc.nim");
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3;
		nimln(249, "gc.nim");
		rtladdzct_54604(c);
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(Processobj155407*, nospstartProcess)(NimStringDesc* command, NimStringDesc* workingdir, NimStringDesc** args, NI argsLen0, Stringtableobj145212* env, NU8 options) {
	Processobj155407* result;
	TY156954 pstdin;
	TY156954 pstdout;
	TY156954 pstderr;
	NimStringDesc* syscommand;
	TY17205* sysargsraw;
	pid_t volatile pid;
	NCSTRING* sysargs;
	TSafePoint TMP703;
	nimfr("startProcess", "osproc.nim")
	result = 0;
	memset((void*)pstdin, 0, sizeof(pstdin));
	memset((void*)pstdout, 0, sizeof(pstdout));
	memset((void*)pstderr, 0, sizeof(pstderr));
	nimln(725, "osproc.nim");
	result = (Processobj155407*) newObj((&NTI155409), sizeof(Processobj155407));
	(*result).Sup.m_type = (&NTI155407);
	nimln(726, "osproc.nim");
	(*result).options = options;
	nimln(727, "osproc.nim");
	(*result).exitcode = ((int) -3);
	nimln(728, "osproc.nim");
	{
		nimln(1104, "system.nim");
		if (!!(((options &(1<<((((NU8) 4))&7)))!=0))) goto LA3;
		nimln(729, "osproc.nim");
		{
			NIM_BOOL LOC7;
			NIM_BOOL LOC8;
			int LOC9;
			int LOC11;
			int LOC13;
			NI32 LOC16;
			LOC7 = 0;
			LOC8 = 0;
			nimln(349, "system.nim");
			nimln(729, "osproc.nim");
			LOC9 = 0;
			LOC9 = pipe(pstdin);
			LOC8 = !((LOC9 == ((NI32) 0)));
			if (LOC8) goto LA10;
			nimln(349, "system.nim");
			nimln(729, "osproc.nim");
			LOC11 = 0;
			LOC11 = pipe(pstdout);
			LOC8 = !((LOC11 == ((NI32) 0)));
			LA10: ;
			LOC7 = LOC8;
			if (LOC7) goto LA12;
			nimln(349, "system.nim");
			nimln(730, "osproc.nim");
			LOC13 = 0;
			LOC13 = pipe(pstderr);
			LOC7 = !((LOC13 == ((NI32) 0)));
			LA12: ;
			if (!LOC7) goto LA14;
			nimln(731, "osproc.nim");
			LOC16 = 0;
			LOC16 = oslasterror_127034();
			raiseoserror_127009(LOC16, ((NimStringDesc*) &TMP633));
		}
		LA14: ;
	}
	LA3: ;
	syscommand = 0;
	sysargsraw = 0;
	nimln(735, "osproc.nim");
	{
		TY157060 LOC21;
		NimStringDesc* LOC22;
		NimStringDesc* LOC23;
		NimStringDesc* LOC24;
		nimln(1098, "system.nim");
		if (!((options &(1<<((((NU8) 2))&7)))!=0)) goto LA19;
		nimln(736, "osproc.nim");
		syscommand = copyString(((NimStringDesc*) &TMP699));
		nimln(737, "osproc.nim");
		sysargsraw = (TY17205*) newSeq((&NTI17205), 3);
		memset((void*)LOC21, 0, sizeof(LOC21));
		LOC21[0] = copyString(syscommand);
		LOC21[1] = copyString(((NimStringDesc*) &TMP700));
		LOC21[2] = copyString(command);
		LOC22 = 0;
		LOC22 = sysargsraw->data[0]; sysargsraw->data[0] = copyStringRC1(LOC21[0]);
		if (LOC22) nimGCunrefNoCycle(LOC22);
		LOC23 = 0;
		LOC23 = sysargsraw->data[1]; sysargsraw->data[1] = copyStringRC1(LOC21[1]);
		if (LOC23) nimGCunrefNoCycle(LOC23);
		LOC24 = 0;
		LOC24 = sysargsraw->data[2]; sysargsraw->data[2] = copyStringRC1(LOC21[2]);
		if (LOC24) nimGCunrefNoCycle(LOC24);
		nimln(738, "osproc.nim");
		{
			if (!!((argsLen0 == ((NI) 0)))) goto LA27;
			failedassertimpl_91603(((NimStringDesc*) &TMP701));
		}
		LA27: ;
	}
	goto LA17;
	LA19: ;
	{
		TY157201 LOC30;
		NimStringDesc* LOC31;
		nimln(740, "osproc.nim");
		syscommand = copyString(command);
		nimln(741, "osproc.nim");
		sysargsraw = (TY17205*) newSeq((&NTI17205), 1);
		memset((void*)LOC30, 0, sizeof(LOC30));
		LOC30[0] = copyString(command);
		LOC31 = 0;
		LOC31 = sysargsraw->data[0]; sysargsraw->data[0] = copyStringRC1(LOC30[0]);
		if (LOC31) nimGCunrefNoCycle(LOC31);
		{
			NimStringDesc* arg_157222;
			NI i_157479;
			arg_157222 = 0;
			nimln(1965, "system.nim");
			i_157479 = ((NI) 0);
			{
				nimln(1966, "system.nim");
				while (1) {
					NimStringDesc* LOC35;
					NI TMP702;
					if (!(i_157479 < argsLen0)) goto LA34;
					nimln(1967, "system.nim");
					if ((NU)(i_157479) >= (NU)(argsLen0)) raiseIndexError();
					arg_157222 = args[i_157479];
					nimln(743, "osproc.nim");
					sysargsraw = (TY17205*) incrSeqV2(&(sysargsraw)->Sup, sizeof(NimStringDesc*));
					LOC35 = 0;
					LOC35 = sysargsraw->data[sysargsraw->Sup.len]; sysargsraw->data[sysargsraw->Sup.len] = copyStringRC1(arg_157222);
					if (LOC35) nimGCunrefNoCycle(LOC35);
					++sysargsraw->Sup.len;
					nimln(1968, "system.nim");
					TMP702 = addInt(i_157479, ((NI) 1));
					i_157479 = (NI)(TMP702);
				} LA34: ;
			}
		}
	}
	LA17: ;
	pid = 0;
	nimln(747, "osproc.nim");
	sysargs = alloccstringarray_17601(sysargsraw->data, sysargsraw->Sup.len);
	nimln(748, "osproc.nim");
	pushSafePoint(&TMP703);
	TMP703.status = setjmp(TMP703.context);
	if (TMP703.status == 0) {
		NCSTRING* sysenv;
		TSafePoint TMP704;
		nimln(750, "osproc.nim");
		{
			if (!(env == NIM_NIL)) goto LA39;
			nimln(751, "osproc.nim");
			sysenv = envtocstringarray_156854();
		}
		goto LA37;
		LA39: ;
		{
			nimln(753, "osproc.nim");
			sysenv = envtocstringarray_156806(env);
		}
		LA37: ;
		nimln(755, "osproc.nim");
		pushSafePoint(&TMP704);
		TMP704.status = setjmp(TMP704.context);
		if (TMP704.status == 0) {
			Startprocessdata156948 data;
			memset((void*)(&data), 0, sizeof(data));
			nimln(758, "osproc.nim");
			data.syscommand = syscommand->data;
			nimln(759, "osproc.nim");
			data.sysargs = sysargs;
			nimln(760, "osproc.nim");
			data.sysenv = sysenv;
			nimln(761, "osproc.nim");
			memcpy((void*)data.pstdin, (NIM_CONST void*)pstdin, sizeof(TY156954));
			nimln(762, "osproc.nim");
			memcpy((void*)data.pstdout, (NIM_CONST void*)pstdout, sizeof(TY156954));
			nimln(763, "osproc.nim");
			memcpy((void*)data.pstderr, (NIM_CONST void*)pstderr, sizeof(TY156954));
			nimln(764, "osproc.nim");
			nimln(1098, "system.nim");
			data.optionpoparentstreams = ((options &(1<<((((NU8) 4))&7)))!=0);
			nimln(765, "osproc.nim");
			nimln(1098, "system.nim");
			data.optionpousepath = ((options &(1<<((((NU8) 1))&7)))!=0);
			nimln(766, "osproc.nim");
			nimln(1098, "system.nim");
			data.optionpostderrtostdout = ((options &(1<<((((NU8) 3))&7)))!=0);
			nimln(767, "osproc.nim");
			data.workingdir = workingdir->data;
			nimln(772, "osproc.nim");
			pid = startprocessauxfork_157001((&data));
			nimln(775, "osproc.nim");
			{
				NimStringDesc* LOC47;
				nimln(1098, "system.nim");
				if (!((options &(1<<((((NU8) 0))&7)))!=0)) goto LA45;
				nimln(776, "osproc.nim");
				LOC47 = 0;
				LOC47 = nsuJoinSep(args, argsLen0, ((NimStringDesc*) &TMP705));
				printf("%s%s%s\012", command? (command)->data:"nil", ((NimStringDesc*) &TMP705)? (((NimStringDesc*) &TMP705))->data:"nil", LOC47? (LOC47)->data:"nil");
			}
			LA45: ;
			nimln(777, "osproc.nim");
			(*result).id = pid;
			nimln(779, "osproc.nim");
			{
				nimln(1098, "system.nim");
				if (!((options &(1<<((((NU8) 4))&7)))!=0)) goto LA50;
				nimln(781, "osproc.nim");
				(*result).inhandle = ((int) 0);
				nimln(782, "osproc.nim");
				(*result).outhandle = ((int) 1);
				nimln(783, "osproc.nim");
				{
					nimln(1098, "system.nim");
					if (!((options &(1<<((((NU8) 3))&7)))!=0)) goto LA54;
					nimln(784, "osproc.nim");
					(*result).errhandle = (*result).outhandle;
				}
				goto LA52;
				LA54: ;
				{
					nimln(786, "osproc.nim");
					(*result).errhandle = ((int) 2);
				}
				LA52: ;
			}
			goto LA48;
			LA50: ;
			{
				int LOC64;
				int LOC65;
				int LOC66;
				nimln(788, "osproc.nim");
				(*result).inhandle = pstdin[(((NI) 1))- 0];
				nimln(789, "osproc.nim");
				(*result).outhandle = pstdout[(((NI) 0))- 0];
				nimln(790, "osproc.nim");
				{
					int LOC62;
					nimln(1098, "system.nim");
					if (!((options &(1<<((((NU8) 3))&7)))!=0)) goto LA60;
					nimln(791, "osproc.nim");
					(*result).errhandle = (*result).outhandle;
					nimln(792, "osproc.nim");
					LOC62 = 0;
					LOC62 = close(pstderr[(((NI) 0))- 0]);
				}
				goto LA58;
				LA60: ;
				{
					nimln(794, "osproc.nim");
					(*result).errhandle = pstderr[(((NI) 0))- 0];
				}
				LA58: ;
				nimln(795, "osproc.nim");
				LOC64 = 0;
				LOC64 = close(pstderr[(((NI) 1))- 0]);
				nimln(796, "osproc.nim");
				LOC65 = 0;
				LOC65 = close(pstdin[(((NI) 0))- 0]);
				nimln(797, "osproc.nim");
				LOC66 = 0;
				LOC66 = close(pstdout[(((NI) 1))- 0]);
			}
			LA48: ;
			popSafePoint();
		}
		else {
			popSafePoint();
			setFrame((TFrame*)&FR);
		}
		{
			nimln(755, "osproc.nim");
			dealloccstringarray_17850(sysenv);
		}
		if (TMP704.status != 0) reraiseException();
		popSafePoint();
	}
	else {
		popSafePoint();
		setFrame((TFrame*)&FR);
	}
	{
		nimln(748, "osproc.nim");
		dealloccstringarray_17850(sysargs);
	}
	if (TMP703.status != 0) reraiseException();
	popFrame();
	return result;
}

N_NIMCALL(void, nospclose)(Processobj155407* p) {
	int LOC13;
	int LOC14;
	int LOC15;
	nimfr("close", "osproc.nim")
	nimln(937, "osproc.nim");
	{
		nimln(349, "system.nim");
		if (!!(((*p).instream == NIM_NIL))) goto LA3;
		nimln(937, "osproc.nim");
		close_148291((*p).instream);
	}
	LA3: ;
	nimln(938, "osproc.nim");
	{
		nimln(349, "system.nim");
		if (!!(((*p).outstream == NIM_NIL))) goto LA7;
		nimln(938, "osproc.nim");
		close_148291((*p).outstream);
	}
	LA7: ;
	nimln(939, "osproc.nim");
	{
		nimln(349, "system.nim");
		if (!!(((*p).errstream == NIM_NIL))) goto LA11;
		nimln(939, "osproc.nim");
		close_148291((*p).errstream);
	}
	LA11: ;
	nimln(940, "osproc.nim");
	LOC13 = 0;
	LOC13 = close((*p).inhandle);
	nimln(941, "osproc.nim");
	LOC14 = 0;
	LOC14 = close((*p).outhandle);
	nimln(942, "osproc.nim");
	LOC15 = 0;
	LOC15 = close((*p).errhandle);
	popFrame();
}

N_NIMCALL(void, nospsuspend)(Processobj155407* p) {
	nimfr("suspend", "osproc.nim")
	nimln(945, "osproc.nim");
	{
		int LOC3;
		NI32 LOC6;
		nimln(349, "system.nim");
		nimln(945, "osproc.nim");
		LOC3 = 0;
		LOC3 = kill((*p).id, SIGSTOP);
		if (!!((LOC3 == ((NI32) 0)))) goto LA4;
		LOC6 = 0;
		LOC6 = oslasterror_127034();
		raiseoserror_127009(LOC6, ((NimStringDesc*) &TMP633));
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(void, nospresume)(Processobj155407* p) {
	nimfr("resume", "osproc.nim")
	nimln(948, "osproc.nim");
	{
		int LOC3;
		NI32 LOC6;
		nimln(349, "system.nim");
		nimln(948, "osproc.nim");
		LOC3 = 0;
		LOC3 = kill((*p).id, SIGCONT);
		if (!!((LOC3 == ((NI32) 0)))) goto LA4;
		LOC6 = 0;
		LOC6 = oslasterror_127034();
		raiseoserror_127009(LOC6, ((NimStringDesc*) &TMP633));
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NIM_BOOL, nosprunning)(Processobj155407* p) {
	NIM_BOOL result;
	NI ret;
	nimfr("running", "osproc.nim")
{	result = 0;
	ret = 0;
	nimln(953, "osproc.nim");
	ret = waitpid((*p).id, (&(*p).exitcode), WNOHANG);
	nimln(959, "osproc.nim");
	{
		if (!(ret == ((NI) 0))) goto LA3;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA3: ;
	nimln(960, "osproc.nim");
	result = (ret == (*p).id);
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, nospterminate)(Processobj155407* p) {
	nimfr("terminate", "osproc.nim")
	nimln(963, "osproc.nim");
	{
		int LOC3;
		NI32 LOC6;
		nimln(349, "system.nim");
		nimln(963, "osproc.nim");
		LOC3 = 0;
		LOC3 = kill((*p).id, SIGTERM);
		if (!!((LOC3 == ((NI32) 0)))) goto LA4;
		nimln(964, "osproc.nim");
		LOC6 = 0;
		LOC6 = oslasterror_127034();
		raiseoserror_127009(LOC6, ((NimStringDesc*) &TMP633));
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(void, nospkill)(Processobj155407* p) {
	nimfr("kill", "osproc.nim")
	nimln(967, "osproc.nim");
	{
		int LOC3;
		NI32 LOC6;
		nimln(349, "system.nim");
		nimln(967, "osproc.nim");
		LOC3 = 0;
		LOC3 = kill((*p).id, SIGKILL);
		if (!!((LOC3 == ((NI32) 0)))) goto LA4;
		nimln(968, "osproc.nim");
		LOC6 = 0;
		LOC6 = oslasterror_127034();
		raiseoserror_127009(LOC6, ((NimStringDesc*) &TMP633));
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NI, nospwaitForExit)(Processobj155407* p, NI timeout) {
	NI result;
	nimfr("waitForExit", "osproc.nim")
{	result = 0;
	nimln(975, "osproc.nim");
	{
		nimln(349, "system.nim");
		if (!!(((*p).exitcode == ((NI32) -3)))) goto LA3;
		nimln(975, "osproc.nim");
		result = ((NI) ((*p).exitcode));
		goto BeforeRet;
	}
	LA3: ;
	nimln(976, "osproc.nim");
	{
		pid_t LOC7;
		NI32 LOC10;
		LOC7 = 0;
		LOC7 = waitpid((*p).id, (&(*p).exitcode), ((int) 0));
		if (!(LOC7 < ((NI) 0))) goto LA8;
		nimln(977, "osproc.nim");
		(*p).exitcode = ((int) -3);
		nimln(978, "osproc.nim");
		LOC10 = 0;
		LOC10 = oslasterror_127034();
		raiseoserror_127009(LOC10, ((NimStringDesc*) &TMP633));
	}
	LA8: ;
	nimln(979, "osproc.nim");
	result = (NI)((NU64)(((NI) ((*p).exitcode))) >> (NU64)(((NI) 8)));
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, peekexitcode_155725)(Processobj155407* p) {
	NI result;
	pid_t ret;
	NIM_BOOL b;
	nimfr("peekExitCode", "osproc.nim")
{	result = 0;
	nimln(982, "osproc.nim");
	{
		nimln(349, "system.nim");
		if (!!(((*p).exitcode == ((NI32) -3)))) goto LA3;
		nimln(982, "osproc.nim");
		result = ((NI) ((*p).exitcode));
		goto BeforeRet;
	}
	LA3: ;
	nimln(983, "osproc.nim");
	ret = waitpid((*p).id, (&(*p).exitcode), WNOHANG);
	nimln(984, "osproc.nim");
	b = (ret == (*p).id);
	nimln(985, "osproc.nim");
	{
		if (!b) goto LA7;
		result = ((NI) -1);
	}
	LA7: ;
	nimln(986, "osproc.nim");
	{
		NIM_BOOL LOC11;
		LOC11 = 0;
		LOC11 = WIFEXITED((*p).exitcode);
		if (!!(LOC11)) goto LA12;
		result = ((NI) -1);
	}
	goto LA9;
	LA12: ;
	{
		nimln(987, "osproc.nim");
		result = (NI)((NU64)(((NI) ((*p).exitcode))) >> (NU64)(((NI) 8)));
	}
	LA9: ;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, createstream_158641)(Streamobj148227** stream, int* handle, NU8 filemode) {
	FILE* f;
	Filestreamobj149467* LOC7;
	nimfr("createStream", "osproc.nim")
	f = 0;
	nimln(992, "osproc.nim");
	{
		NIM_BOOL LOC3;
		NI32 LOC6;
		LOC3 = 0;
		LOC3 = open_16811(&f, (*handle), filemode);
		if (!!(LOC3)) goto LA4;
		LOC6 = 0;
		LOC6 = oslasterror_127034();
		raiseoserror_127009(LOC6, ((NimStringDesc*) &TMP633));
	}
	LA4: ;
	nimln(993, "osproc.nim");
	LOC7 = 0;
	LOC7 = newfilestream_149544(f);
	unsureAsgnRef((void**) (&(*stream)), &LOC7->Sup);
	popFrame();
}

N_NIMCALL(Streamobj148227*, nospinputStream)(Processobj155407* p) {
	Streamobj148227* result;
	nimfr("inputStream", "osproc.nim")
{	result = 0;
	nimln(996, "osproc.nim");
	{
		if (!((*p).instream == NIM_NIL)) goto LA3;
		nimln(997, "osproc.nim");
		createstream_158641(&(*p).instream, (&(*p).inhandle), ((NU8) 1));
	}
	LA3: ;
	nimln(998, "osproc.nim");
	result = (*p).instream;
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(Streamobj148227*, nospoutputStream)(Processobj155407* p) {
	Streamobj148227* result;
	nimfr("outputStream", "osproc.nim")
{	result = 0;
	nimln(1001, "osproc.nim");
	{
		if (!((*p).outstream == NIM_NIL)) goto LA3;
		nimln(1002, "osproc.nim");
		createstream_158641(&(*p).outstream, (&(*p).outhandle), ((NU8) 0));
	}
	LA3: ;
	nimln(1003, "osproc.nim");
	result = (*p).outstream;
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(Streamobj148227*, nosperrorStream)(Processobj155407* p) {
	Streamobj148227* result;
	nimfr("errorStream", "osproc.nim")
{	result = 0;
	nimln(1006, "osproc.nim");
	{
		if (!((*p).errstream == NIM_NIL)) goto LA3;
		nimln(1007, "osproc.nim");
		createstream_158641(&(*p).errstream, (&(*p).errhandle), ((NU8) 0));
	}
	LA3: ;
	nimln(1008, "osproc.nim");
	result = (*p).errstream;
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, nospexecCmd)(NimStringDesc* command) {
	NI result;
	int LOC1;
	nimfr("execCmd", "osproc.nim")
	result = 0;
	nimln(1015, "osproc.nim");
	LOC1 = 0;
	LOC1 = system(command->data);
	result = ((NI) ((NI32)((NU32)(LOC1) >> (NU32)(((NI32) 8)))));
	popFrame();
	return result;
}

N_NIMCALL(void, createfdset_158804)(fd_set* fd, TY156201* s, NI* m) {
	nimfr("createFdSet", "osproc.nim")
	nimln(1020, "osproc.nim");
	FD_ZERO(fd);
	{
		Processobj155407* i_159011;
		NI i_159029;
		NI L_159031;
		i_159011 = 0;
		nimln(3365, "system.nim");
		i_159029 = ((NI) 0);
		nimln(3366, "system.nim");
		L_159031 = (s ? s->Sup.len : 0);
		{
			nimln(3367, "system.nim");
			while (1) {
				NI TMP706;
				if (!(i_159029 < L_159031)) goto LA3;
				nimln(3368, "system.nim");
				if ((NU)(i_159029) >= (NU)(s->Sup.len)) raiseIndexError();
				i_159011 = s->data[i_159029];
				nimln(1022, "osproc.nim");
				(*m) = (((*m) >= ((NI) ((*i_159011).outhandle))) ? (*m) : ((NI) ((*i_159011).outhandle)));
				nimln(1023, "osproc.nim");
				FD_SET((*i_159011).outhandle, fd);
				nimln(3369, "system.nim");
				TMP706 = addInt(i_159029, ((NI) 1));
				i_159029 = (NI)(TMP706);
				nimln(3370, "system.nim");
				{
					if (!!(((s ? s->Sup.len : 0) == L_159031))) goto LA6;
					failedassertimpl_91603(((NimStringDesc*) &TMP707));
				}
				LA6: ;
			} LA3: ;
		}
	}
	popFrame();
}

N_NIMCALL(void, pruneprocessset_159044)(TY156201** s, fd_set* fd) {
	NI i;
	NI L;
	nimfr("pruneProcessSet", "osproc.nim")
	nimln(1026, "osproc.nim");
	i = ((NI) 0);
	nimln(1027, "osproc.nim");
	L = ((*s) ? (*s)->Sup.len : 0);
	{
		nimln(1028, "osproc.nim");
		while (1) {
			if (!(i < L)) goto LA2;
			nimln(1029, "osproc.nim");
			{
				int LOC5;
				NI TMP708;
				NI TMP709;
				if ((NU)(i) >= (NU)((*s)->Sup.len)) raiseIndexError();
				LOC5 = 0;
				LOC5 = FD_ISSET((*(*s)->data[i]).outhandle, fd);
				if (!(LOC5 == ((NI32) 0))) goto LA6;
				nimln(1030, "osproc.nim");
				if ((NU)(i) >= (NU)((*s)->Sup.len)) raiseIndexError();
				TMP708 = subInt(L, ((NI) 1));
				if ((NU)((NI)(TMP708)) >= (NU)((*s)->Sup.len)) raiseIndexError();
				asgnRef((void**) (&(*s)->data[i]), (*s)->data[(NI)(TMP708)]);
				nimln(1031, "osproc.nim");
				TMP709 = subInt(L, ((NI) 1));
				L = (NI)(TMP709);
			}
			goto LA3;
			LA6: ;
			{
				NI TMP710;
				nimln(1033, "osproc.nim");
				TMP710 = addInt(i, ((NI) 1));
				i = (NI)(TMP710);
			}
			LA3: ;
		} LA2: ;
	}
	nimln(1034, "osproc.nim");
	(*s) = (TY156201*) setLengthSeq(&((*s))->Sup, sizeof(Processobj155407*), ((NI)chckRange(L, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	popFrame();
}

N_NIMCALL(NI, select_156635)(TY156201** readfds, NI timeout) {
	NI result;
	struct timeval tv;
	NI TMP711;
	fd_set rd;
	NI m;
	nimfr("select", "osproc.nim")
	result = 0;
	memset((void*)(&tv), 0, sizeof(tv));
	nimln(1038, "osproc.nim");
	tv.tv_sec = ((NI) 0);
	nimln(1039, "osproc.nim");
	TMP711 = mulInt(timeout, ((NI) 1000));
	tv.tv_usec = (NI)(TMP711);
	memset((void*)(&rd), 0, sizeof(rd));
	nimln(1042, "osproc.nim");
	m = ((NI) 0);
	nimln(1043, "osproc.nim");
	createfdset_158804((&rd), (*readfds), (&m));
	nimln(1045, "osproc.nim");
	{
		NI TMP712;
		int LOC5;
		nimln(349, "system.nim");
		if (!!((timeout == ((NI) -1)))) goto LA3;
		nimln(1046, "osproc.nim");
		TMP712 = addInt(m, ((NI) 1));
		LOC5 = 0;
		LOC5 = select(((int)chckRange((NI)(TMP712), ((int) (-2147483647 -1)), ((int) 2147483647))), (&rd), NIM_NIL, NIM_NIL, (&tv));
		result = ((NI) (LOC5));
	}
	goto LA1;
	LA3: ;
	{
		NI TMP713;
		int LOC7;
		nimln(1048, "osproc.nim");
		TMP713 = addInt(m, ((NI) 1));
		LOC7 = 0;
		LOC7 = select(((int)chckRange((NI)(TMP713), ((int) (-2147483647 -1)), ((int) 2147483647))), (&rd), NIM_NIL, NIM_NIL, NIM_NIL);
		result = ((NI) (LOC7));
	}
	LA1: ;
	nimln(1050, "osproc.nim");
	pruneprocessset_159044(readfds, (&rd));
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, hasdata_159164)(Processobj155407* p) {
	NIM_BOOL result;
	fd_set rd;
	NI m;
	NI TMP714;
	int LOC1;
	nimfr("hasData", "osproc.nim")
	result = 0;
	memset((void*)(&rd), 0, sizeof(rd));
	nimln(1055, "osproc.nim");
	FD_ZERO((&rd));
	nimln(1056, "osproc.nim");
	m = ((((NI) 0) >= ((NI) ((*p).outhandle))) ? ((NI) 0) : ((NI) ((*p).outhandle)));
	nimln(1057, "osproc.nim");
	FD_SET((*p).outhandle, (&rd));
	nimln(1059, "osproc.nim");
	TMP714 = addInt(m, ((NI) 1));
	LOC1 = 0;
	LOC1 = select(((int)chckRange((NI)(TMP714), ((int) (-2147483647 -1)), ((int) 2147483647))), (&rd), NIM_NIL, NIM_NIL, NIM_NIL);
	result = (((NI) (LOC1)) == ((NI) 1));
	popFrame();
	return result;
}

N_NIMCALL(void, execcmdex_159404)(NimStringDesc* command, NU8 options, TY159410* Result) {
	Processobj155407* p;
	TY155637 LOC1;
	Streamobj148227* outp;
	NimStringDesc* line;
	nimfr("execCmdEx", "osproc.nim")
	nimln(1072, "osproc.nim");
	memset((void*)LOC1, 0, sizeof(LOC1));
	p = nospstartProcess(command, ((NimStringDesc*) &TMP633), LOC1, 0, NIM_NIL, (options | 4));
	nimln(1073, "osproc.nim");
	outp = nospoutputStream(p);
	nimln(1074, "osproc.nim");
	unsureAsgnRef((void**) (&(*Result).Field0), copyString(TMP715.Field0));
	(*Result).Field1 = TMP715.Field1;
	nimln(1075, "osproc.nim");
	line = rawNewString(((NI) 120));
	{
		nimln(1076, "osproc.nim");
		while (1) {
			nimln(1077, "osproc.nim");
			{
				NIM_BOOL LOC6;
				LOC6 = 0;
				LOC6 = readline_149242(outp, (&line));
				if (!LOC6) goto LA7;
				nimln(1078, "osproc.nim");
				(*Result).Field0 = resizeString((*Result).Field0, line->Sup.len + 0);
appendString((*Result).Field0, line);
				nimln(1079, "osproc.nim");
				(*Result).Field0 = resizeString((*Result).Field0, 1);
appendString((*Result).Field0, ((NimStringDesc*) &TMP673));
			}
			goto LA4;
			LA7: ;
			{
				nimln(1081, "osproc.nim");
				(*Result).Field1 = peekexitcode_155725(p);
				nimln(1082, "osproc.nim");
				{
					nimln(349, "system.nim");
					if (!!(((*Result).Field1 == ((NI) -1)))) goto LA12;
					nimln(1082, "osproc.nim");
					goto LA2;
				}
				LA12: ;
			}
			LA4: ;
		}
	} LA2: ;
	nimln(1083, "osproc.nim");
	nospclose(p);
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, HEX00_osprocInit000)(void) {
	nimfr("osproc", "osproc.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, HEX00_osprocDatInit000)(void) {
static TNimNode* TMP645[9];
static TNimNode* TMP647[7];
NI TMP649;
static char* NIM_CONST TMP648[7] = {
"poEchoCmd", 
"poUsePath", 
"poEvalCommand", 
"poStdErrToStdOut", 
"poParentStreams", 
"poInteractive", 
"poDemon"};
static TNimNode TMP140[19];
NTI155407.size = sizeof(Processobj155407);
NTI155407.kind = 17;
NTI155407.base = (&NTI4011);
TMP645[0] = &TMP140[1];
TMP140[1].kind = 1;
TMP140[1].offset = offsetof(Processobj155407, inhandle);
TMP140[1].typ = (&NTI16408);
TMP140[1].name = "inHandle";
TMP645[1] = &TMP140[2];
TMP140[2].kind = 1;
TMP140[2].offset = offsetof(Processobj155407, outhandle);
TMP140[2].typ = (&NTI16408);
TMP140[2].name = "outHandle";
TMP645[2] = &TMP140[3];
TMP140[3].kind = 1;
TMP140[3].offset = offsetof(Processobj155407, errhandle);
TMP140[3].typ = (&NTI16408);
TMP140[3].name = "errHandle";
TMP645[3] = &TMP140[4];
TMP140[4].kind = 1;
TMP140[4].offset = offsetof(Processobj155407, instream);
TMP140[4].typ = (&NTI148225);
TMP140[4].name = "inStream";
TMP645[4] = &TMP140[5];
TMP140[5].kind = 1;
TMP140[5].offset = offsetof(Processobj155407, outstream);
TMP140[5].typ = (&NTI148225);
TMP140[5].name = "outStream";
TMP645[5] = &TMP140[6];
TMP140[6].kind = 1;
TMP140[6].offset = offsetof(Processobj155407, errstream);
TMP140[6].typ = (&NTI148225);
TMP140[6].name = "errStream";
TMP645[6] = &TMP140[7];
TMP140[7].kind = 1;
TMP140[7].offset = offsetof(Processobj155407, id);
TMP140[7].typ = (&NTI114289);
TMP140[7].name = "id";
TMP645[7] = &TMP140[8];
TMP140[8].kind = 1;
TMP140[8].offset = offsetof(Processobj155407, exitcode);
TMP140[8].typ = (&NTI8211);
TMP140[8].name = "exitCode";
TMP645[8] = &TMP140[9];
NTI155405.size = sizeof(NU8);
NTI155405.kind = 14;
NTI155405.base = 0;
NTI155405.flags = 3;
for (TMP649 = 0; TMP649 < 7; TMP649++) {
TMP140[TMP649+10].kind = 1;
TMP140[TMP649+10].offset = TMP649;
TMP140[TMP649+10].name = TMP648[TMP649];
TMP647[TMP649] = &TMP140[TMP649+10];
}
TMP140[17].len = 7; TMP140[17].kind = 2; TMP140[17].sons = &TMP647[0];
NTI155405.node = &TMP140[17];
NTI155649.size = sizeof(NU8);
NTI155649.kind = 19;
NTI155649.base = (&NTI155405);
NTI155649.flags = 3;
TMP140[18].len = 0; TMP140[18].kind = 0;
NTI155649.node = &TMP140[18];
TMP140[9].kind = 1;
TMP140[9].offset = offsetof(Processobj155407, options);
TMP140[9].typ = (&NTI155649);
TMP140[9].name = "options";
TMP140[0].len = 9; TMP140[0].kind = 2; TMP140[0].sons = &TMP645[0];
NTI155407.node = &TMP140[0];
NTI155409.size = sizeof(Processobj155407*);
NTI155409.kind = 22;
NTI155409.base = (&NTI155407);
NTI155409.marker = TMP650;
NTI156201.size = sizeof(TY156201*);
NTI156201.kind = 24;
NTI156201.base = (&NTI155409);
NTI156201.marker = TMP651;
}

