/* Generated by Nim Compiler v0.12.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nim -o /home/marco/saus/advent-of-code-2019/17.nim/nimcache/program.o /home/marco/saus/advent-of-code-2019/17.nim/nimcache/program.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <stdio.h>
#include <sys/types.h>
typedef struct Processobj155407 Processobj155407;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Stringtableobj145212 Stringtableobj145212;
typedef struct Streamobj148227 Streamobj148227;
typedef struct Robot160065 Robot160065;
typedef struct Square160039 Square160039;
typedef struct TY160418 TY160418;
typedef struct TY112900 TY112900;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct TY160531 TY160531;
typedef struct Intersection160520 Intersection160520;
typedef struct Forward160692 Forward160692;
typedef struct Route160789 Route160789;
typedef struct TY17205 TY17205;
typedef struct Cell49347 Cell49347;
typedef struct Cellseq49363 Cellseq49363;
typedef struct Gcheap51418 Gcheap51418;
typedef struct Gcstack51416 Gcstack51416;
typedef struct Cellset49359 Cellset49359;
typedef struct Pagedesc49355 Pagedesc49355;
typedef struct Memregion31291 Memregion31291;
typedef struct Smallchunk31243 Smallchunk31243;
typedef struct Llchunk31285 Llchunk31285;
typedef struct Bigchunk31245 Bigchunk31245;
typedef struct Intset31217 Intset31217;
typedef struct Trunk31213 Trunk31213;
typedef struct Avlnode31289 Avlnode31289;
typedef struct Gcstat51414 Gcstat51414;
typedef struct Program161804 Program161804;
typedef struct TY161805 TY161805;
typedef struct TY162087 TY162087;
typedef struct Solvedprogram162457 Solvedprogram162457;
typedef struct Message162664 Message162664;
typedef struct TNimObject TNimObject;
typedef struct Keyvaluepairseq145210 Keyvaluepairseq145210;
typedef struct Basechunk31241 Basechunk31241;
typedef struct Freecell31233 Freecell31233;
typedef struct TY109772 TY109772;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NimStringDesc* TY155637[1];
typedef NimStringDesc* TY157201[1];
struct Robot160065 {
NI Field0;
NI Field1;
NU8 Field2;
};
struct Square160039 {
NI Field0;
NI Field1;
NIM_CHAR Field2;
};
typedef Square160039 TY160051[40];
typedef TY160051 Chart160047[31];
struct TY112900 {
NI Field0;
NI Field1;
};
typedef N_NIMCALL_PTR(void, TY3889) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3894) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3889 marker;
TY3894 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct Intersection160520 {
NI Field0;
NI Field1;
NU8 Field2;
};
struct Forward160692 {
NI Field0;
TY160531* Field1;
};
struct  Cell49347  {
NI refcount;
TNimType* typ;
};
struct  Cellseq49363  {
NI len;
NI cap;
Cell49347** d;
};
struct  Cellset49359  {
NI counter;
NI max;
Pagedesc49355* head;
Pagedesc49355** data;
};
typedef Smallchunk31243* TY31306[512];
typedef Trunk31213* Trunkbuckets31215[256];
struct  Intset31217  {
Trunkbuckets31215 data;
};
struct  Memregion31291  {
NI minlargeobj;
NI maxlargeobj;
TY31306 freesmallchunks;
Llchunk31285* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk31245* freechunkslist;
Intset31217 chunkstarts;
Avlnode31289* root;
Avlnode31289* deleted;
Avlnode31289* last;
Avlnode31289* freeavlnodes;
};
struct  Gcstat51414  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Gcheap51418  {
Gcstack51416* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq49363 zct;
Cellseq49363 decstack;
Cellset49359 cycleroots;
Cellseq49363 tempstack;
NI recgclock;
Memregion31291 region;
Gcstat51414 stat;
};
struct Route160789 {
TY17205* Field0;
NIM_BOOL Field1;
};
struct Program161804 {
TY161805* Field0;
NIM_BOOL Field1;
};
typedef TY17205* TY161838[1];
typedef NU8 TY162124[3];
struct Solvedprogram162457 {
Program161804 Field0;
Route160789 Field1;
};
struct Message162664 {
TY17205* Field0;
TY17205* Field1;
TY17205* Field2;
TY17205* Field3;
};
typedef NimStringDesc* TY157060[3];
struct  TNimObject  {
TNimType* m_type;
};
struct  Processobj155407  {
  TNimObject Sup;
int inhandle;
int outhandle;
int errhandle;
Streamobj148227* instream;
Streamobj148227* outstream;
Streamobj148227* errstream;
pid_t id;
int exitcode;
NU8 options;
};
struct  Stringtableobj145212  {
  TNimObject Sup;
NI counter;
Keyvaluepairseq145210* data;
NU8 mode;
};
typedef N_NIMCALL_PTR(void, TY148228) (Streamobj148227* s);
typedef N_NIMCALL_PTR(NIM_BOOL, TY148232) (Streamobj148227* s);
typedef N_NIMCALL_PTR(void, TY148236) (Streamobj148227* s, NI pos);
typedef N_NIMCALL_PTR(NI, TY148241) (Streamobj148227* s);
typedef N_NIMCALL_PTR(NI, TY148245) (Streamobj148227* s, void* buffer, NI buflen);
typedef N_NIMCALL_PTR(NI, TY148251) (Streamobj148227* s, void* buffer, NI buflen);
typedef N_NIMCALL_PTR(void, TY148257) (Streamobj148227* s, void* buffer, NI buflen);
typedef N_NIMCALL_PTR(void, TY148263) (Streamobj148227* s);
struct  Streamobj148227  {
  TNimObject Sup;
TY148228 closeimpl;
TY148232 atendimpl;
TY148236 setpositionimpl;
TY148241 getpositionimpl;
TY148245 readdataimpl;
TY148251 peekdataimpl;
TY148257 writedataimpl;
TY148263 flushimpl;
};
struct  Gcstack51416  {
Gcstack51416* prev;
Gcstack51416* next;
void* starts;
void* pos;
NI maxstacksize;
};
typedef NI TY31222[8];
struct  Pagedesc49355  {
Pagedesc49355* next;
NI key;
TY31222 bits;
};
struct  Basechunk31241  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk31243  {
  Basechunk31241 Sup;
Smallchunk31243* next;
Smallchunk31243* prev;
Freecell31233* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk31285  {
NI size;
NI acc;
Llchunk31285* next;
};
struct  Bigchunk31245  {
  Basechunk31241 Sup;
Bigchunk31245* next;
Bigchunk31245* prev;
NI align;
NF data;
};
struct  Trunk31213  {
Trunk31213* next;
NI key;
TY31222 bits;
};
typedef Avlnode31289* TY31296[2];
struct  Avlnode31289  {
TY31296 link;
NI key;
NI upperbound;
NI level;
};
struct TY109772 {
NimStringDesc* Field0;
NimStringDesc* Field1;
};
struct  Freecell31233  {
Freecell31233* next;
NI zerofield;
};
struct TY160418 {
  TGenericSeq Sup;
  TY112900 data[SEQ_DECL_SIZE];
};
struct TY160531 {
  TGenericSeq Sup;
  Intersection160520 data[SEQ_DECL_SIZE];
};
struct TY17205 {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct TY161805 {
  TGenericSeq Sup;
  TY17205* data[SEQ_DECL_SIZE];
};
struct TY162087 {
  TGenericSeq Sup;
  Route160789 data[SEQ_DECL_SIZE];
};
struct Keyvaluepairseq145210 {
  TGenericSeq Sup;
  TY109772 data[SEQ_DECL_SIZE];
};
N_NIMCALL(Processobj155407*, spawnrobot_160004)(void);
N_NIMCALL(Processobj155407*, nospstartProcess)(NimStringDesc* command, NimStringDesc* workingdir, NimStringDesc** args, NI argsLen0, Stringtableobj145212* env, NU8 options);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_23601)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(void, givecommand_160013)(Processobj155407* process, NI input);
N_NIMCALL(Streamobj148227*, nospinputStream)(Processobj155407* p);
N_NIMCALL(void, writeline_148526)(Streamobj148227* s, NimStringDesc** args, NI argsLen0);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
N_NIMCALL(void, flush_148275)(Streamobj148227* s);
N_NIMCALL(NI, readouput_160026)(Processobj155407* process);
N_NIMCALL(Streamobj148227*, nospoutputStream)(Processobj155407* p);
N_NIMCALL(NimStringDesc*, readline_149277)(Streamobj148227* s);
N_NIMCALL(NI, nsuParseInt)(NimStringDesc* s);
N_NIMCALL(Robot160065, turnleft_160072)(Robot160065* robot);
N_NIMCALL(Robot160065, turnright_160125)(Robot160065* robot);
N_NIMCALL(Robot160065, move_160178)(Robot160065* robot, NI amount);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NIMCALL(void, readchart_160232)(Processobj155407* process, Chart160047* Result);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(void, write_16883)(FILE* f, NI i);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(void, write_16903)(FILE* f, NIM_CHAR c);
N_NIMCALL(NIM_BOOL, iscrosssection_160265)(Chart160047 chart, Square160039* square);
N_NIMCALL(NI, determinealignmentparamters_160334)(Chart160047 chart);
N_NIMCALL(NI, mulInt)(NI a, NI b);
N_NIMCALL(TY160418*, findintersections_160415)(Chart160047 chart);
N_NIMCALL(void, TMP735)(void* p, NI op);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq, NI elemsize);
N_NIMCALL(NIM_BOOL, isoutofbounds_160509)(Robot160065* robot);
N_NIMCALL(NIM_BOOL, shouldturnleft_160527)(Robot160065* robot, Chart160047 chart, TY160531* intersections);
N_NIMCALL(void, failedassertimpl_91603)(NimStringDesc* msg);
N_NIMCALL(NIM_BOOL, shouldturnright_160643)(Robot160065* robot, Chart160047 chart, TY160531* intersections);
N_NIMCALL(void, determinemovement_160699)(Robot160065* robot, Chart160047 chart, TY160531* intersections, Forward160692* Result);
N_NIMCALL(void, TMP745)(void* p, NI op);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src_86204, TNimType* mt);
N_NIMCALL(TY160531*, tointersections_160796)(TY160418* coords);
N_NIMCALL(NIM_BOOL, isstuckinaloopat_161047)(TY160531* intersections, Intersection160520* place);
N_NIMCALL(void, printintersection_161085)(Intersection160520* intersection);
static N_INLINE(void, writeline_161120)(FILE* f, NimStringDesc** x, NI xLen0);
N_NIMCALL(void, write_16895)(FILE* f, NimStringDesc* s);
N_NIMCALL(void, printintersections_161102)(TY160531* intersections);
N_NIMCALL(void, findroute_161178)(Chart160047 chart, TY160531* intersections, Route160789* Result);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(Cell49347*, usrtocell_53046)(void* usr);
static N_INLINE(void, rtladdzct_54604)(Cell49347* c);
N_NOINLINE(void, addzct_53017)(Cellseq49363* s, Cell49347* c);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(NimStringDesc*, nsuIntToStr)(NI x, NI minchars);
N_NIMCALL(TY17205*, duplicate_161318)(TY17205* route);
N_NIMCALL(NIM_BOOL, containtsat_161443)(TY17205* route, TY17205* command, NI index);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(TY17205*, replace_161499)(TY17205* route, TY17205* command);
N_NIMCALL(TY17205*, first_161573)(TY17205* route, NI amount);
N_NIMCALL(NIM_BOOL, isvalidlength_161674)(TY17205* command);
N_NIMCALL(NIM_BOOL, doesnotcontainterminator_161720)(TY17205* command);
N_NIMCALL(NIM_BOOL, isvalid_161756)(TY17205* command);
N_NIMCALL(NIM_BOOL, isempty_161767)(TY17205* route);
N_NIMCALL(void, findprogramimpl_161812)(TY17205* route, NI depth, Program161804* Result);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP780)(void* p, NI op);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(void, findprogram_162069)(TY17205* route, Program161804* Result);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_NIMCALL(TY162087*, findrouteswithintersections_162080)(Chart160047 chart, TY160531** intersections, NI i);
N_NIMCALL(void, TMP788)(void* p, NI op);
N_NIMCALL(void, findsolvableroute_162463)(Chart160047 chart, Solvedprogram162457* Result);
N_NIMCALL(void, print_162574)(Chart160047 chart);
N_NIMCALL(void, findmessage_162676)(Solvedprogram162457* program, Message162664* Result);
N_NIMCALL(void, sendstring_162827)(Processobj155407* robot, NimStringDesc* text);
N_NIMCALL(void, sendline_162855)(Processobj155407* robot, TY17205* line);
N_NIMCALL(void, send_162902)(Processobj155407* robot, Message162664* message);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incref_55422)(Cell49347* c);
static N_INLINE(NIM_BOOL, canbecycleroot_53067)(Cell49347* c);
static N_INLINE(void, rtladdcycleroot_53823)(Cell49347* c);
N_NOINLINE(void, incl_50065)(Cellset49359* s, Cell49347* cell);
static N_INLINE(void, decref_55004)(Cell49347* c);
N_NIMCALL(void, write_16911)(FILE* f, NimStringDesc** a, NI aLen0);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_timesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_timesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_posixInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_posixDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_osInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_osDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_etcprivInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_etcprivDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_hashesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_hashesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_strtabsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_strtabsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_streamsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_streamsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_linuxInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_linuxDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_cpuinfoInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_cpuinfoDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_osprocInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_osprocDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, programInit000)(void);
NIM_EXTERNC N_NOINLINE(void, programDatInit000)(void);
STRING_LITERAL(TMP716, "./intcode", 9);
STRING_LITERAL(TMP717, ".", 1);
STRING_LITERAL(TMP739, "len(a) == L seq modified while iterating over it", 48);
STRING_LITERAL(TMP752, "\012", 1);
STRING_LITERAL(TMP755, ";", 1);
NIM_CONST TY157201 TMP754 = {((NimStringDesc*) &TMP755)}
;
NIM_CONST TY112900 TMP756 = {((NI) 24),
((NI) 4)}
;
NIM_CONST Robot160065 TMP757 = {((NI) 4),
((NI) 0),
((NU8) 0)}
;
STRING_LITERAL(TMP758, "L", 1);
STRING_LITERAL(TMP759, "R", 1);
STRING_LITERAL(TMP765, "NOPE", 4);
NIM_CONST struct {
  TGenericSeq Sup;
  TY17205* data[0];
} CNSTSEQ786 = {{0, 0}};
NIM_CONST Program161804 TMP784 = {((TY161805*)&CNSTSEQ786),
NIM_FALSE}
;
NIM_CONST TY162124 TMP789 = {((NU8) 0),
((NU8) 1),
((NU8) 2)}
;
STRING_LITERAL(TMP794, "4", 1);
STRING_LITERAL(TMP795, "10", 2);
STRING_LITERAL(TMP796, "8", 1);
NIM_CONST struct {
  TGenericSeq Sup;
  NimStringDesc* data[78];
} CNSTSEQ798 = {{78, 78}, {((NimStringDesc*) &TMP758),
((NimStringDesc*) &TMP794),
((NimStringDesc*) &TMP758),
((NimStringDesc*) &TMP794),
((NimStringDesc*) &TMP758),
((NimStringDesc*) &TMP795),
((NimStringDesc*) &TMP759),
((NimStringDesc*) &TMP794),
((NimStringDesc*) &TMP759),
((NimStringDesc*) &TMP794),
((NimStringDesc*) &TMP758),
((NimStringDesc*) &TMP794),
((NimStringDesc*) &TMP758),
((NimStringDesc*) &TMP794),
((NimStringDesc*) &TMP759),
((NimStringDesc*) &TMP796),
((NimStringDesc*) &TMP759),
((NimStringDesc*) &TMP795),
((NimStringDesc*) &TMP758),
((NimStringDesc*) &TMP794),
((NimStringDesc*) &TMP758),
((NimStringDesc*) &TMP794),
((NimStringDesc*) &TMP758),
((NimStringDesc*) &TMP795),
((NimStringDesc*) &TMP759),
((NimStringDesc*) &TMP794),
((NimStringDesc*) &TMP759),
((NimStringDesc*) &TMP794),
((NimStringDesc*) &TMP758),
((NimStringDesc*) &TMP795),
((NimStringDesc*) &TMP759),
((NimStringDesc*) &TMP795),
((NimStringDesc*) &TMP758),
((NimStringDesc*) &TMP794),
((NimStringDesc*) &TMP758),
((NimStringDesc*) &TMP794),
((NimStringDesc*) &TMP758),
((NimStringDesc*) &TMP795),
((NimStringDesc*) &TMP759),
((NimStringDesc*) &TMP794),
((NimStringDesc*) &TMP759),
((NimStringDesc*) &TMP794),
((NimStringDesc*) &TMP758),
((NimStringDesc*) &TMP795),
((NimStringDesc*) &TMP759),
((NimStringDesc*) &TMP795),
((NimStringDesc*) &TMP759),
((NimStringDesc*) &TMP794),
((NimStringDesc*) &TMP758),
((NimStringDesc*) &TMP794),
((NimStringDesc*) &TMP758),
((NimStringDesc*) &TMP794),
((NimStringDesc*) &TMP759),
((NimStringDesc*) &TMP796),
((NimStringDesc*) &TMP759),
((NimStringDesc*) &TMP795),
((NimStringDesc*) &TMP759),
((NimStringDesc*) &TMP794),
((NimStringDesc*) &TMP758),
((NimStringDesc*) &TMP795),
((NimStringDesc*) &TMP759),
((NimStringDesc*) &TMP795),
((NimStringDesc*) &TMP759),
((NimStringDesc*) &TMP794),
((NimStringDesc*) &TMP758),
((NimStringDesc*) &TMP795),
((NimStringDesc*) &TMP759),
((NimStringDesc*) &TMP795),
((NimStringDesc*) &TMP759),
((NimStringDesc*) &TMP794),
((NimStringDesc*) &TMP758),
((NimStringDesc*) &TMP794),
((NimStringDesc*) &TMP758),
((NimStringDesc*) &TMP794),
((NimStringDesc*) &TMP759),
((NimStringDesc*) &TMP796),
((NimStringDesc*) &TMP759),
((NimStringDesc*) &TMP795)}};
NIM_CONST struct {
  TGenericSeq Sup;
  Route160789 data[1];
} CNSTSEQ799 = {{1, 1}, {{((TY17205*)&CNSTSEQ798),
NIM_TRUE}
}};
NIM_CONST TY162087* TMP793 = ((TY162087*)&CNSTSEQ799);
NIM_CONST struct {
  TGenericSeq Sup;
  TY17205* data[0];
} CNSTSEQ802 = {{0, 0}};
NIM_CONST struct {
  TGenericSeq Sup;
  NimStringDesc* data[0];
} CNSTSEQ803 = {{0, 0}};
NIM_CONST Solvedprogram162457 TMP800 = {{((TY161805*)&CNSTSEQ802),
NIM_FALSE}
,
{((TY17205*)&CNSTSEQ803),
NIM_FALSE}
}
;
STRING_LITERAL(TMP804, " ", 1);
NIM_CONST TY157201 TMP803 = {((NimStringDesc*) &TMP804)}
;
STRING_LITERAL(TMP807, "A", 1);
STRING_LITERAL(TMP809, "B", 1);
STRING_LITERAL(TMP811, "C", 1);
STRING_LITERAL(TMP814, "HELP HELP", 9);
NIM_CONST TY157201 TMP813 = {((NimStringDesc*) &TMP814)}
;
STRING_LITERAL(TMP816, "len(a) == L string modified while iterating over it", 51);
STRING_LITERAL(TMP818, ",", 1);
STRING_LITERAL(TMP822, "\"", 1);
STRING_LITERAL(TMP823, "\",", 2);
STRING_LITERAL(TMP830, "n", 1);
NIM_CONST struct {
  TGenericSeq Sup;
  NimStringDesc* data[1];
} CNSTSEQ832 = {{1, 1}, {((NimStringDesc*) &TMP830)}};
NIM_CONST TY17205* TMP829 = ((TY17205*)&CNSTSEQ832);
extern TFrame* frameptr_20842;
extern TNimType NTI112900; /* tuple[years: int, days: int] */
TNimType NTI160418; /* seq[Coord] */
TNimType NTI160520; /* Intersection */
extern TNimType NTI108; /* int */
TNimType NTI160401; /* Move */
TNimType NTI160531; /* seq[Intersection] */
extern TNimType NTI17205; /* seq[string] */
extern Gcheap51418 gch_51459;
TNimType NTI161805; /* seq[seq[string]] */
TNimType NTI161804; /* Program */
extern TNimType NTI138; /* bool */
TNimType NTI160789; /* Route */
TNimType NTI162087; /* seq[Route] */
Processobj155407* robot_162912;
Chart160047 chart_162919;
TNimType NTI160039; /* Square */
extern TNimType NTI147; /* char */
TNimType NTI160051; /* array[0..39, Square] */
TNimType NTI160047; /* Chart */
Solvedprogram162457 program_162959;
TNimType NTI162457; /* SolvedProgram */
NimStringDesc* step_163140;
TY17205* function_163186;
NimStringDesc* step_163196;
Message162664 message_163245;
TNimType NTI162664; /* Message */
NimStringDesc* call_163282;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_20842 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_20842).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_20842;
	frameptr_20842 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_23601();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_20842 = (*frameptr_20842).prev;
}

N_NIMCALL(Processobj155407*, spawnrobot_160004)(void) {
	Processobj155407* result;
	TY155637 LOC1;
	nimfr("spawnRobot", "program.nim")
{	result = 0;
	nimln(5, "program.nim");
	memset((void*)LOC1, 0, sizeof(LOC1));
	result = nospstartProcess(((NimStringDesc*) &TMP716), ((NimStringDesc*) &TMP717), LOC1, 0, NIM_NIL, 8);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, givecommand_160013)(Processobj155407* process, NI input) {
	Streamobj148227* inputstream;
	TY157201 LOC1;
	nimfr("giveCommand", "program.nim")
	nimln(8, "program.nim");
	inputstream = nospinputStream(process);
	nimln(9, "program.nim");
	memset((void*)LOC1, 0, sizeof(LOC1));
	LOC1[0] = nimIntToStr(input);
	writeline_148526(inputstream, LOC1, 1);
	nimln(10, "program.nim");
	flush_148275(inputstream);
	popFrame();
}

N_NIMCALL(NI, readouput_160026)(Processobj155407* process) {
	NI result;
	Streamobj148227* output;
	NimStringDesc* text;
	nimfr("readOuput", "program.nim")
	result = 0;
	nimln(13, "program.nim");
	output = nospoutputStream(process);
	nimln(14, "program.nim");
	text = readline_149277(output);
	nimln(15, "program.nim");
	result = nsuParseInt(text);
	popFrame();
	return result;
}

N_NIMCALL(Robot160065, turnleft_160072)(Robot160065* robot) {
	Robot160065 result;
	nimfr("turnLeft", "program.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln(37, "program.nim");
	{
		if (!((*robot).Field2 == ((NU8) 0))) goto LA3;
		nimln(38, "program.nim");
		result.Field0 = (*robot).Field0;
		result.Field1 = (*robot).Field1;
		result.Field2 = ((NU8) 3);
	}
	goto LA1;
	LA3: ;
	{
		nimln(40, "program.nim");
		{
			if (!((*robot).Field2 == ((NU8) 3))) goto LA8;
			nimln(41, "program.nim");
			result.Field0 = (*robot).Field0;
			result.Field1 = (*robot).Field1;
			result.Field2 = ((NU8) 2);
		}
		goto LA6;
		LA8: ;
		{
			nimln(43, "program.nim");
			{
				if (!((*robot).Field2 == ((NU8) 2))) goto LA13;
				nimln(44, "program.nim");
				result.Field0 = (*robot).Field0;
				result.Field1 = (*robot).Field1;
				result.Field2 = ((NU8) 1);
			}
			goto LA11;
			LA13: ;
			{
				nimln(46, "program.nim");
				result.Field0 = (*robot).Field0;
				result.Field1 = (*robot).Field1;
				result.Field2 = ((NU8) 0);
			}
			LA11: ;
		}
		LA6: ;
	}
	LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(Robot160065, turnright_160125)(Robot160065* robot) {
	Robot160065 result;
	nimfr("turnRight", "program.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln(49, "program.nim");
	{
		if (!((*robot).Field2 == ((NU8) 0))) goto LA3;
		nimln(50, "program.nim");
		result.Field0 = (*robot).Field0;
		result.Field1 = (*robot).Field1;
		result.Field2 = ((NU8) 1);
	}
	goto LA1;
	LA3: ;
	{
		nimln(52, "program.nim");
		{
			if (!((*robot).Field2 == ((NU8) 3))) goto LA8;
			nimln(53, "program.nim");
			result.Field0 = (*robot).Field0;
			result.Field1 = (*robot).Field1;
			result.Field2 = ((NU8) 0);
		}
		goto LA6;
		LA8: ;
		{
			nimln(55, "program.nim");
			{
				if (!((*robot).Field2 == ((NU8) 2))) goto LA13;
				nimln(56, "program.nim");
				result.Field0 = (*robot).Field0;
				result.Field1 = (*robot).Field1;
				result.Field2 = ((NU8) 3);
			}
			goto LA11;
			LA13: ;
			{
				nimln(58, "program.nim");
				result.Field0 = (*robot).Field0;
				result.Field1 = (*robot).Field1;
				result.Field2 = ((NU8) 2);
			}
			LA11: ;
		}
		LA6: ;
	}
	LA1: ;
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

N_NIMCALL(Robot160065, move_160178)(Robot160065* robot, NI amount) {
	Robot160065 result;
	nimfr("move", "program.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln(61, "program.nim");
	{
		NI TMP718;
		if (!((*robot).Field2 == ((NU8) 0))) goto LA3;
		nimln(62, "program.nim");
		result.Field0 = (*robot).Field0;
		TMP718 = subInt((*robot).Field1, amount);
		result.Field1 = (NI)(TMP718);
		result.Field2 = (*robot).Field2;
	}
	goto LA1;
	LA3: ;
	{
		nimln(64, "program.nim");
		{
			NI TMP719;
			if (!((*robot).Field2 == ((NU8) 3))) goto LA8;
			nimln(65, "program.nim");
			TMP719 = subInt((*robot).Field0, amount);
			result.Field0 = (NI)(TMP719);
			result.Field1 = (*robot).Field1;
			result.Field2 = (*robot).Field2;
		}
		goto LA6;
		LA8: ;
		{
			nimln(67, "program.nim");
			{
				NI TMP720;
				if (!((*robot).Field2 == ((NU8) 2))) goto LA13;
				nimln(68, "program.nim");
				result.Field0 = (*robot).Field0;
				TMP720 = addInt((*robot).Field1, amount);
				result.Field1 = (NI)(TMP720);
				result.Field2 = (*robot).Field2;
			}
			goto LA11;
			LA13: ;
			{
				NI TMP721;
				nimln(70, "program.nim");
				TMP721 = addInt((*robot).Field0, amount);
				result.Field0 = (NI)(TMP721);
				result.Field1 = (*robot).Field1;
				result.Field2 = (*robot).Field2;
			}
			LA11: ;
		}
		LA6: ;
	}
	LA1: ;
	popFrame();
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (a <= i);
		if (!(LOC3)) goto LA4;
		LOC3 = (i <= b);
		LA4: ;
		if (!LOC3) goto LA5;
		result = i;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(void, readchart_160232)(Processobj155407* process, Chart160047* Result) {
	NI i;
	NI j;
	Chart160047 chart;
	NIM_CHAR previousoutput;
	nimfr("readChart", "program.nim")
	nimln(74, "program.nim");
	i = ((NI) 0);
	nimln(75, "program.nim");
	j = ((NI) 0);
	memset((void*)chart, 0, sizeof(chart));
	nimln(77, "program.nim");
	previousoutput = 32;
	{
		nimln(78, "program.nim");
		while (1) {
			NIM_CHAR output;
			NI LOC3;
			nimln(79, "program.nim");
			LOC3 = 0;
			LOC3 = readouput_160026(process);
			output = ((NIM_CHAR)chckRange(LOC3, 0, 255));
			nimln(80, "program.nim");
			{
				NI TMP722;
				if (!((NU8)(output) == (NU8)(10))) goto LA6;
				nimln(81, "program.nim");
				{
					if (!((NU8)(previousoutput) == (NU8)(output))) goto LA10;
					nimln(82, "program.nim");
					goto LA1;
				}
				LA10: ;
				nimln(83, "program.nim");
				write_16883(stdout, j);
				nimln(84, "program.nim");
				TMP722 = addInt(j, ((NI) 1));
				j = (NI)(TMP722);
				nimln(85, "program.nim");
				i = ((NI) 0);
			}
			goto LA4;
			LA6: ;
			{
				Square160039 square;
				NI TMP723;
				memset((void*)(&square), 0, sizeof(square));
				nimln(88, "program.nim");
				square.Field0 = i;
				square.Field1 = j;
				square.Field2 = output;
				nimln(89, "program.nim");
				if ((NU)(j) > (NU)(30)) raiseIndexError();
				if ((NU)(i) > (NU)(39)) raiseIndexError();
				chart[(j)- 0][(i)- 0] = square;
				nimln(90, "program.nim");
				TMP723 = addInt(i, ((NI) 1));
				i = (NI)(TMP723);
			}
			LA4: ;
			nimln(91, "program.nim");
			write_16903(stdout, output);
			nimln(92, "program.nim");
			previousoutput = output;
		}
	} LA1: ;
	nimln(93, "program.nim");
	memcpy((void*)(*Result), (NIM_CONST void*)chart, sizeof(Chart160047));
	popFrame();
}

N_NIMCALL(NIM_BOOL, iscrosssection_160265)(Chart160047 chart, Square160039* square) {
	NIM_BOOL result;
	nimfr("isCrossSection", "program.nim")
{	result = 0;
	{
		NI y_160280;
		NI HEX3Atmp_160293;
		NI HEX3Atmp_160294;
		NI TMP724;
		NI TMP725;
		NI res_160297;
		y_160280 = 0;
		HEX3Atmp_160293 = 0;
		HEX3Atmp_160294 = 0;
		nimln(96, "program.nim");
		TMP724 = subInt((*square).Field1, ((NI) 1));
		HEX3Atmp_160293 = (NI)(TMP724);
		TMP725 = addInt((*square).Field1, ((NI) 1));
		HEX3Atmp_160294 = (NI)(TMP725);
		nimln(1874, "system.nim");
		res_160297 = HEX3Atmp_160293;
		{
			nimln(1875, "system.nim");
			while (1) {
				NI TMP726;
				if (!(res_160297 <= HEX3Atmp_160294)) goto LA3;
				nimln(1876, "system.nim");
				y_160280 = res_160297;
				nimln(97, "program.nim");
				{
					nimln(349, "system.nim");
					if ((NU)(y_160280) > (NU)(30)) raiseIndexError();
					if ((NU)((*square).Field0) > (NU)(39)) raiseIndexError();
					if (!!(((NU8)(chart[(y_160280)- 0][((*square).Field0)- 0].Field2) == (NU8)(35)))) goto LA6;
					nimln(98, "program.nim");
					result = NIM_FALSE;
					nimln(99, "program.nim");
					goto BeforeRet;
				}
				LA6: ;
				nimln(1895, "system.nim");
				TMP726 = addInt(res_160297, ((NI) 1));
				res_160297 = (NI)(TMP726);
			} LA3: ;
		}
	}
	{
		NI x_160291;
		NI HEX3Atmp_160302;
		NI HEX3Atmp_160303;
		NI TMP727;
		NI TMP728;
		NI res_160306;
		x_160291 = 0;
		HEX3Atmp_160302 = 0;
		HEX3Atmp_160303 = 0;
		nimln(100, "program.nim");
		TMP727 = subInt((*square).Field0, ((NI) 1));
		HEX3Atmp_160302 = (NI)(TMP727);
		TMP728 = addInt((*square).Field0, ((NI) 1));
		HEX3Atmp_160303 = (NI)(TMP728);
		nimln(1874, "system.nim");
		res_160306 = HEX3Atmp_160302;
		{
			nimln(1875, "system.nim");
			while (1) {
				NI TMP729;
				if (!(res_160306 <= HEX3Atmp_160303)) goto LA10;
				nimln(1876, "system.nim");
				x_160291 = res_160306;
				nimln(101, "program.nim");
				{
					nimln(349, "system.nim");
					if ((NU)((*square).Field1) > (NU)(30)) raiseIndexError();
					if ((NU)(x_160291) > (NU)(39)) raiseIndexError();
					if (!!(((NU8)(chart[((*square).Field1)- 0][(x_160291)- 0].Field2) == (NU8)(35)))) goto LA13;
					nimln(102, "program.nim");
					result = NIM_FALSE;
					nimln(103, "program.nim");
					goto BeforeRet;
				}
				LA13: ;
				nimln(1895, "system.nim");
				TMP729 = addInt(res_160306, ((NI) 1));
				res_160306 = (NI)(TMP729);
			} LA10: ;
		}
	}
	nimln(104, "program.nim");
	result = NIM_TRUE;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, determinealignmentparamters_160334)(Chart160047 chart) {
	NI result;
	NI sum;
	nimfr("determineAlignmentParamters", "program.nim")
	result = 0;
	nimln(107, "program.nim");
	sum = ((NI) 0);
	{
		NI y_160349;
		NI res_160372;
		y_160349 = 0;
		nimln(1874, "system.nim");
		res_160372 = ((NI) 1);
		{
			nimln(1875, "system.nim");
			while (1) {
				NI TMP733;
				if (!(res_160372 <= ((NI) 29))) goto LA3;
				nimln(1876, "system.nim");
				y_160349 = res_160372;
				{
					NI x_160361;
					NI res_160366;
					x_160361 = 0;
					nimln(1874, "system.nim");
					res_160366 = ((NI) 1);
					{
						nimln(1875, "system.nim");
						while (1) {
							NI TMP732;
							if (!(res_160366 <= ((NI) 38))) goto LA6;
							nimln(1876, "system.nim");
							x_160361 = res_160366;
							nimln(110, "program.nim");
							{
								NIM_BOOL LOC9;
								NI TMP730;
								NI TMP731;
								if ((NU)(y_160349) > (NU)(30)) raiseIndexError();
								if ((NU)(x_160361) > (NU)(39)) raiseIndexError();
								LOC9 = 0;
								LOC9 = iscrosssection_160265(chart, (&chart[(y_160349)- 0][(x_160361)- 0]));
								if (!LOC9) goto LA10;
								nimln(111, "program.nim");
								TMP730 = mulInt(x_160361, y_160349);
								TMP731 = addInt(sum, (NI)(TMP730));
								sum = (NI)(TMP731);
							}
							LA10: ;
							nimln(1895, "system.nim");
							TMP732 = addInt(res_160366, ((NI) 1));
							res_160366 = (NI)(TMP732);
						} LA6: ;
					}
				}
				TMP733 = addInt(res_160372, ((NI) 1));
				res_160372 = (NI)(TMP733);
			} LA3: ;
		}
	}
	nimln(112, "program.nim");
	result = sum;
	popFrame();
	return result;
}
N_NIMCALL(void, TMP735)(void* p, NI op) {
	TY160418* a;
	NI LOC1;
	a = (TY160418*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	}
}

N_NIMCALL(TY160418*, findintersections_160415)(Chart160047 chart) {
	TY160418* result;
	nimfr("findIntersections", "program.nim")
	result = 0;
	nimln(124, "program.nim");
	result = (TY160418*) newSeq((&NTI160418), 0);
	{
		NI y_160446;
		NI res_160481;
		y_160446 = 0;
		nimln(1874, "system.nim");
		res_160481 = ((NI) 1);
		{
			nimln(1875, "system.nim");
			while (1) {
				NI TMP737;
				if (!(res_160481 <= ((NI) 29))) goto LA3;
				nimln(1876, "system.nim");
				y_160446 = res_160481;
				{
					NI x_160457;
					NI res_160475;
					x_160457 = 0;
					nimln(1874, "system.nim");
					res_160475 = ((NI) 1);
					{
						nimln(1875, "system.nim");
						while (1) {
							NI TMP736;
							if (!(res_160475 <= ((NI) 38))) goto LA6;
							nimln(1876, "system.nim");
							x_160457 = res_160475;
							nimln(127, "program.nim");
							{
								NIM_BOOL LOC9;
								TY112900 LOC12;
								if ((NU)(y_160446) > (NU)(30)) raiseIndexError();
								if ((NU)(x_160457) > (NU)(39)) raiseIndexError();
								LOC9 = 0;
								LOC9 = iscrosssection_160265(chart, (&chart[(y_160446)- 0][(x_160457)- 0]));
								if (!LOC9) goto LA10;
								nimln(128, "program.nim");
								LOC12.Field0 = x_160457;
								LOC12.Field1 = y_160446;
								result = (TY160418*) incrSeqV2(&(result)->Sup, sizeof(TY112900));
								result->data[result->Sup.len] = LOC12;
								++result->Sup.len;
							}
							LA10: ;
							nimln(1895, "system.nim");
							TMP736 = addInt(res_160475, ((NI) 1));
							res_160475 = (NI)(TMP736);
						} LA6: ;
					}
				}
				TMP737 = addInt(res_160481, ((NI) 1));
				res_160481 = (NI)(TMP737);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, isoutofbounds_160509)(Robot160065* robot) {
	NIM_BOOL result;
	NIM_BOOL LOC1;
	NIM_BOOL LOC2;
	NIM_BOOL LOC3;
	nimfr("isOutOfBounds", "program.nim")
	result = 0;
	nimln(131, "program.nim");
	LOC1 = 0;
	LOC2 = 0;
	LOC3 = 0;
	LOC3 = ((*robot).Field0 < ((NI) 0));
	if (LOC3) goto LA4;
	nimln(357, "system.nim");
	LOC3 = (((NI) 39) < (*robot).Field0);
	LA4: ;
	LOC2 = LOC3;
	if (LOC2) goto LA5;
	nimln(131, "program.nim");
	LOC2 = ((*robot).Field1 < ((NI) 0));
	LA5: ;
	LOC1 = LOC2;
	if (LOC1) goto LA6;
	nimln(357, "system.nim");
	LOC1 = (((NI) 30) < (*robot).Field1);
	LA6: ;
	result = LOC1;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, shouldturnleft_160527)(Robot160065* robot, Chart160047 chart, TY160531* intersections) {
	NIM_BOOL result;
	Robot160065 proxy;
	Robot160065 LOC14;
	nimfr("shouldTurnLeft", "program.nim")
{	result = 0;
	{
		Intersection160520 intersection_160611;
		NI i_160625;
		NI L_160627;
		memset((void*)(&intersection_160611), 0, sizeof(intersection_160611));
		nimln(3365, "system.nim");
		i_160625 = ((NI) 0);
		nimln(3366, "system.nim");
		L_160627 = (intersections ? intersections->Sup.len : 0);
		{
			nimln(3367, "system.nim");
			while (1) {
				NI TMP738;
				if (!(i_160625 < L_160627)) goto LA3;
				nimln(3368, "system.nim");
				if ((NU)(i_160625) >= (NU)(intersections->Sup.len)) raiseIndexError();
				intersection_160611 = intersections->data[i_160625];
				nimln(141, "program.nim");
				{
					NIM_BOOL LOC6;
					LOC6 = 0;
					LOC6 = (intersection_160611.Field0 == (*robot).Field0);
					if (!(LOC6)) goto LA7;
					LOC6 = (intersection_160611.Field1 == (*robot).Field1);
					LA7: ;
					if (!LOC6) goto LA8;
					nimln(142, "program.nim");
					result = (intersection_160611.Field2 == ((NU8) 1));
					goto BeforeRet;
				}
				LA8: ;
				nimln(3369, "system.nim");
				TMP738 = addInt(i_160625, ((NI) 1));
				i_160625 = (NI)(TMP738);
				nimln(3370, "system.nim");
				{
					if (!!(((intersections ? intersections->Sup.len : 0) == L_160627))) goto LA12;
					failedassertimpl_91603(((NimStringDesc*) &TMP739));
				}
				LA12: ;
			} LA3: ;
		}
	}
	nimln(143, "program.nim");
	LOC14 = turnleft_160072(robot);
	proxy = move_160178((&LOC14), ((NI) 1));
	nimln(144, "program.nim");
	{
		NIM_BOOL LOC17;
		LOC17 = 0;
		LOC17 = isoutofbounds_160509((&proxy));
		if (!LOC17) goto LA18;
		nimln(145, "program.nim");
		result = NIM_FALSE;
		nimln(146, "program.nim");
		goto BeforeRet;
	}
	LA18: ;
	nimln(147, "program.nim");
	if ((NU)(proxy.Field1) > (NU)(30)) raiseIndexError();
	if ((NU)(proxy.Field0) > (NU)(39)) raiseIndexError();
	result = ((NU8)(chart[(proxy.Field1)- 0][(proxy.Field0)- 0].Field2) == (NU8)(35));
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, shouldturnright_160643)(Robot160065* robot, Chart160047 chart, TY160531* intersections) {
	NIM_BOOL result;
	Robot160065 proxy;
	Robot160065 LOC14;
	nimfr("shouldTurnRight", "program.nim")
{	result = 0;
	{
		Intersection160520 intersection_160659;
		NI i_160673;
		NI L_160675;
		memset((void*)(&intersection_160659), 0, sizeof(intersection_160659));
		nimln(3365, "system.nim");
		i_160673 = ((NI) 0);
		nimln(3366, "system.nim");
		L_160675 = (intersections ? intersections->Sup.len : 0);
		{
			nimln(3367, "system.nim");
			while (1) {
				NI TMP740;
				if (!(i_160673 < L_160675)) goto LA3;
				nimln(3368, "system.nim");
				if ((NU)(i_160673) >= (NU)(intersections->Sup.len)) raiseIndexError();
				intersection_160659 = intersections->data[i_160673];
				nimln(151, "program.nim");
				{
					NIM_BOOL LOC6;
					LOC6 = 0;
					LOC6 = (intersection_160659.Field0 == (*robot).Field0);
					if (!(LOC6)) goto LA7;
					LOC6 = (intersection_160659.Field1 == (*robot).Field1);
					LA7: ;
					if (!LOC6) goto LA8;
					nimln(152, "program.nim");
					result = (intersection_160659.Field2 == ((NU8) 2));
					goto BeforeRet;
				}
				LA8: ;
				nimln(3369, "system.nim");
				TMP740 = addInt(i_160673, ((NI) 1));
				i_160673 = (NI)(TMP740);
				nimln(3370, "system.nim");
				{
					if (!!(((intersections ? intersections->Sup.len : 0) == L_160675))) goto LA12;
					failedassertimpl_91603(((NimStringDesc*) &TMP739));
				}
				LA12: ;
			} LA3: ;
		}
	}
	nimln(153, "program.nim");
	LOC14 = turnright_160125(robot);
	proxy = move_160178((&LOC14), ((NI) 1));
	nimln(154, "program.nim");
	{
		NIM_BOOL LOC17;
		LOC17 = 0;
		LOC17 = isoutofbounds_160509((&proxy));
		if (!LOC17) goto LA18;
		nimln(155, "program.nim");
		result = NIM_FALSE;
	}
	goto LA15;
	LA18: ;
	{
		nimln(157, "program.nim");
		if ((NU)(proxy.Field1) > (NU)(30)) raiseIndexError();
		if ((NU)(proxy.Field0) > (NU)(39)) raiseIndexError();
		result = ((NU8)(chart[(proxy.Field1)- 0][(proxy.Field0)- 0].Field2) == (NU8)(35));
	}
	LA15: ;
	}BeforeRet: ;
	popFrame();
	return result;
}
N_NIMCALL(void, TMP745)(void* p, NI op) {
	TY160531* a;
	NI LOC1;
	a = (TY160531*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	}
}

N_NIMCALL(void, determinemovement_160699)(Robot160065* robot, Chart160047 chart, TY160531* intersections, Forward160692* Result) {
	TY160531* passedintersections;
	Robot160065 proxy;
	NI steps;
	nimfr("determineMovement", "program.nim")
	passedintersections = 0;
	nimln(166, "program.nim");
	passedintersections = (TY160531*) newSeq((&NTI160531), 0);
	nimln(167, "program.nim");
	proxy = (*robot);
	nimln(168, "program.nim");
	steps = ((NI) -1);
	{
		nimln(169, "program.nim");
		while (1) {
			NIM_BOOL LOC3;
			NI TMP746;
			NIM_BOOL stoppedatintersection;
			LOC3 = 0;
			if ((NU)(proxy.Field1) > (NU)(30)) raiseIndexError();
			if ((NU)(proxy.Field0) > (NU)(39)) raiseIndexError();
			LOC3 = ((NU8)(chart[(proxy.Field1)- 0][(proxy.Field0)- 0].Field2) == (NU8)(35));
			if (LOC3) goto LA4;
			if ((NU)(proxy.Field1) > (NU)(30)) raiseIndexError();
			if ((NU)(proxy.Field0) > (NU)(39)) raiseIndexError();
			LOC3 = ((NU8)(chart[(proxy.Field1)- 0][(proxy.Field0)- 0].Field2) == (NU8)(94));
			LA4: ;
			if (!LOC3) goto LA2;
			nimln(170, "program.nim");
			TMP746 = addInt(steps, ((NI) 1));
			steps = (NI)(TMP746);
			nimln(171, "program.nim");
			proxy = move_160178((&proxy), ((NI) 1));
			nimln(172, "program.nim");
			{
				NIM_BOOL LOC7;
				LOC7 = 0;
				LOC7 = isoutofbounds_160509((&proxy));
				if (!LOC7) goto LA8;
				nimln(173, "program.nim");
				goto LA1;
			}
			LA8: ;
			nimln(174, "program.nim");
			stoppedatintersection = NIM_FALSE;
			{
				Intersection160520 intersection_160736;
				NI i_160764;
				NI L_160766;
				memset((void*)(&intersection_160736), 0, sizeof(intersection_160736));
				nimln(3365, "system.nim");
				i_160764 = ((NI) 0);
				nimln(3366, "system.nim");
				L_160766 = (intersections ? intersections->Sup.len : 0);
				{
					nimln(3367, "system.nim");
					while (1) {
						NI TMP747;
						if (!(i_160764 < L_160766)) goto LA12;
						nimln(3368, "system.nim");
						if ((NU)(i_160764) >= (NU)(intersections->Sup.len)) raiseIndexError();
						intersection_160736 = intersections->data[i_160764];
						nimln(176, "program.nim");
						{
							NIM_BOOL LOC15;
							LOC15 = 0;
							LOC15 = (intersection_160736.Field0 == proxy.Field0);
							if (!(LOC15)) goto LA16;
							LOC15 = (intersection_160736.Field1 == proxy.Field1);
							LA16: ;
							if (!LOC15) goto LA17;
							nimln(177, "program.nim");
							passedintersections = (TY160531*) incrSeqV2(&(passedintersections)->Sup, sizeof(Intersection160520));
							passedintersections->data[passedintersections->Sup.len] = intersection_160736;
							++passedintersections->Sup.len;
							nimln(178, "program.nim");
							{
								if (!!((intersection_160736.Field2 == ((NU8) 0)))) goto LA21;
								nimln(179, "program.nim");
								stoppedatintersection = NIM_TRUE;
							}
							LA21: ;
						}
						LA17: ;
						nimln(3369, "system.nim");
						TMP747 = addInt(i_160764, ((NI) 1));
						i_160764 = (NI)(TMP747);
						nimln(3370, "system.nim");
						{
							if (!!(((intersections ? intersections->Sup.len : 0) == L_160766))) goto LA25;
							failedassertimpl_91603(((NimStringDesc*) &TMP739));
						}
						LA25: ;
					} LA12: ;
				}
			}
			nimln(180, "program.nim");
			{
				NI TMP748;
				if (!stoppedatintersection) goto LA29;
				nimln(181, "program.nim");
				TMP748 = addInt(steps, ((NI) 1));
				steps = (NI)(TMP748);
				nimln(182, "program.nim");
				goto LA1;
			}
			LA29: ;
		} LA2: ;
	} LA1: ;
	nimln(183, "program.nim");
	(*Result).Field0 = steps;
	genericSeqAssign((&(*Result).Field1), passedintersections, (&NTI160531));
	popFrame();
}

N_NIMCALL(TY160531*, tointersections_160796)(TY160418* coords) {
	TY160531* result;
	nimfr("toIntersections", "program.nim")
	result = 0;
	nimln(191, "program.nim");
	result = (TY160531*) newSeq((&NTI160531), 0);
	{
		TY112900 coord_161011;
		NI i_161029;
		NI L_161031;
		memset((void*)(&coord_161011), 0, sizeof(coord_161011));
		nimln(3365, "system.nim");
		i_161029 = ((NI) 0);
		nimln(3366, "system.nim");
		L_161031 = (coords ? coords->Sup.len : 0);
		{
			nimln(3367, "system.nim");
			while (1) {
				Intersection160520 LOC4;
				NI TMP749;
				if (!(i_161029 < L_161031)) goto LA3;
				nimln(3368, "system.nim");
				if ((NU)(i_161029) >= (NU)(coords->Sup.len)) raiseIndexError();
				coord_161011 = coords->data[i_161029];
				nimln(193, "program.nim");
				LOC4.Field0 = coord_161011.Field0;
				LOC4.Field1 = coord_161011.Field1;
				LOC4.Field2 = ((NU8) 0);
				result = (TY160531*) incrSeqV2(&(result)->Sup, sizeof(Intersection160520));
				result->data[result->Sup.len] = LOC4;
				++result->Sup.len;
				nimln(3369, "system.nim");
				TMP749 = addInt(i_161029, ((NI) 1));
				i_161029 = (NI)(TMP749);
				nimln(3370, "system.nim");
				{
					if (!!(((coords ? coords->Sup.len : 0) == L_161031))) goto LA7;
					failedassertimpl_91603(((NimStringDesc*) &TMP739));
				}
				LA7: ;
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, isstuckinaloopat_161047)(TY160531* intersections, Intersection160520* place) {
	NIM_BOOL result;
	NI count;
	nimfr("isStuckInALoopAt", "program.nim")
	result = 0;
	nimln(196, "program.nim");
	count = ((NI) 0);
	{
		Intersection160520 i_161063;
		NI i_161067;
		NI L_161069;
		memset((void*)(&i_161063), 0, sizeof(i_161063));
		nimln(3365, "system.nim");
		i_161067 = ((NI) 0);
		nimln(3366, "system.nim");
		L_161069 = (intersections ? intersections->Sup.len : 0);
		{
			nimln(3367, "system.nim");
			while (1) {
				NI TMP751;
				if (!(i_161067 < L_161069)) goto LA3;
				nimln(3368, "system.nim");
				if ((NU)(i_161067) >= (NU)(intersections->Sup.len)) raiseIndexError();
				i_161063 = intersections->data[i_161067];
				nimln(198, "program.nim");
				{
					NIM_BOOL LOC6;
					NI TMP750;
					LOC6 = 0;
					LOC6 = (i_161063.Field0 == (*place).Field0);
					if (!(LOC6)) goto LA7;
					LOC6 = (i_161063.Field1 == (*place).Field1);
					LA7: ;
					if (!LOC6) goto LA8;
					nimln(199, "program.nim");
					TMP750 = addInt(count, ((NI) 1));
					count = (NI)(TMP750);
				}
				LA8: ;
				nimln(3369, "system.nim");
				TMP751 = addInt(i_161067, ((NI) 1));
				i_161067 = (NI)(TMP751);
				nimln(3370, "system.nim");
				{
					if (!!(((intersections ? intersections->Sup.len : 0) == L_161069))) goto LA12;
					failedassertimpl_91603(((NimStringDesc*) &TMP739));
				}
				LA12: ;
			} LA3: ;
		}
	}
	nimln(200, "program.nim");
	nimln(357, "system.nim");
	result = (((NI) 2) < count);
	popFrame();
	return result;
}

N_NIMCALL(void, printintersection_161085)(Intersection160520* intersection) {
	nimfr("printIntersection", "program.nim")
	nimln(204, "program.nim");
	switch ((*intersection).Field2) {
	case ((NU8) 0):
	{
		nimln(206, "program.nim");
		write_16903(stdout, 83);
	}
	break;
	case ((NU8) 1):
	{
		nimln(208, "program.nim");
		write_16903(stdout, 76);
	}
	break;
	case ((NU8) 2):
	{
		nimln(210, "program.nim");
		write_16903(stdout, 82);
	}
	break;
	default:
	{
		nimln(212, "program.nim");
		write_16903(stdout, 63);
	}
	break;
	}
	popFrame();
}

static N_INLINE(void, writeline_161120)(FILE* f, NimStringDesc** x, NI xLen0) {
	nimfr("writeLine", "sysio.nim")
	{
		NimStringDesc* i_161136;
		NI i_161144;
		i_161136 = 0;
		nimln(1965, "system.nim");
		i_161144 = ((NI) 0);
		{
			nimln(1966, "system.nim");
			while (1) {
				if (!(i_161144 < xLen0)) goto LA3;
				nimln(1967, "system.nim");
				i_161136 = x[i_161144];
				nimln(218, "sysio.nim");
				write_16895(f, i_161136);
				nimln(1968, "system.nim");
				i_161144 += ((NI) 1);
			} LA3: ;
		}
	}
	nimln(219, "sysio.nim");
	write_16895(f, ((NimStringDesc*) &TMP752));
	popFrame();
}

N_NIMCALL(void, printintersections_161102)(TY160531* intersections) {
	nimfr("printIntersections", "program.nim")
	{
		Intersection160520 intersection_161115;
		NI i_161160;
		NI L_161162;
		memset((void*)(&intersection_161115), 0, sizeof(intersection_161115));
		nimln(3365, "system.nim");
		i_161160 = ((NI) 0);
		nimln(3366, "system.nim");
		L_161162 = (intersections ? intersections->Sup.len : 0);
		{
			nimln(3367, "system.nim");
			while (1) {
				NI TMP753;
				if (!(i_161160 < L_161162)) goto LA3;
				nimln(3368, "system.nim");
				if ((NU)(i_161160) >= (NU)(intersections->Sup.len)) raiseIndexError();
				intersection_161115 = intersections->data[i_161160];
				nimln(216, "program.nim");
				printintersection_161085((&intersection_161115));
				nimln(3369, "system.nim");
				TMP753 = addInt(i_161160, ((NI) 1));
				i_161160 = (NI)(TMP753);
				nimln(3370, "system.nim");
				{
					if (!!(((intersections ? intersections->Sup.len : 0) == L_161162))) goto LA6;
					failedassertimpl_91603(((NimStringDesc*) &TMP739));
				}
				LA6: ;
			} LA3: ;
		}
	}
	nimln(217, "program.nim");
	writeline_161120(stdout, TMP754, 1);
	popFrame();
}

static N_INLINE(Cell49347*, usrtocell_53046)(void* usr) {
	Cell49347* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(131, "gc.nim");
	result = ((Cell49347*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell49347))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_54604)(Cell49347* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(212, "gc.nim");
	addzct_53017((&gch_51459.zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	Cell49347* c;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(246, "gc.nim");
	c = usrtocell_53046(p);
	nimln(248, "gc.nim");
	{
		nimln(180, "gc.nim");
		(*c).refcount -= ((NI) 8);
		nimln(181, "gc.nim");
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3;
		nimln(249, "gc.nim");
		rtladdzct_54604(c);
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(void, findroute_161178)(Chart160047 chart, TY160531* intersections, Route160789* Result) {
	TY112900 endpoint;
	TY17205* route;
	TY160531* passedintersections;
	Robot160065 robot;
	NIM_BOOL done;
	NIM_BOOL valid;
	NIM_BOOL LOC31;
	nimfr("findRoute", "program.nim")
	nimln(220, "program.nim");
	endpoint = TMP756;
	route = 0;
	nimln(222, "program.nim");
	route = (TY17205*) newSeq((&NTI17205), 0);
	passedintersections = 0;
	nimln(224, "program.nim");
	passedintersections = (TY160531*) newSeq((&NTI160531), 0);
	memset((void*)(&robot), 0, sizeof(robot));
	nimln(226, "program.nim");
	robot = TMP757;
	nimln(227, "program.nim");
	done = NIM_FALSE;
	{
		nimln(228, "program.nim");
		while (1) {
			Forward160692 movement;
			NimStringDesc* LOC29;
			NimStringDesc* LOC30;
			if (!(done == NIM_FALSE)) goto LA2;
			nimln(229, "program.nim");
			{
				NIM_BOOL LOC5;
				NimStringDesc* LOC8;
				LOC5 = 0;
				LOC5 = shouldturnleft_160527((&robot), chart, intersections);
				if (!LOC5) goto LA6;
				nimln(230, "program.nim");
				route = (TY17205*) incrSeqV2(&(route)->Sup, sizeof(NimStringDesc*));
				LOC8 = 0;
				LOC8 = route->data[route->Sup.len]; route->data[route->Sup.len] = copyStringRC1(((NimStringDesc*) &TMP758));
				if (LOC8) nimGCunrefNoCycle(LOC8);
				++route->Sup.len;
				nimln(231, "program.nim");
				robot = turnleft_160072((&robot));
			}
			goto LA3;
			LA6: ;
			{
				nimln(233, "program.nim");
				{
					NIM_BOOL LOC12;
					NimStringDesc* LOC15;
					LOC12 = 0;
					LOC12 = shouldturnright_160643((&robot), chart, intersections);
					if (!LOC12) goto LA13;
					nimln(234, "program.nim");
					route = (TY17205*) incrSeqV2(&(route)->Sup, sizeof(NimStringDesc*));
					LOC15 = 0;
					LOC15 = route->data[route->Sup.len]; route->data[route->Sup.len] = copyStringRC1(((NimStringDesc*) &TMP759));
					if (LOC15) nimGCunrefNoCycle(LOC15);
					++route->Sup.len;
					nimln(235, "program.nim");
					robot = turnright_160125((&robot));
				}
				goto LA10;
				LA13: ;
				{
					nimln(237, "program.nim");
					done = NIM_TRUE;
					nimln(238, "program.nim");
					goto LA1;
				}
				LA10: ;
			}
			LA3: ;
			memset((void*)(&movement), 0, sizeof(movement));
			nimln(239, "program.nim");
			chckNil((void*)(&movement));
			memset((void*)(&movement), 0, sizeof(movement));
			determinemovement_160699((&robot), chart, intersections, (&movement));
			{
				Intersection160520 intersection_161260;
				TY160531* HEX3Atmp_161291;
				NI i_161294;
				NI L_161296;
				memset((void*)(&intersection_161260), 0, sizeof(intersection_161260));
				HEX3Atmp_161291 = 0;
				nimln(240, "program.nim");
				HEX3Atmp_161291 = movement.Field1;
				nimln(3365, "system.nim");
				i_161294 = ((NI) 0);
				nimln(3366, "system.nim");
				L_161296 = (HEX3Atmp_161291 ? HEX3Atmp_161291->Sup.len : 0);
				{
					nimln(3367, "system.nim");
					while (1) {
						NI TMP760;
						if (!(i_161294 < L_161296)) goto LA19;
						nimln(3368, "system.nim");
						if ((NU)(i_161294) >= (NU)(HEX3Atmp_161291->Sup.len)) raiseIndexError();
						intersection_161260 = HEX3Atmp_161291->data[i_161294];
						nimln(241, "program.nim");
						passedintersections = (TY160531*) incrSeqV2(&(passedintersections)->Sup, sizeof(Intersection160520));
						passedintersections->data[passedintersections->Sup.len] = intersection_161260;
						++passedintersections->Sup.len;
						nimln(242, "program.nim");
						{
							NIM_BOOL LOC22;
							LOC22 = 0;
							LOC22 = isstuckinaloopat_161047(passedintersections, (&intersection_161260));
							if (!LOC22) goto LA23;
							nimln(243, "program.nim");
							done = NIM_TRUE;
						}
						LA23: ;
						nimln(3369, "system.nim");
						TMP760 = addInt(i_161294, ((NI) 1));
						i_161294 = (NI)(TMP760);
						nimln(3370, "system.nim");
						{
							if (!!(((HEX3Atmp_161291 ? HEX3Atmp_161291->Sup.len : 0) == L_161296))) goto LA27;
							failedassertimpl_91603(((NimStringDesc*) &TMP739));
						}
						LA27: ;
					} LA19: ;
				}
			}
			nimln(244, "program.nim");
			robot = move_160178((&robot), movement.Field0);
			nimln(245, "program.nim");
			LOC29 = 0;
			LOC29 = nsuIntToStr(movement.Field0, ((NI) 1));
			route = (TY17205*) incrSeqV2(&(route)->Sup, sizeof(NimStringDesc*));
			LOC30 = 0;
			LOC30 = route->data[route->Sup.len]; route->data[route->Sup.len] = copyStringRC1(LOC29);
			if (LOC30) nimGCunrefNoCycle(LOC30);
			++route->Sup.len;
		} LA2: ;
	} LA1: ;
	nimln(246, "program.nim");
	LOC31 = 0;
	LOC31 = (robot.Field0 == endpoint.Field0);
	if (!(LOC31)) goto LA32;
	LOC31 = (robot.Field1 == endpoint.Field1);
	LA32: ;
	valid = LOC31;
	nimln(247, "program.nim");
	genericSeqAssign((&(*Result).Field0), route, (&NTI17205));
	(*Result).Field1 = valid;
	popFrame();
}

N_NIMCALL(TY17205*, duplicate_161318)(TY17205* route) {
	TY17205* result;
	nimfr("duplicate", "program.nim")
	result = 0;
	nimln(250, "program.nim");
	result = (TY17205*) newSeq((&NTI17205), 0);
	{
		NimStringDesc* step_161411;
		NI i_161425;
		NI L_161427;
		step_161411 = 0;
		nimln(3365, "system.nim");
		i_161425 = ((NI) 0);
		nimln(3366, "system.nim");
		L_161427 = (route ? route->Sup.len : 0);
		{
			nimln(3367, "system.nim");
			while (1) {
				NimStringDesc* LOC4;
				NI TMP761;
				if (!(i_161425 < L_161427)) goto LA3;
				nimln(3368, "system.nim");
				if ((NU)(i_161425) >= (NU)(route->Sup.len)) raiseIndexError();
				step_161411 = route->data[i_161425];
				nimln(252, "program.nim");
				result = (TY17205*) incrSeqV2(&(result)->Sup, sizeof(NimStringDesc*));
				LOC4 = 0;
				LOC4 = result->data[result->Sup.len]; result->data[result->Sup.len] = copyStringRC1(step_161411);
				if (LOC4) nimGCunrefNoCycle(LOC4);
				++result->Sup.len;
				nimln(3369, "system.nim");
				TMP761 = addInt(i_161425, ((NI) 1));
				i_161425 = (NI)(TMP761);
				nimln(3370, "system.nim");
				{
					if (!!(((route ? route->Sup.len : 0) == L_161427))) goto LA7;
					failedassertimpl_91603(((NimStringDesc*) &TMP739));
				}
				LA7: ;
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL LOC11;
	int LOC13;
{	result = 0;
	{
		if (!(a == b)) goto LA3;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == NIM_NIL);
		if (LOC7) goto LA8;
		LOC7 = (b == NIM_NIL);
		LA8: ;
		if (!LOC7) goto LA9;
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA9: ;
	LOC11 = 0;
	LOC11 = ((*a).Sup.len == (*b).Sup.len);
	if (!(LOC11)) goto LA12;
	LOC13 = 0;
	LOC13 = memcmp(((NCSTRING) ((*a).data)), ((NCSTRING) ((*b).data)), (*a).Sup.len);
	LOC11 = (LOC13 == ((NI32) 0));
	LA12: ;
	result = LOC11;
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(NIM_BOOL, containtsat_161443)(TY17205* route, TY17205* command, NI index) {
	NIM_BOOL result;
	NI i;
	nimfr("containtsAt", "program.nim")
{	result = 0;
	nimln(255, "program.nim");
	{
		NI TMP762;
		nimln(357, "system.nim");
		nimln(255, "program.nim");
		TMP762 = addInt(index, (command ? command->Sup.len : 0));
		if (!((route ? route->Sup.len : 0) < (NI)(TMP762))) goto LA3;
		nimln(256, "program.nim");
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA3: ;
	nimln(257, "program.nim");
	i = index;
	{
		NimStringDesc* step_161477;
		NI i_161481;
		NI L_161483;
		step_161477 = 0;
		nimln(3365, "system.nim");
		i_161481 = ((NI) 0);
		nimln(3366, "system.nim");
		L_161483 = (command ? command->Sup.len : 0);
		{
			nimln(3367, "system.nim");
			while (1) {
				NI TMP763;
				NI TMP764;
				if (!(i_161481 < L_161483)) goto LA7;
				nimln(3368, "system.nim");
				if ((NU)(i_161481) >= (NU)(command->Sup.len)) raiseIndexError();
				step_161477 = command->data[i_161481];
				nimln(259, "program.nim");
				{
					if ((NU)(i) >= (NU)(route->Sup.len)) raiseIndexError();
					if (!!(eqStrings(route->data[i], step_161477))) goto LA10;
					nimln(260, "program.nim");
					result = NIM_FALSE;
					nimln(261, "program.nim");
					goto BeforeRet;
				}
				LA10: ;
				nimln(262, "program.nim");
				TMP763 = addInt(i, ((NI) 1));
				i = (NI)(TMP763);
				nimln(3369, "system.nim");
				TMP764 = addInt(i_161481, ((NI) 1));
				i_161481 = (NI)(TMP764);
				nimln(3370, "system.nim");
				{
					if (!!(((command ? command->Sup.len : 0) == L_161483))) goto LA14;
					failedassertimpl_91603(((NimStringDesc*) &TMP739));
				}
				LA14: ;
			} LA7: ;
		}
	}
	nimln(263, "program.nim");
	result = NIM_TRUE;
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(TY17205*, replace_161499)(TY17205* route, TY17205* command) {
	TY17205* result;
	NI i;
	nimfr("replace", "program.nim")
	result = 0;
	nimln(266, "program.nim");
	result = (TY17205*) newSeq((&NTI17205), 0);
	nimln(267, "program.nim");
	i = ((NI) 0);
	{
		nimln(268, "program.nim");
		while (1) {
			if (!(i < (route ? route->Sup.len : 0))) goto LA2;
			nimln(269, "program.nim");
			{
				NIM_BOOL LOC5;
				NimStringDesc* LOC8;
				NI TMP766;
				LOC5 = 0;
				LOC5 = containtsat_161443(route, command, i);
				if (!LOC5) goto LA6;
				nimln(270, "program.nim");
				result = (TY17205*) incrSeqV2(&(result)->Sup, sizeof(NimStringDesc*));
				LOC8 = 0;
				LOC8 = result->data[result->Sup.len]; result->data[result->Sup.len] = copyStringRC1(((NimStringDesc*) &TMP765));
				if (LOC8) nimGCunrefNoCycle(LOC8);
				++result->Sup.len;
				nimln(271, "program.nim");
				TMP766 = addInt(i, (command ? command->Sup.len : 0));
				i = (NI)(TMP766);
			}
			goto LA3;
			LA6: ;
			{
				NimStringDesc* LOC10;
				NI TMP767;
				nimln(273, "program.nim");
				if ((NU)(i) >= (NU)(route->Sup.len)) raiseIndexError();
				result = (TY17205*) incrSeqV2(&(result)->Sup, sizeof(NimStringDesc*));
				LOC10 = 0;
				LOC10 = result->data[result->Sup.len]; result->data[result->Sup.len] = copyStringRC1(route->data[i]);
				if (LOC10) nimGCunrefNoCycle(LOC10);
				++result->Sup.len;
				nimln(274, "program.nim");
				TMP767 = addInt(i, ((NI) 1));
				i = (NI)(TMP767);
			}
			LA3: ;
		} LA2: ;
	}
	popFrame();
	return result;
}

N_NIMCALL(TY17205*, first_161573)(TY17205* route, NI amount) {
	TY17205* result;
	NI offset;
	nimfr("first", "program.nim")
	result = 0;
	nimln(277, "program.nim");
	result = (TY17205*) newSeq((&NTI17205), 0);
	nimln(278, "program.nim");
	offset = ((NI) 0);
	{
		NimStringDesc* step_161606;
		NI i_161639;
		NI L_161641;
		step_161606 = 0;
		nimln(3365, "system.nim");
		i_161639 = ((NI) 0);
		nimln(3366, "system.nim");
		L_161641 = (route ? route->Sup.len : 0);
		{
			nimln(3367, "system.nim");
			while (1) {
				NI TMP769;
				if (!(i_161639 < L_161641)) goto LA3;
				nimln(3368, "system.nim");
				if ((NU)(i_161639) >= (NU)(route->Sup.len)) raiseIndexError();
				step_161606 = route->data[i_161639];
				nimln(280, "program.nim");
				{
					NI TMP768;
					if (!eqStrings(step_161606, ((NimStringDesc*) &TMP765))) goto LA6;
					nimln(281, "program.nim");
					TMP768 = addInt(offset, ((NI) 1));
					offset = (NI)(TMP768);
				}
				goto LA4;
				LA6: ;
				{
					nimln(283, "program.nim");
					goto LA1;
				}
				LA4: ;
				nimln(3369, "system.nim");
				TMP769 = addInt(i_161639, ((NI) 1));
				i_161639 = (NI)(TMP769);
				nimln(3370, "system.nim");
				{
					if (!!(((route ? route->Sup.len : 0) == L_161641))) goto LA11;
					failedassertimpl_91603(((NimStringDesc*) &TMP739));
				}
				LA11: ;
			} LA3: ;
		}
	} LA1: ;
	{
		NI i_161617;
		NI HEX3Atmp_161643;
		NI TMP770;
		NI res_161646;
		i_161617 = 0;
		HEX3Atmp_161643 = 0;
		nimln(284, "program.nim");
		TMP770 = subInt(amount, ((NI) 1));
		HEX3Atmp_161643 = (NI)(TMP770);
		nimln(1874, "system.nim");
		res_161646 = ((NI) 0);
		{
			nimln(1875, "system.nim");
			while (1) {
				NI TMP773;
				NimStringDesc* LOC20;
				NI TMP774;
				if (!(res_161646 <= HEX3Atmp_161643)) goto LA15;
				nimln(1876, "system.nim");
				i_161617 = res_161646;
				nimln(285, "program.nim");
				{
					NI TMP771;
					NI TMP772;
					nimln(357, "system.nim");
					nimln(285, "program.nim");
					TMP771 = subInt((route ? route->Sup.len : 0), ((NI) 1));
					TMP772 = addInt(i_161617, offset);
					if (!((NI)(TMP771) < (NI)(TMP772))) goto LA18;
					nimln(286, "program.nim");
					goto LA13;
				}
				LA18: ;
				nimln(287, "program.nim");
				TMP773 = addInt(i_161617, offset);
				if ((NU)((NI)(TMP773)) >= (NU)(route->Sup.len)) raiseIndexError();
				result = (TY17205*) incrSeqV2(&(result)->Sup, sizeof(NimStringDesc*));
				LOC20 = 0;
				LOC20 = result->data[result->Sup.len]; result->data[result->Sup.len] = copyStringRC1(route->data[(NI)(TMP773)]);
				if (LOC20) nimGCunrefNoCycle(LOC20);
				++result->Sup.len;
				nimln(1895, "system.nim");
				TMP774 = addInt(res_161646, ((NI) 1));
				res_161646 = (NI)(TMP774);
			} LA15: ;
		}
	} LA13: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, isvalidlength_161674)(TY17205* command) {
	NIM_BOOL result;
	NI length;
	NI TMP775;
	nimfr("isValidLength", "program.nim")
	result = 0;
	nimln(290, "program.nim");
	TMP775 = subInt((command ? command->Sup.len : 0), ((NI) 1));
	length = (NI)(TMP775);
	{
		NimStringDesc* step_161697;
		NI i_161702;
		NI L_161704;
		step_161697 = 0;
		nimln(3365, "system.nim");
		i_161702 = ((NI) 0);
		nimln(3366, "system.nim");
		L_161704 = (command ? command->Sup.len : 0);
		{
			nimln(3367, "system.nim");
			while (1) {
				NI TMP776;
				NI TMP777;
				if (!(i_161702 < L_161704)) goto LA3;
				nimln(3368, "system.nim");
				if ((NU)(i_161702) >= (NU)(command->Sup.len)) raiseIndexError();
				step_161697 = command->data[i_161702];
				nimln(292, "program.nim");
				TMP776 = addInt(length, (step_161697 ? step_161697->Sup.len : 0));
				length = (NI)(TMP776);
				nimln(3369, "system.nim");
				TMP777 = addInt(i_161702, ((NI) 1));
				i_161702 = (NI)(TMP777);
				nimln(3370, "system.nim");
				{
					if (!!(((command ? command->Sup.len : 0) == L_161704))) goto LA6;
					failedassertimpl_91603(((NimStringDesc*) &TMP739));
				}
				LA6: ;
			} LA3: ;
		}
	}
	nimln(293, "program.nim");
	result = (length < ((NI) 21));
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, doesnotcontainterminator_161720)(TY17205* command) {
	NIM_BOOL result;
	nimfr("doesNotContainTerminator", "program.nim")
	result = 0;
	nimln(296, "program.nim");
	result = NIM_TRUE;
	{
		NimStringDesc* step_161734;
		NI i_161738;
		NI L_161740;
		step_161734 = 0;
		nimln(3365, "system.nim");
		i_161738 = ((NI) 0);
		nimln(3366, "system.nim");
		L_161740 = (command ? command->Sup.len : 0);
		{
			nimln(3367, "system.nim");
			while (1) {
				NI TMP778;
				if (!(i_161738 < L_161740)) goto LA3;
				nimln(3368, "system.nim");
				if ((NU)(i_161738) >= (NU)(command->Sup.len)) raiseIndexError();
				step_161734 = command->data[i_161738];
				nimln(298, "program.nim");
				{
					if (!eqStrings(step_161734, ((NimStringDesc*) &TMP765))) goto LA6;
					nimln(299, "program.nim");
					result = NIM_FALSE;
				}
				LA6: ;
				nimln(3369, "system.nim");
				TMP778 = addInt(i_161738, ((NI) 1));
				i_161738 = (NI)(TMP778);
				nimln(3370, "system.nim");
				{
					if (!!(((command ? command->Sup.len : 0) == L_161740))) goto LA10;
					failedassertimpl_91603(((NimStringDesc*) &TMP739));
				}
				LA10: ;
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, isvalid_161756)(TY17205* command) {
	NIM_BOOL result;
	NIM_BOOL LOC1;
	nimfr("isValid", "program.nim")
	result = 0;
	nimln(302, "program.nim");
	LOC1 = 0;
	LOC1 = isvalidlength_161674(command);
	if (!(LOC1)) goto LA2;
	LOC1 = doesnotcontainterminator_161720(command);
	LA2: ;
	result = LOC1;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, isempty_161767)(TY17205* route) {
	NIM_BOOL result;
	nimfr("isEmpty", "program.nim")
	result = 0;
	nimln(305, "program.nim");
	result = NIM_TRUE;
	{
		NimStringDesc* step_161781;
		NI i_161785;
		NI L_161787;
		step_161781 = 0;
		nimln(3365, "system.nim");
		i_161785 = ((NI) 0);
		nimln(3366, "system.nim");
		L_161787 = (route ? route->Sup.len : 0);
		{
			nimln(3367, "system.nim");
			while (1) {
				NI TMP779;
				if (!(i_161785 < L_161787)) goto LA3;
				nimln(3368, "system.nim");
				if ((NU)(i_161785) >= (NU)(route->Sup.len)) raiseIndexError();
				step_161781 = route->data[i_161785];
				nimln(307, "program.nim");
				{
					if (!!(eqStrings(step_161781, ((NimStringDesc*) &TMP765)))) goto LA6;
					nimln(308, "program.nim");
					result = NIM_FALSE;
				}
				LA6: ;
				nimln(3369, "system.nim");
				TMP779 = addInt(i_161785, ((NI) 1));
				i_161785 = (NI)(TMP779);
				nimln(3370, "system.nim");
				{
					if (!!(((route ? route->Sup.len : 0) == L_161787))) goto LA10;
					failedassertimpl_91603(((NimStringDesc*) &TMP739));
				}
				LA10: ;
			} LA3: ;
		}
	}
	popFrame();
	return result;
}
N_NIMCALL(void, TMP780)(void* p, NI op) {
	TY161805* a;
	NI LOC1;
	a = (TY161805*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1], op);
	}
}

N_NIMCALL(void, findprogramimpl_161812)(TY17205* route, NI depth, Program161804* Result) {
	NI commandsize;
	nimfr("findProgramImpl", "program.nim")
{	nimln(316, "program.nim");
	commandsize = ((NI) 10);
	nimln(317, "program.nim");
	{
		if (!((route ? route->Sup.len : 0) < commandsize)) goto LA3;
		nimln(318, "program.nim");
		commandsize = (route ? route->Sup.len : 0);
	}
	LA3: ;
	{
		nimln(319, "program.nim");
		while (1) {
			TY17205* command;
			NI TMP783;
			nimln(357, "system.nim");
			if (!(((NI) 0) < commandsize)) goto LA6;
			nimln(320, "program.nim");
			command = first_161573(route, commandsize);
			nimln(321, "program.nim");
			{
				NIM_BOOL LOC9;
				TY17205* reducedroute;
				LOC9 = 0;
				LOC9 = isvalid_161756(command);
				if (!LOC9) goto LA10;
				nimln(322, "program.nim");
				reducedroute = replace_161499(route, command);
				nimln(323, "program.nim");
				{
					if (!(depth == ((NI) 0))) goto LA14;
					nimln(324, "program.nim");
					{
						NIM_BOOL LOC18;
						TY161838 LOC21;
						LOC18 = 0;
						LOC18 = isempty_161767(reducedroute);
						if (!LOC18) goto LA19;
						nimln(325, "program.nim");
						unsureAsgnRef((void**) (&(*Result).Field0), (TY161805*) newSeq((&NTI161805), 1));
						memset((void*)LOC21, 0, sizeof(LOC21));
						genericSeqAssign((&LOC21[0]), command, (&NTI17205));
						genericSeqAssign((&(*Result).Field0->data[0]), LOC21[0], (&NTI17205));
						(*Result).Field1 = NIM_TRUE;
						nimln(326, "program.nim");
						goto BeforeRet;
					}
					LA19: ;
				}
				goto LA12;
				LA14: ;
				{
					Program161804 program;
					NI TMP781;
					memset((void*)(&program), 0, sizeof(program));
					nimln(328, "program.nim");
					TMP781 = subInt(depth, ((NI) 1));
					chckNil((void*)(&program));
					memset((void*)(&program), 0, sizeof(program));
					findprogramimpl_161812(reducedroute, (NI)(TMP781), (&program));
					nimln(329, "program.nim");
					{
						TY161838 LOC27;
						if (!program.Field1) goto LA25;
						nimln(330, "program.nim");
						unsureAsgnRef((void**) (&(*Result).Field0), (TY161805*) newSeq((&NTI161805), 1));
						memset((void*)LOC27, 0, sizeof(LOC27));
						genericSeqAssign((&LOC27[0]), command, (&NTI17205));
						genericSeqAssign((&(*Result).Field0->data[0]), LOC27[0], (&NTI17205));
						(*Result).Field1 = NIM_TRUE;
						{
							TY17205* function_162011;
							TY161805* HEX3Atmp_162042;
							NI i_162045;
							NI L_162047;
							function_162011 = 0;
							HEX3Atmp_162042 = 0;
							nimln(331, "program.nim");
							HEX3Atmp_162042 = program.Field0;
							nimln(3365, "system.nim");
							i_162045 = ((NI) 0);
							nimln(3366, "system.nim");
							L_162047 = (HEX3Atmp_162042 ? HEX3Atmp_162042->Sup.len : 0);
							{
								nimln(3367, "system.nim");
								while (1) {
									NI TMP782;
									if (!(i_162045 < L_162047)) goto LA30;
									nimln(3368, "system.nim");
									if ((NU)(i_162045) >= (NU)(HEX3Atmp_162042->Sup.len)) raiseIndexError();
									function_162011 = HEX3Atmp_162042->data[i_162045];
									nimln(332, "program.nim");
									(*Result).Field0 = (TY161805*) incrSeqV2(&((*Result).Field0)->Sup, sizeof(TY17205*));
									genericSeqAssign((&(*Result).Field0->data[(*Result).Field0->Sup.len]), function_162011, (&NTI17205));
									++(*Result).Field0->Sup.len;
									nimln(3369, "system.nim");
									TMP782 = addInt(i_162045, ((NI) 1));
									i_162045 = (NI)(TMP782);
									nimln(3370, "system.nim");
									{
										if (!!(((HEX3Atmp_162042 ? HEX3Atmp_162042->Sup.len : 0) == L_162047))) goto LA33;
										failedassertimpl_91603(((NimStringDesc*) &TMP739));
									}
									LA33: ;
								} LA30: ;
							}
						}
						nimln(333, "program.nim");
						goto BeforeRet;
					}
					LA25: ;
				}
				LA12: ;
			}
			LA10: ;
			nimln(334, "program.nim");
			TMP783 = subInt(commandsize, ((NI) 1));
			commandsize = (NI)(TMP783);
		} LA6: ;
	}
	nimln(335, "program.nim");
	genericSeqAssign((&(*Result).Field0), TMP784.Field0, (&NTI161805));
	(*Result).Field1 = TMP784.Field1;
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
}

N_NIMCALL(void, findprogram_162069)(TY17205* route, Program161804* Result) {
	nimfr("findProgram", "program.nim")
	nimln(339, "program.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI161804));
	findprogramimpl_161812(route, ((NI) 2), Result);
	popFrame();
}
N_NIMCALL(void, TMP788)(void* p, NI op) {
	TY162087* a;
	NI LOC1;
	a = (TY162087*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1].Field0, op);
	}
}

N_NIMCALL(TY162087*, findrouteswithintersections_162080)(Chart160047 chart, TY160531** intersections, NI i) {
	TY162087* result;
	nimfr("findRoutesWithIntersections", "program.nim")
{	result = 0;
	nimln(342, "program.nim");
	result = (TY162087*) newSeq((&NTI162087), 0);
	nimln(343, "program.nim");
	{
		Route160789 route;
		if (!(i == ((*intersections) ? (*intersections)->Sup.len : 0))) goto LA3;
		memset((void*)(&route), 0, sizeof(route));
		nimln(344, "program.nim");
		chckNil((void*)(&route));
		memset((void*)(&route), 0, sizeof(route));
		findroute_161178(chart, (*intersections), (&route));
		nimln(345, "program.nim");
		{
			if (!route.Field1) goto LA7;
			nimln(346, "program.nim");
			result = (TY162087*) incrSeqV2(&(result)->Sup, sizeof(Route160789));
			genericSeqAssign((&result->data[result->Sup.len].Field0), route.Field0, (&NTI17205));
			result->data[result->Sup.len].Field1 = route.Field1;
			++result->Sup.len;
		}
		LA7: ;
		nimln(347, "program.nim");
		goto BeforeRet;
	}
	LA3: ;
	{
		NU8 move_162162;
		NI i_162431;
		move_162162 = 0;
		nimln(1979, "system.nim");
		i_162431 = ((NI) 0);
		nimln(1980, "system.nim");
		{
			if (!(((NI) (i_162431)) <= ((NI) 2))) goto LA12;
			{
				nimln(1981, "system.nim");
				while (1) {
					TY162087* routes;
					NI TMP790;
					NI TMP792;
					nimln(1982, "system.nim");
					move_162162 = TMP789[(i_162431)- 0];
					nimln(349, "program.nim");
					if ((NU)(i) >= (NU)((*intersections)->Sup.len)) raiseIndexError();
					(*intersections)->data[i].Field2 = move_162162;
					nimln(350, "program.nim");
					TMP790 = addInt(i, ((NI) 1));
					routes = findrouteswithintersections_162080(chart, intersections, (NI)(TMP790));
					{
						Route160789 route_162411;
						NI i_162426;
						NI L_162428;
						memset((void*)(&route_162411), 0, sizeof(route_162411));
						nimln(3365, "system.nim");
						i_162426 = ((NI) 0);
						nimln(3366, "system.nim");
						L_162428 = (routes ? routes->Sup.len : 0);
						{
							nimln(3367, "system.nim");
							while (1) {
								NI TMP791;
								if (!(i_162426 < L_162428)) goto LA18;
								nimln(3368, "system.nim");
								if ((NU)(i_162426) >= (NU)(routes->Sup.len)) raiseIndexError();
								route_162411.Field0 = routes->data[i_162426].Field0;
								route_162411.Field1 = routes->data[i_162426].Field1;
								nimln(352, "program.nim");
								result = (TY162087*) incrSeqV2(&(result)->Sup, sizeof(Route160789));
								genericSeqAssign((&result->data[result->Sup.len].Field0), route_162411.Field0, (&NTI17205));
								result->data[result->Sup.len].Field1 = route_162411.Field1;
								++result->Sup.len;
								nimln(3369, "system.nim");
								TMP791 = addInt(i_162426, ((NI) 1));
								i_162426 = (NI)(TMP791);
								nimln(3370, "system.nim");
								{
									if (!!(((routes ? routes->Sup.len : 0) == L_162428))) goto LA21;
									failedassertimpl_91603(((NimStringDesc*) &TMP739));
								}
								LA21: ;
							} LA18: ;
						}
					}
					nimln(1983, "system.nim");
					{
						nimln(353, "system.nim");
						if (!(((NI) 2) <= ((NI) (i_162431)))) goto LA25;
						nimln(1983, "system.nim");
						goto LA14;
					}
					LA25: ;
					nimln(1984, "system.nim");
					TMP792 = addInt(i_162431, ((NI) 1));
					if (TMP792 < 0 || TMP792 > 2) raiseOverflow();
					i_162431 = (NI)(TMP792);
				}
			} LA14: ;
		}
		LA12: ;
	}
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, findsolvableroute_162463)(Chart160047 chart, Solvedprogram162457* Result) {
	TY160531* intersections;
	TY160418* LOC1;
	TY162087* routes;
	nimfr("findSolvableRoute", "program.nim")
{	nimln(360, "program.nim");
	LOC1 = 0;
	LOC1 = findintersections_160415(chart);
	intersections = tointersections_160796(LOC1);
	nimln(363, "program.nim");
	genericSeqAssign((&routes), TMP793, (&NTI162087));
	{
		Route160789 route_162508;
		NI i_162556;
		NI L_162558;
		memset((void*)(&route_162508), 0, sizeof(route_162508));
		nimln(3365, "system.nim");
		i_162556 = ((NI) 0);
		nimln(3366, "system.nim");
		L_162558 = (routes ? routes->Sup.len : 0);
		{
			nimln(3367, "system.nim");
			while (1) {
				Program161804 program;
				NI TMP799;
				if (!(i_162556 < L_162558)) goto LA4;
				nimln(3368, "system.nim");
				if ((NU)(i_162556) >= (NU)(routes->Sup.len)) raiseIndexError();
				route_162508.Field0 = routes->data[i_162556].Field0;
				route_162508.Field1 = routes->data[i_162556].Field1;
				memset((void*)(&program), 0, sizeof(program));
				nimln(365, "program.nim");
				chckNil((void*)(&program));
				memset((void*)(&program), 0, sizeof(program));
				findprogram_162069(route_162508.Field0, (&program));
				nimln(366, "program.nim");
				{
					if (!program.Field1) goto LA7;
					nimln(367, "program.nim");
					genericSeqAssign((&(*Result).Field0.Field0), program.Field0, (&NTI161805));
					(*Result).Field0.Field1 = program.Field1;
					genericSeqAssign((&(*Result).Field1.Field0), route_162508.Field0, (&NTI17205));
					(*Result).Field1.Field1 = route_162508.Field1;
					nimln(368, "program.nim");
					goto BeforeRet;
				}
				LA7: ;
				nimln(3369, "system.nim");
				TMP799 = addInt(i_162556, ((NI) 1));
				i_162556 = (NI)(TMP799);
				nimln(3370, "system.nim");
				{
					if (!!(((routes ? routes->Sup.len : 0) == L_162558))) goto LA11;
					failedassertimpl_91603(((NimStringDesc*) &TMP739));
				}
				LA11: ;
			} LA4: ;
		}
	}
	nimln(369, "program.nim");
	genericSeqAssign((&(*Result).Field0.Field0), TMP800.Field0.Field0, (&NTI161805));
	(*Result).Field0.Field1 = TMP800.Field0.Field1;
	genericSeqAssign((&(*Result).Field1.Field0), TMP800.Field1.Field0, (&NTI17205));
	(*Result).Field1.Field1 = TMP800.Field1.Field1;
	}BeforeRet: ;
	popFrame();
}

N_NIMCALL(void, print_162574)(Chart160047 chart) {
	nimfr("print", "program.nim")
	{
		NI y_162587;
		NI res_162635;
		y_162587 = 0;
		nimln(1874, "system.nim");
		res_162635 = ((NI) 0);
		{
			nimln(1875, "system.nim");
			while (1) {
				NI TMP806;
				if (!(res_162635 <= ((NI) 30))) goto LA3;
				nimln(1876, "system.nim");
				y_162587 = res_162635;
				nimln(373, "program.nim");
				writeline_161120(stdout, TMP803, 1);
				{
					NI x_162610;
					NI res_162629;
					x_162610 = 0;
					nimln(1874, "system.nim");
					res_162629 = ((NI) 0);
					{
						nimln(1875, "system.nim");
						while (1) {
							NI TMP805;
							if (!(res_162629 <= ((NI) 38))) goto LA6;
							nimln(1876, "system.nim");
							x_162610 = res_162629;
							nimln(375, "program.nim");
							if ((NU)(y_162587) > (NU)(30)) raiseIndexError();
							if ((NU)(x_162610) > (NU)(39)) raiseIndexError();
							write_16903(stdout, chart[(y_162587)- 0][(x_162610)- 0].Field2);
							nimln(1895, "system.nim");
							TMP805 = addInt(res_162629, ((NI) 1));
							res_162629 = (NI)(TMP805);
						} LA6: ;
					}
				}
				TMP806 = addInt(res_162635, ((NI) 1));
				res_162635 = (NI)(TMP806);
			} LA3: ;
		}
	}
	nimln(376, "program.nim");
	writeline_161120(stdout, TMP803, 1);
	popFrame();
}

N_NIMCALL(void, findmessage_162676)(Solvedprogram162457* program, Message162664* Result) {
	TY17205* a;
	TY17205* b;
	TY17205* c;
	TY17205* calls;
	NI i;
	TY17205* route;
	nimfr("findMessage", "program.nim")
{	nimln(386, "program.nim");
	if ((NU)(((NI) 0)) >= (NU)((*program).Field0.Field0->Sup.len)) raiseIndexError();
	genericSeqAssign((&a), (*program).Field0.Field0->data[((NI) 0)], (&NTI17205));
	nimln(387, "program.nim");
	if ((NU)(((NI) 1)) >= (NU)((*program).Field0.Field0->Sup.len)) raiseIndexError();
	genericSeqAssign((&b), (*program).Field0.Field0->data[((NI) 1)], (&NTI17205));
	nimln(388, "program.nim");
	if ((NU)(((NI) 2)) >= (NU)((*program).Field0.Field0->Sup.len)) raiseIndexError();
	genericSeqAssign((&c), (*program).Field0.Field0->data[((NI) 2)], (&NTI17205));
	nimln(389, "program.nim");
	calls = (TY17205*) newSeq((&NTI17205), 0);
	nimln(390, "program.nim");
	i = ((NI) 0);
	nimln(391, "program.nim");
	genericSeqAssign((&route), (*program).Field1.Field0, (&NTI17205));
	{
		nimln(392, "program.nim");
		while (1) {
			if (!(i < (route ? route->Sup.len : 0))) goto LA2;
			{
				nimln(393, "program.nim");
				{
					NIM_BOOL LOC6;
					NimStringDesc* LOC9;
					NI TMP808;
					LOC6 = 0;
					LOC6 = containtsat_161443(route, a, i);
					if (!LOC6) goto LA7;
					nimln(394, "program.nim");
					calls = (TY17205*) incrSeqV2(&(calls)->Sup, sizeof(NimStringDesc*));
					LOC9 = 0;
					LOC9 = calls->data[calls->Sup.len]; calls->data[calls->Sup.len] = copyStringRC1(((NimStringDesc*) &TMP807));
					if (LOC9) nimGCunrefNoCycle(LOC9);
					++calls->Sup.len;
					nimln(395, "program.nim");
					TMP808 = addInt(i, (a ? a->Sup.len : 0));
					i = (NI)(TMP808);
					nimln(396, "program.nim");
					goto LA3;
				}
				LA7: ;
				nimln(397, "program.nim");
				{
					NIM_BOOL LOC12;
					NimStringDesc* LOC15;
					NI TMP810;
					LOC12 = 0;
					LOC12 = containtsat_161443(route, b, i);
					if (!LOC12) goto LA13;
					nimln(398, "program.nim");
					calls = (TY17205*) incrSeqV2(&(calls)->Sup, sizeof(NimStringDesc*));
					LOC15 = 0;
					LOC15 = calls->data[calls->Sup.len]; calls->data[calls->Sup.len] = copyStringRC1(((NimStringDesc*) &TMP809));
					if (LOC15) nimGCunrefNoCycle(LOC15);
					++calls->Sup.len;
					nimln(399, "program.nim");
					TMP810 = addInt(i, (b ? b->Sup.len : 0));
					i = (NI)(TMP810);
					nimln(400, "program.nim");
					goto LA3;
				}
				LA13: ;
				nimln(401, "program.nim");
				{
					NIM_BOOL LOC18;
					NimStringDesc* LOC21;
					NI TMP812;
					LOC18 = 0;
					LOC18 = containtsat_161443(route, c, i);
					if (!LOC18) goto LA19;
					nimln(402, "program.nim");
					calls = (TY17205*) incrSeqV2(&(calls)->Sup, sizeof(NimStringDesc*));
					LOC21 = 0;
					LOC21 = calls->data[calls->Sup.len]; calls->data[calls->Sup.len] = copyStringRC1(((NimStringDesc*) &TMP811));
					if (LOC21) nimGCunrefNoCycle(LOC21);
					++calls->Sup.len;
					nimln(403, "program.nim");
					TMP812 = addInt(i, (c ? c->Sup.len : 0));
					i = (NI)(TMP812);
					nimln(404, "program.nim");
					goto LA3;
				}
				LA19: ;
				nimln(405, "program.nim");
				writeline_161120(stdout, TMP813, 1);
				nimln(406, "program.nim");
				goto LA1;
			} LA3: ;
		} LA2: ;
	} LA1: ;
	nimln(408, "program.nim");
	genericSeqAssign((&(*Result).Field0), calls, (&NTI17205));
	genericSeqAssign((&(*Result).Field1), a, (&NTI17205));
	genericSeqAssign((&(*Result).Field2), b, (&NTI17205));
	genericSeqAssign((&(*Result).Field3), c, (&NTI17205));
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
}

N_NIMCALL(void, sendstring_162827)(Processobj155407* robot, NimStringDesc* text) {
	nimfr("sendString", "program.nim")
	{
		NIM_CHAR c_162832;
		NI i_162837;
		NI L_162839;
		c_162832 = 0;
		nimln(3383, "system.nim");
		i_162837 = ((NI) 0);
		nimln(3384, "system.nim");
		L_162839 = (text ? text->Sup.len : 0);
		{
			nimln(3385, "system.nim");
			while (1) {
				NI TMP815;
				if (!(i_162837 < L_162839)) goto LA3;
				nimln(3386, "system.nim");
				if ((NU)(i_162837) > (NU)(text->Sup.len)) raiseIndexError();
				c_162832 = text->data[i_162837];
				nimln(412, "program.nim");
				givecommand_160013(robot, ((NI) (((NU8)(c_162832)))));
				nimln(3387, "system.nim");
				TMP815 = addInt(i_162837, ((NI) 1));
				i_162837 = (NI)(TMP815);
				nimln(3388, "system.nim");
				{
					if (!!(((text ? text->Sup.len : 0) == L_162839))) goto LA6;
					failedassertimpl_91603(((NimStringDesc*) &TMP816));
				}
				LA6: ;
			} LA3: ;
		}
	}
	popFrame();
}

N_NIMCALL(void, sendline_162855)(Processobj155407* robot, TY17205* line) {
	nimfr("sendLine", "program.nim")
	nimln(415, "program.nim");
	if ((NU)(((NI) 0)) >= (NU)(line->Sup.len)) raiseIndexError();
	sendstring_162827(robot, line->data[((NI) 0)]);
	{
		NI i_162878;
		NI HEX3Atmp_162880;
		NI TMP817;
		NI res_162883;
		i_162878 = 0;
		HEX3Atmp_162880 = 0;
		nimln(416, "program.nim");
		TMP817 = subInt((line ? line->Sup.len : 0), ((NI) 1));
		HEX3Atmp_162880 = (NI)(TMP817);
		nimln(1874, "system.nim");
		res_162883 = ((NI) 1);
		{
			nimln(1875, "system.nim");
			while (1) {
				NI TMP819;
				if (!(res_162883 <= HEX3Atmp_162880)) goto LA3;
				nimln(1876, "system.nim");
				i_162878 = res_162883;
				nimln(417, "program.nim");
				sendstring_162827(robot, ((NimStringDesc*) &TMP818));
				nimln(418, "program.nim");
				if ((NU)(i_162878) >= (NU)(line->Sup.len)) raiseIndexError();
				sendstring_162827(robot, line->data[i_162878]);
				nimln(1895, "system.nim");
				TMP819 = addInt(res_162883, ((NI) 1));
				res_162883 = (NI)(TMP819);
			} LA3: ;
		}
	}
	nimln(419, "program.nim");
	givecommand_160013(robot, ((NI) 10));
	popFrame();
}

N_NIMCALL(void, send_162902)(Processobj155407* robot, Message162664* message) {
	nimfr("send", "program.nim")
	nimln(422, "program.nim");
	sendline_162855(robot, (*message).Field0);
	nimln(423, "program.nim");
	sendline_162855(robot, (*message).Field1);
	nimln(424, "program.nim");
	sendline_162855(robot, (*message).Field2);
	nimln(425, "program.nim");
	sendline_162855(robot, (*message).Field3);
	popFrame();
}

static N_INLINE(NIM_BOOL, canbecycleroot_53067)(Cell49347* c) {
	NIM_BOOL result;
	nimfr("canBeCycleRoot", "gc.nim")
	result = 0;
	nimln(134, "gc.nim");
	nimln(1104, "system.nim");
	result = !((((*(*c).typ).flags &(1<<((((NU8) 1))&7)))!=0));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdcycleroot_53823)(Cell49347* c) {
	nimfr("rtlAddCycleRoot", "gc.nim")
	nimln(202, "gc.nim");
	{
		nimln(349, "system.nim");
		nimln(147, "gc.nim");
		if (!!((((NI) ((NI)((*c).refcount & ((NI) 3)))) == ((NI) 3)))) goto LA3;
		nimln(152, "gc.nim");
		(*c).refcount = (NI)((NI)((*c).refcount & ((NI) -4)) | ((NI) 3));
		nimln(204, "gc.nim");
		incl_50065((&gch_51459.cycleroots), c);
	}
	LA3: ;
	popFrame();
}

static N_INLINE(void, incref_55422)(Cell49347* c) {
	nimfr("incRef", "gc.nim")
	nimln(229, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	nimln(232, "gc.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = canbecycleroot_53067(c);
		if (!LOC3) goto LA4;
		nimln(233, "gc.nim");
		rtladdcycleroot_53823(c);
	}
	LA4: ;
	popFrame();
}

static N_INLINE(void, decref_55004)(Cell49347* c) {
	nimfr("decRef", "gc.nim")
	nimln(219, "gc.nim");
	{
		nimln(180, "gc.nim");
		(*c).refcount -= ((NI) 8);
		nimln(181, "gc.nim");
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3;
		nimln(220, "gc.nim");
		rtladdzct_54604(c);
	}
	goto LA1;
	LA3: ;
	{
		NIM_BOOL LOC6;
		nimln(221, "gc.nim");
		LOC6 = 0;
		LOC6 = canbecycleroot_53067(c);
		if (!LOC6) goto LA7;
		nimln(224, "gc.nim");
		rtladdcycleroot_53823(c);
	}
	goto LA1;
	LA7: ;
	LA1: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr("asgnRef", "gc.nim")
	nimln(257, "gc.nim");
	{
		Cell49347* LOC5;
		nimln(349, "system.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(257, "gc.nim");
		LOC5 = 0;
		LOC5 = usrtocell_53046(src);
		incref_55422(LOC5);
	}
	LA3: ;
	nimln(258, "gc.nim");
	{
		Cell49347* LOC10;
		nimln(349, "system.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8;
		nimln(258, "gc.nim");
		LOC10 = 0;
		LOC10 = usrtocell_53046((*dest));
		decref_55004(LOC10);
	}
	LA8: ;
	nimln(259, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(264, "gc.nim");
	{
		Cell49347* c;
		nimln(349, "system.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(265, "gc.nim");
		c = usrtocell_53046(src);
		nimln(182, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3: ;
	nimln(267, "gc.nim");
	{
		Cell49347* c;
		nimln(349, "system.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(268, "gc.nim");
		c = usrtocell_53046((*dest));
		nimln(269, "gc.nim");
		{
			nimln(180, "gc.nim");
			(*c).refcount -= ((NI) 8);
			nimln(181, "gc.nim");
			if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA11;
			nimln(270, "gc.nim");
			rtladdzct_54604(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(271, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner() {
	systemInit000();
	HEX00_parseutilsDatInit000();
	HEX00_strutilsDatInit000();
	HEX00_timesDatInit000();
	HEX00_posixDatInit000();
	HEX00_osDatInit000();
	HEX00_etcprivDatInit000();
	HEX00_hashesDatInit000();
	HEX00_strtabsDatInit000();
	HEX00_streamsDatInit000();
	HEX00_linuxDatInit000();
	HEX00_cpuinfoDatInit000();
	HEX00_osprocDatInit000();
	programDatInit000();
	HEX00_parseutilsInit000();
	HEX00_strutilsInit000();
	HEX00_timesInit000();
	HEX00_posixInit000();
	HEX00_osInit000();
	HEX00_etcprivInit000();
	HEX00_hashesInit000();
	HEX00_strtabsInit000();
	HEX00_streamsInit000();
	HEX00_linuxInit000();
	HEX00_cpuinfoInit000();
	HEX00_osprocInit000();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	programInit000();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, programInit000)(void) {
	nimfr("program", "program.nim")
	nimln(427, "program.nim");
	asgnRef((void**) (&robot_162912), spawnrobot_160004());
	nimln(428, "program.nim");
	chckNil((void*)chart_162919);
	genericReset((void*)chart_162919, (&NTI160047));
	readchart_160232(robot_162912, chart_162919);
	nimln(429, "program.nim");
	print_162574(chart_162919);
	nimln(434, "program.nim");
	chckNil((void*)(&program_162959));
	genericReset((void*)(&program_162959), (&NTI162457));
	findsolvableroute_162463(chart_162919, (&program_162959));
	{
		TY17205* HEX3Atmp_163144;
		NI i_163147;
		NI L_163149;
		HEX3Atmp_163144 = 0;
		nimln(435, "program.nim");
		genericSeqAssign((&HEX3Atmp_163144), program_162959.Field1.Field0, (&NTI17205));
		nimln(3365, "system.nim");
		i_163147 = ((NI) 0);
		nimln(3366, "system.nim");
		L_163149 = (HEX3Atmp_163144 ? HEX3Atmp_163144->Sup.len : 0);
		{
			nimln(3367, "system.nim");
			while (1) {
				NimStringDesc* LOC4;
				TY157060 LOC5;
				NI TMP824;
				if (!(i_163147 < L_163149)) goto LA3;
				nimln(3368, "system.nim");
				if ((NU)(i_163147) >= (NU)(HEX3Atmp_163144->Sup.len)) raiseIndexError();
				LOC4 = 0;
				LOC4 = step_163140; step_163140 = copyStringRC1(HEX3Atmp_163144->data[i_163147]);
				if (LOC4) nimGCunrefNoCycle(LOC4);
				nimln(436, "program.nim");
				memset((void*)LOC5, 0, sizeof(LOC5));
				LOC5[0] = copyString(((NimStringDesc*) &TMP822));
				LOC5[1] = copyString(step_163140);
				LOC5[2] = copyString(((NimStringDesc*) &TMP823));
				write_16911(stdout, LOC5, 3);
				nimln(3369, "system.nim");
				TMP824 = addInt(i_163147, ((NI) 1));
				i_163147 = (NI)(TMP824);
				nimln(3370, "system.nim");
				{
					if (!!(((HEX3Atmp_163144 ? HEX3Atmp_163144->Sup.len : 0) == L_163149))) goto LA8;
					failedassertimpl_91603(((NimStringDesc*) &TMP739));
				}
				LA8: ;
			} LA3: ;
		}
	}
	nimln(437, "program.nim");
	writeline_161120(stdout, TMP803, 1);
	{
		TY161805* HEX3Atmp_163218;
		NI i_163221;
		NI L_163223;
		HEX3Atmp_163218 = 0;
		nimln(438, "program.nim");
		genericSeqAssign((&HEX3Atmp_163218), program_162959.Field0.Field0, (&NTI161805));
		nimln(3365, "system.nim");
		i_163221 = ((NI) 0);
		nimln(3366, "system.nim");
		L_163223 = (HEX3Atmp_163218 ? HEX3Atmp_163218->Sup.len : 0);
		{
			nimln(3367, "system.nim");
			while (1) {
				NI TMP826;
				if (!(i_163221 < L_163223)) goto LA12;
				nimln(3368, "system.nim");
				if ((NU)(i_163221) >= (NU)(HEX3Atmp_163218->Sup.len)) raiseIndexError();
				genericSeqAssign((&function_163186), HEX3Atmp_163218->data[i_163221], (&NTI17205));
				{
					NI i_163215;
					NI L_163217;
					asgnRefNoCycle((void**) (&step_163196), NIM_NIL);
					nimln(3365, "system.nim");
					i_163215 = ((NI) 0);
					nimln(3366, "system.nim");
					L_163217 = (function_163186 ? function_163186->Sup.len : 0);
					{
						nimln(3367, "system.nim");
						while (1) {
							NimStringDesc* LOC16;
							NI TMP825;
							if (!(i_163215 < L_163217)) goto LA15;
							nimln(3368, "system.nim");
							if ((NU)(i_163215) >= (NU)(function_163186->Sup.len)) raiseIndexError();
							LOC16 = 0;
							LOC16 = step_163196; step_163196 = copyStringRC1(function_163186->data[i_163215]);
							if (LOC16) nimGCunrefNoCycle(LOC16);
							nimln(440, "program.nim");
							write_16895(stdout, step_163196);
							nimln(3369, "system.nim");
							TMP825 = addInt(i_163215, ((NI) 1));
							i_163215 = (NI)(TMP825);
							nimln(3370, "system.nim");
							{
								if (!!(((function_163186 ? function_163186->Sup.len : 0) == L_163217))) goto LA19;
								failedassertimpl_91603(((NimStringDesc*) &TMP739));
							}
							LA19: ;
						} LA15: ;
					}
				}
				nimln(441, "program.nim");
				writeline_161120(stdout, TMP803, 1);
				nimln(3369, "system.nim");
				TMP826 = addInt(i_163221, ((NI) 1));
				i_163221 = (NI)(TMP826);
				nimln(3370, "system.nim");
				{
					if (!!(((HEX3Atmp_163218 ? HEX3Atmp_163218->Sup.len : 0) == L_163223))) goto LA23;
					failedassertimpl_91603(((NimStringDesc*) &TMP739));
				}
				LA23: ;
			} LA12: ;
		}
	}
	nimln(442, "program.nim");
	chckNil((void*)(&message_163245));
	genericReset((void*)(&message_163245), (&NTI162664));
	findmessage_162676((&program_162959), (&message_163245));
	{
		TY17205* HEX3Atmp_163286;
		NI i_163289;
		NI L_163291;
		HEX3Atmp_163286 = 0;
		nimln(443, "program.nim");
		genericSeqAssign((&HEX3Atmp_163286), message_163245.Field0, (&NTI17205));
		nimln(3365, "system.nim");
		i_163289 = ((NI) 0);
		nimln(3366, "system.nim");
		L_163291 = (HEX3Atmp_163286 ? HEX3Atmp_163286->Sup.len : 0);
		{
			nimln(3367, "system.nim");
			while (1) {
				NimStringDesc* LOC28;
				NI TMP828;
				if (!(i_163289 < L_163291)) goto LA27;
				nimln(3368, "system.nim");
				if ((NU)(i_163289) >= (NU)(HEX3Atmp_163286->Sup.len)) raiseIndexError();
				LOC28 = 0;
				LOC28 = call_163282; call_163282 = copyStringRC1(HEX3Atmp_163286->data[i_163289]);
				if (LOC28) nimGCunrefNoCycle(LOC28);
				nimln(444, "program.nim");
				write_16895(stdout, call_163282);
				nimln(3369, "system.nim");
				TMP828 = addInt(i_163289, ((NI) 1));
				i_163289 = (NI)(TMP828);
				nimln(3370, "system.nim");
				{
					if (!!(((HEX3Atmp_163286 ? HEX3Atmp_163286->Sup.len : 0) == L_163291))) goto LA31;
					failedassertimpl_91603(((NimStringDesc*) &TMP739));
				}
				LA31: ;
			} LA27: ;
		}
	}
	nimln(445, "program.nim");
	send_162902(robot_162912, (&message_163245));
	nimln(446, "program.nim");
	sendline_162855(robot_162912, TMP829);
	{
		nimln(447, "program.nim");
		while (1) {
			Chart160047 LOC35;
			nimln(448, "program.nim");
			memset((void*)LOC35, 0, sizeof(LOC35));
			readchart_160232(robot_162912, LOC35);
			print_162574(LOC35);
		}
	}
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, programDatInit000)(void) {
static TNimNode* TMP741[3];
static TNimNode* TMP742[3];
NI TMP744;
static char* NIM_CONST TMP743[3] = {
"straight", 
"left", 
"right"};
static TNimNode* TMP786[2];
static TNimNode* TMP787[2];
static TNimNode* TMP820[3];
static TNimNode* TMP821[2];
static TNimNode* TMP827[4];
static TNimNode TMP138[26];
NTI160418.size = sizeof(TY160418*);
NTI160418.kind = 24;
NTI160418.base = (&NTI112900);
NTI160418.flags = 2;
NTI160418.marker = TMP735;
NTI160520.size = sizeof(Intersection160520);
NTI160520.kind = 18;
NTI160520.base = 0;
NTI160520.flags = 3;
TMP741[0] = &TMP138[1];
TMP138[1].kind = 1;
TMP138[1].offset = offsetof(Intersection160520, Field0);
TMP138[1].typ = (&NTI108);
TMP138[1].name = "Field0";
TMP741[1] = &TMP138[2];
TMP138[2].kind = 1;
TMP138[2].offset = offsetof(Intersection160520, Field1);
TMP138[2].typ = (&NTI108);
TMP138[2].name = "Field1";
TMP741[2] = &TMP138[3];
NTI160401.size = sizeof(NU8);
NTI160401.kind = 14;
NTI160401.base = 0;
NTI160401.flags = 3;
for (TMP744 = 0; TMP744 < 3; TMP744++) {
TMP138[TMP744+4].kind = 1;
TMP138[TMP744+4].offset = TMP744;
TMP138[TMP744+4].name = TMP743[TMP744];
TMP742[TMP744] = &TMP138[TMP744+4];
}
TMP138[7].len = 3; TMP138[7].kind = 2; TMP138[7].sons = &TMP742[0];
NTI160401.node = &TMP138[7];
TMP138[3].kind = 1;
TMP138[3].offset = offsetof(Intersection160520, Field2);
TMP138[3].typ = (&NTI160401);
TMP138[3].name = "Field2";
TMP138[0].len = 3; TMP138[0].kind = 2; TMP138[0].sons = &TMP741[0];
NTI160520.node = &TMP138[0];
NTI160531.size = sizeof(TY160531*);
NTI160531.kind = 24;
NTI160531.base = (&NTI160520);
NTI160531.flags = 2;
NTI160531.marker = TMP745;
NTI161805.size = sizeof(TY161805*);
NTI161805.kind = 24;
NTI161805.base = (&NTI17205);
NTI161805.flags = 2;
NTI161805.marker = TMP780;
NTI161804.size = sizeof(Program161804);
NTI161804.kind = 18;
NTI161804.base = 0;
NTI161804.flags = 2;
TMP786[0] = &TMP138[9];
TMP138[9].kind = 1;
TMP138[9].offset = offsetof(Program161804, Field0);
TMP138[9].typ = (&NTI161805);
TMP138[9].name = "Field0";
TMP786[1] = &TMP138[10];
TMP138[10].kind = 1;
TMP138[10].offset = offsetof(Program161804, Field1);
TMP138[10].typ = (&NTI138);
TMP138[10].name = "Field1";
TMP138[8].len = 2; TMP138[8].kind = 2; TMP138[8].sons = &TMP786[0];
NTI161804.node = &TMP138[8];
NTI160789.size = sizeof(Route160789);
NTI160789.kind = 18;
NTI160789.base = 0;
NTI160789.flags = 2;
TMP787[0] = &TMP138[12];
TMP138[12].kind = 1;
TMP138[12].offset = offsetof(Route160789, Field0);
TMP138[12].typ = (&NTI17205);
TMP138[12].name = "Field0";
TMP787[1] = &TMP138[13];
TMP138[13].kind = 1;
TMP138[13].offset = offsetof(Route160789, Field1);
TMP138[13].typ = (&NTI138);
TMP138[13].name = "Field1";
TMP138[11].len = 2; TMP138[11].kind = 2; TMP138[11].sons = &TMP787[0];
NTI160789.node = &TMP138[11];
NTI162087.size = sizeof(TY162087*);
NTI162087.kind = 24;
NTI162087.base = (&NTI160789);
NTI162087.flags = 2;
NTI162087.marker = TMP788;
NTI160039.size = sizeof(Square160039);
NTI160039.kind = 18;
NTI160039.base = 0;
NTI160039.flags = 3;
TMP820[0] = &TMP138[15];
TMP138[15].kind = 1;
TMP138[15].offset = offsetof(Square160039, Field0);
TMP138[15].typ = (&NTI108);
TMP138[15].name = "Field0";
TMP820[1] = &TMP138[16];
TMP138[16].kind = 1;
TMP138[16].offset = offsetof(Square160039, Field1);
TMP138[16].typ = (&NTI108);
TMP138[16].name = "Field1";
TMP820[2] = &TMP138[17];
TMP138[17].kind = 1;
TMP138[17].offset = offsetof(Square160039, Field2);
TMP138[17].typ = (&NTI147);
TMP138[17].name = "Field2";
TMP138[14].len = 3; TMP138[14].kind = 2; TMP138[14].sons = &TMP820[0];
NTI160039.node = &TMP138[14];
NTI160051.size = sizeof(TY160051);
NTI160051.kind = 16;
NTI160051.base = (&NTI160039);
NTI160051.flags = 3;
NTI160047.size = sizeof(Chart160047);
NTI160047.kind = 16;
NTI160047.base = (&NTI160051);
NTI160047.flags = 3;
NTI162457.size = sizeof(Solvedprogram162457);
NTI162457.kind = 18;
NTI162457.base = 0;
NTI162457.flags = 2;
TMP821[0] = &TMP138[19];
TMP138[19].kind = 1;
TMP138[19].offset = offsetof(Solvedprogram162457, Field0);
TMP138[19].typ = (&NTI161804);
TMP138[19].name = "Field0";
TMP821[1] = &TMP138[20];
TMP138[20].kind = 1;
TMP138[20].offset = offsetof(Solvedprogram162457, Field1);
TMP138[20].typ = (&NTI160789);
TMP138[20].name = "Field1";
TMP138[18].len = 2; TMP138[18].kind = 2; TMP138[18].sons = &TMP821[0];
NTI162457.node = &TMP138[18];
NTI162664.size = sizeof(Message162664);
NTI162664.kind = 18;
NTI162664.base = 0;
NTI162664.flags = 2;
TMP827[0] = &TMP138[22];
TMP138[22].kind = 1;
TMP138[22].offset = offsetof(Message162664, Field0);
TMP138[22].typ = (&NTI17205);
TMP138[22].name = "Field0";
TMP827[1] = &TMP138[23];
TMP138[23].kind = 1;
TMP138[23].offset = offsetof(Message162664, Field1);
TMP138[23].typ = (&NTI17205);
TMP138[23].name = "Field1";
TMP827[2] = &TMP138[24];
TMP138[24].kind = 1;
TMP138[24].offset = offsetof(Message162664, Field2);
TMP138[24].typ = (&NTI17205);
TMP138[24].name = "Field2";
TMP827[3] = &TMP138[25];
TMP138[25].kind = 1;
TMP138[25].offset = offsetof(Message162664, Field3);
TMP138[25].typ = (&NTI17205);
TMP138[25].name = "Field3";
TMP138[21].len = 4; TMP138[21].kind = 2; TMP138[21].sons = &TMP827[0];
NTI162664.node = &TMP138[21];
}

