/* Generated by Nim Compiler v0.12.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nim -o /home/marco/saus/advent-of-code-2019/17.nim/nimcache/streams.o /home/marco/saus/advent-of-code-2019/17.nim/nimcache/streams.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <setjmp.h>
#include <string.h>
#include <stdio.h>
typedef struct Ioerror4031 Ioerror4031;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Systemerror4029 Systemerror4029;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Cell49347 Cell49347;
typedef struct Cellseq49363 Cellseq49363;
typedef struct Gcheap51418 Gcheap51418;
typedef struct Gcstack51416 Gcstack51416;
typedef struct Cellset49359 Cellset49359;
typedef struct Pagedesc49355 Pagedesc49355;
typedef struct Memregion31291 Memregion31291;
typedef struct Smallchunk31243 Smallchunk31243;
typedef struct Llchunk31285 Llchunk31285;
typedef struct Bigchunk31245 Bigchunk31245;
typedef struct Intset31217 Intset31217;
typedef struct Trunk31213 Trunk31213;
typedef struct Avlnode31289 Avlnode31289;
typedef struct Gcstat51414 Gcstat51414;
typedef struct Streamobj148227 Streamobj148227;
typedef struct TSafePoint TSafePoint;
typedef struct Stringstreamobj149311 Stringstreamobj149311;
typedef struct Filestreamobj149467 Filestreamobj149467;
typedef struct Basechunk31241 Basechunk31241;
typedef struct Freecell31233 Freecell31233;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_NIMCALL_PTR(void, TY3889) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3894) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3889 marker;
TY3894 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  Systemerror4029  {
  Exception Sup;
};
struct  Ioerror4031  {
  Systemerror4029 Sup;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Cell49347  {
NI refcount;
TNimType* typ;
};
struct  Cellseq49363  {
NI len;
NI cap;
Cell49347** d;
};
struct  Cellset49359  {
NI counter;
NI max;
Pagedesc49355* head;
Pagedesc49355** data;
};
typedef Smallchunk31243* TY31306[512];
typedef Trunk31213* Trunkbuckets31215[256];
struct  Intset31217  {
Trunkbuckets31215 data;
};
struct  Memregion31291  {
NI minlargeobj;
NI maxlargeobj;
TY31306 freesmallchunks;
Llchunk31285* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk31245* freechunkslist;
Intset31217 chunkstarts;
Avlnode31289* root;
Avlnode31289* deleted;
Avlnode31289* last;
Avlnode31289* freeavlnodes;
};
struct  Gcstat51414  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Gcheap51418  {
Gcstack51416* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq49363 zct;
Cellseq49363 decstack;
Cellset49359 cycleroots;
Cellseq49363 tempstack;
NI recgclock;
Memregion31291 region;
Gcstat51414 stat;
};
typedef N_NIMCALL_PTR(void, TY148228) (Streamobj148227* s);
typedef N_NIMCALL_PTR(NIM_BOOL, TY148232) (Streamobj148227* s);
typedef N_NIMCALL_PTR(void, TY148236) (Streamobj148227* s, NI pos);
typedef N_NIMCALL_PTR(NI, TY148241) (Streamobj148227* s);
typedef N_NIMCALL_PTR(NI, TY148245) (Streamobj148227* s, void* buffer, NI buflen);
typedef N_NIMCALL_PTR(NI, TY148251) (Streamobj148227* s, void* buffer, NI buflen);
typedef N_NIMCALL_PTR(void, TY148257) (Streamobj148227* s, void* buffer, NI buflen);
typedef N_NIMCALL_PTR(void, TY148263) (Streamobj148227* s);
struct  Streamobj148227  {
  TNimObject Sup;
TY148228 closeimpl;
TY148232 atendimpl;
TY148236 setpositionimpl;
TY148241 getpositionimpl;
TY148245 readdataimpl;
TY148251 peekdataimpl;
TY148257 writedataimpl;
TY148263 flushimpl;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClPrc) (Exception* e, void* ClEnv);
void* ClEnv;
} TY19211;
struct  TSafePoint  {
TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
TY19211 raiseAction;
};
struct  Stringstreamobj149311  {
  Streamobj148227 Sup;
NimStringDesc* data;
NI pos;
};
struct  Filestreamobj149467  {
  Streamobj148227 Sup;
FILE* f;
};
struct  Gcstack51416  {
Gcstack51416* prev;
Gcstack51416* next;
void* starts;
void* pos;
NI maxstacksize;
};
typedef NI TY31222[8];
struct  Pagedesc49355  {
Pagedesc49355* next;
NI key;
TY31222 bits;
};
struct  Basechunk31241  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk31243  {
  Basechunk31241 Sup;
Smallchunk31243* next;
Smallchunk31243* prev;
Freecell31233* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk31285  {
NI size;
NI acc;
Llchunk31285* next;
};
struct  Bigchunk31245  {
  Basechunk31241 Sup;
Bigchunk31245* next;
Bigchunk31245* prev;
NI align;
NF data;
};
struct  Trunk31213  {
Trunk31213* next;
NI key;
TY31222 bits;
};
typedef Avlnode31289* TY31296[2];
struct  Avlnode31289  {
TY31296 link;
NI key;
NI upperbound;
NI level;
};
struct  Freecell31233  {
Freecell31233* next;
NI zerofield;
};
N_NIMCALL(Ioerror4031*, neweio_148205)(NimStringDesc* msg);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(Cell49347*, usrtocell_53046)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_23601)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtladdzct_54604)(Cell49347* c);
N_NOINLINE(void, addzct_53017)(Cellseq49363* s, Cell49347* c);
N_NIMCALL(void, flush_148275)(Streamobj148227* s);
N_NIMCALL(void, close_148291)(Streamobj148227* s);
N_NIMCALL(void, close_148307)(Streamobj148227* s, Streamobj148227* unused);
N_NIMCALL(NIM_BOOL, atend_148317)(Streamobj148227* s);
N_NIMCALL(NIM_BOOL, atend_148327)(Streamobj148227* s, Streamobj148227* unused);
N_NIMCALL(void, setposition_148338)(Streamobj148227* s, NI pos);
N_NIMCALL(void, setposition_148348)(Streamobj148227* s, Streamobj148227* unused, NI pos);
N_NIMCALL(NI, getposition_148359)(Streamobj148227* s);
N_NIMCALL(NI, getposition_148369)(Streamobj148227* s, Streamobj148227* unused);
N_NIMCALL(NI, readdata_148380)(Streamobj148227* s, void* buffer, NI buflen);
N_NIMCALL(NimStringDesc*, readall_148392)(Streamobj148227* s);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newlen);
N_NIMCALL(NI, readdata_148423)(Streamobj148227* s, Streamobj148227* unused, void* buffer, NI buflen);
N_NIMCALL(NI, peekdata_148436)(Streamobj148227* s, void* buffer, NI buflen);
N_NIMCALL(void, writedata_148448)(Streamobj148227* s, void* buffer, NI buflen);
N_NIMCALL(void, writedata_148459)(Streamobj148227* s, Streamobj148227* unused, void* buffer, NI buflen);
N_NIMCALL(void, write_148483)(Streamobj148227* s, NimStringDesc* x);
N_NIMCALL(void, writeln_148493)(Streamobj148227* s, NimStringDesc** args, NI argsLen0);
N_NIMCALL(void, writeline_148526)(Streamobj148227* s, NimStringDesc** args, NI argsLen0);
N_NIMCALL(NIM_CHAR, readchar_148584)(Streamobj148227* s);
N_NIMCALL(NIM_CHAR, peekchar_148595)(Streamobj148227* s);
N_NIMCALL(void, read_148611)(Streamobj148227* s, NIM_BOOL* result);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_NIMCALL(NIM_BOOL, readbool_148606)(Streamobj148227* s);
N_NIMCALL(void, peek_148656)(Streamobj148227* s, NIM_BOOL* result);
N_NIMCALL(NIM_BOOL, peekbool_148651)(Streamobj148227* s);
N_NIMCALL(void, read_148698)(Streamobj148227* s, NI8* result);
N_NIMCALL(NI8, readint8_148693)(Streamobj148227* s);
N_NIMCALL(void, peek_148743)(Streamobj148227* s, NI8* result);
N_NIMCALL(NI8, peekint8_148738)(Streamobj148227* s);
N_NIMCALL(void, read_148785)(Streamobj148227* s, NI16* result);
N_NIMCALL(NI16, readint16_148780)(Streamobj148227* s);
N_NIMCALL(void, peek_148830)(Streamobj148227* s, NI16* result);
N_NIMCALL(NI16, peekint16_148825)(Streamobj148227* s);
N_NIMCALL(void, read_148872)(Streamobj148227* s, NI32* result);
N_NIMCALL(NI32, readint32_148867)(Streamobj148227* s);
N_NIMCALL(void, peek_148917)(Streamobj148227* s, NI32* result);
N_NIMCALL(NI32, peekint32_148912)(Streamobj148227* s);
N_NIMCALL(void, read_148959)(Streamobj148227* s, NI64* result);
N_NIMCALL(NI64, readint64_148954)(Streamobj148227* s);
N_NIMCALL(void, peek_149004)(Streamobj148227* s, NI64* result);
N_NIMCALL(NI64, peekint64_148999)(Streamobj148227* s);
N_NIMCALL(void, read_149046)(Streamobj148227* s, NF32* result);
N_NIMCALL(NF32, readfloat32_149041)(Streamobj148227* s);
N_NIMCALL(void, peek_149091)(Streamobj148227* s, NF32* result);
N_NIMCALL(NF32, peekfloat32_149086)(Streamobj148227* s);
N_NIMCALL(void, read_149133)(Streamobj148227* s, NF* result);
N_NIMCALL(NF, readfloat64_149128)(Streamobj148227* s);
N_NIMCALL(void, peek_149175)(Streamobj148227* s, NF* result);
N_NIMCALL(NF, peekfloat64_149170)(Streamobj148227* s);
N_NIMCALL(NimStringDesc*, readstr_149212)(Streamobj148227* s, NI length);
N_NIMCALL(NimStringDesc*, peekstr_149227)(Streamobj148227* s, NI length);
N_NIMCALL(NIM_BOOL, readline_149242)(Streamobj148227* s, NimStringDesc** line);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_NIMCALL(NIM_BOOL, peekline_149264)(Streamobj148227* s, NimStringDesc** line);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
static N_INLINE(void, popSafePoint)(void);
static N_INLINE(void, setFrame)(TFrame* s);
N_NIMCALL(void, reraiseException)(void);
N_NIMCALL(NimStringDesc*, readline_149277)(Streamobj148227* s);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(NimStringDesc*, peekline_149297)(Streamobj148227* s);
N_NIMCALL(NIM_BOOL, ssatend_149322)(Streamobj148227* s_149324);
N_NIMCALL(void, chckObj)(TNimType* obj, TNimType* subclass);
N_NIMCALL(NI, clamp_149339)(NI x, NI a, NI b);
N_NIMCALL(void, sssetposition_149333)(Streamobj148227* s_149335, NI pos);
N_NIMCALL(NI, ssgetposition_149358)(Streamobj148227* s_149360);
N_NIMCALL(NI, ssreaddata_149369)(Streamobj148227* s_149371, void* buffer, NI buflen);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NIMCALL(NI, sspeekdata_149396)(Streamobj148227* s_149398, void* buffer, NI buflen);
N_NIMCALL(void, sswritedata_149414)(Streamobj148227* s_149416, void* buffer, NI buflen);
N_NIMCALL(void, ssclose_149436)(Streamobj148227* s_149438);
N_NIMCALL(Stringstreamobj149311*, newstringstream_149446)(NimStringDesc* s);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP624)(void* p, NI op);
N_NIMCALL(void, fsclose_149471)(Streamobj148227* s);
N_NIMCALL(void, fsflush_149489)(Streamobj148227* s);
N_NIMCALL(NIM_BOOL, fsatend_149495)(Streamobj148227* s);
N_NIMCALL(NIM_BOOL, endoffile_16860)(FILE* f);
N_NIMCALL(void, fssetposition_149502)(Streamobj148227* s, NI pos);
N_NIMCALL(void, setfilepos_16987)(FILE* f, NI64 pos);
N_NIMCALL(NI, fsgetposition_149509)(Streamobj148227* s);
N_NIMCALL(NI64, getfilepos_16991)(FILE* f);
N_NIMCALL(NI, fsreaddata_149517)(Streamobj148227* s, void* buffer, NI buflen);
N_NIMCALL(NI, readbuffer_16960)(FILE* f, void* buffer, NI len);
N_NIMCALL(NI, fspeekdata_149526)(Streamobj148227* s, void* buffer, NI buflen);
N_NIMCALL(void, fswritedata_149536)(Streamobj148227* s, void* buffer, NI buflen);
N_NIMCALL(NI, writebuffer_16982)(FILE* f, void* buffer, NI len);
N_NIMCALL(Filestreamobj149467*, newfilestream_149544)(FILE* f);
N_NIMCALL(void, TMP627)(void* p, NI op);
N_NIMCALL(Filestreamobj149467*, newfilestream_149559)(NimStringDesc* filename, NU8 mode);
N_NIMCALL(NIM_BOOL, open_16803)(FILE** f, NimStringDesc* filename, NU8 mode, NI bufsize);
N_NIMCALL(void, TMP646)(void* p, NI op);
STRING_LITERAL(TMP610, "\012", 1);
STRING_LITERAL(TMP612, "cannot read from stream", 23);
STRING_LITERAL(TMP614, "", 0);
STRING_LITERAL(TMP626, "cannot write to stream", 22);
extern TNimType NTI16835; /* ref IOError */
extern TNimType NTI4031; /* IOError */
extern TFrame* frameptr_20842;
extern Gcheap51418 gch_51459;
extern TSafePoint* exchandler_20843;
extern TNimType NTI4011; /* RootObj */
TNimType NTI148227; /* StreamObj */
TNimType NTI148228; /* proc (s: Stream){.gcsafe.} */
TNimType NTI148232; /* proc (s: Stream): bool{.gcsafe.} */
TNimType NTI148236; /* proc (s: Stream, pos: int){.gcsafe.} */
TNimType NTI148241; /* proc (s: Stream): int{.gcsafe.} */
TNimType NTI148245; /* proc (s: Stream, buffer: pointer, bufLen: int): int{.gcsafe.} */
TNimType NTI148251; /* proc (s: Stream, buffer: pointer, bufLen: int): int{.gcsafe.} */
TNimType NTI148257; /* proc (s: Stream, buffer: pointer, bufLen: int){.gcsafe.} */
TNimType NTI148263; /* proc (s: Stream){.gcsafe.} */
TNimType NTI149311; /* StringStreamObj */
extern TNimType NTI149; /* string */
extern TNimType NTI108; /* int */
TNimType NTI149309; /* StringStream */
TNimType NTI149467; /* FileStreamObj */
extern TNimType NTI16404; /* File */
TNimType NTI149465; /* FileStream */
TNimType NTI148225; /* Stream */

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_20842 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_20842).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_20842;
	frameptr_20842 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_23601();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_20842 = (*frameptr_20842).prev;
}

static N_INLINE(Cell49347*, usrtocell_53046)(void* usr) {
	Cell49347* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(131, "gc.nim");
	result = ((Cell49347*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell49347))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_54604)(Cell49347* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(212, "gc.nim");
	addzct_53017((&gch_51459.zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	Cell49347* c;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(246, "gc.nim");
	c = usrtocell_53046(p);
	nimln(248, "gc.nim");
	{
		nimln(180, "gc.nim");
		(*c).refcount -= ((NI) 8);
		nimln(181, "gc.nim");
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3;
		nimln(249, "gc.nim");
		rtladdzct_54604(c);
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(Ioerror4031*, neweio_148205)(NimStringDesc* msg) {
	Ioerror4031* result;
	NimStringDesc* LOC1;
	nimfr("newEIO", "streams.nim")
	result = 0;
	nimln(38, "streams.nim");
	result = (Ioerror4031*) newObj((&NTI16835), sizeof(Ioerror4031));
	(*result).Sup.Sup.Sup.m_type = (&NTI4031);
	nimln(39, "streams.nim");
	LOC1 = 0;
	LOC1 = (*result).Sup.Sup.message; (*result).Sup.Sup.message = copyStringRC1(msg);
	if (LOC1) nimGCunrefNoCycle(LOC1);
	popFrame();
	return result;
}

N_NIMCALL(void, flush_148275)(Streamobj148227* s) {
	nimfr("flush", "streams.nim")
	nimln(64, "streams.nim");
	{
		if (!!((*s).flushimpl == 0)) goto LA3;
		(*s).flushimpl(s);
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(void, close_148291)(Streamobj148227* s) {
	nimfr("close", "streams.nim")
	nimln(68, "streams.nim");
	{
		if (!!((*s).closeimpl == 0)) goto LA3;
		(*s).closeimpl(s);
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(void, close_148307)(Streamobj148227* s, Streamobj148227* unused) {
	nimfr("close", "streams.nim")
	nimln(72, "streams.nim");
	(*s).closeimpl(s);
	popFrame();
}

N_NIMCALL(NIM_BOOL, atend_148317)(Streamobj148227* s) {
	NIM_BOOL result;
	nimfr("atEnd", "streams.nim")
	result = 0;
	nimln(77, "streams.nim");
	result = (*s).atendimpl(s);
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, atend_148327)(Streamobj148227* s, Streamobj148227* unused) {
	NIM_BOOL result;
	nimfr("atEnd", "streams.nim")
	result = 0;
	nimln(82, "streams.nim");
	result = (*s).atendimpl(s);
	popFrame();
	return result;
}

N_NIMCALL(void, setposition_148338)(Streamobj148227* s, NI pos) {
	nimfr("setPosition", "streams.nim")
	nimln(86, "streams.nim");
	(*s).setpositionimpl(s, pos);
	popFrame();
}

N_NIMCALL(void, setposition_148348)(Streamobj148227* s, Streamobj148227* unused, NI pos) {
	nimfr("setPosition", "streams.nim")
	nimln(90, "streams.nim");
	(*s).setpositionimpl(s, pos);
	popFrame();
}

N_NIMCALL(NI, getposition_148359)(Streamobj148227* s) {
	NI result;
	nimfr("getPosition", "streams.nim")
	result = 0;
	nimln(94, "streams.nim");
	result = (*s).getpositionimpl(s);
	popFrame();
	return result;
}

N_NIMCALL(NI, getposition_148369)(Streamobj148227* s, Streamobj148227* unused) {
	NI result;
	nimfr("getPosition", "streams.nim")
	result = 0;
	nimln(98, "streams.nim");
	result = (*s).getpositionimpl(s);
	popFrame();
	return result;
}

N_NIMCALL(NI, readdata_148380)(Streamobj148227* s, void* buffer, NI buflen) {
	NI result;
	nimfr("readData", "streams.nim")
	result = 0;
	nimln(102, "streams.nim");
	result = (*s).readdataimpl(s, buffer, buflen);
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (a <= i);
		if (!(LOC3)) goto LA4;
		LOC3 = (i <= b);
		LA4: ;
		if (!LOC3) goto LA5;
		result = i;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(NimStringDesc*, readall_148392)(Streamobj148227* s) {
	NimStringDesc* result;
	NI r;
	nimfr("readAll", "streams.nim")
	result = 0;
	nimln(107, "streams.nim");
	result = mnewString(((NI) 1000));
	nimln(108, "streams.nim");
	r = ((NI) 0);
	{
		nimln(109, "streams.nim");
		while (1) {
			NI readbytes;
			NI TMP607;
			NI TMP608;
			nimln(110, "streams.nim");
			if ((NU)(r) > (NU)(result->Sup.len)) raiseIndexError();
			readbytes = readdata_148380(s, ((void*) ((&result->data[r]))), ((NI) 1000));
			nimln(111, "streams.nim");
			{
				NI TMP606;
				if (!(readbytes < ((NI) 1000))) goto LA5;
				nimln(112, "streams.nim");
				TMP606 = addInt(r, readbytes);
				result = setLengthStr(result, ((NI)chckRange((NI)(TMP606), ((NI) 0), ((NI) IL64(9223372036854775807)))));
				nimln(113, "streams.nim");
				goto LA1;
			}
			LA5: ;
			nimln(114, "streams.nim");
			TMP607 = addInt(r, ((NI) 1000));
			r = (NI)(TMP607);
			nimln(115, "streams.nim");
			TMP608 = addInt(r, ((NI) 1000));
			result = setLengthStr(result, ((NI)chckRange((NI)(TMP608), ((NI) 0), ((NI) IL64(9223372036854775807)))));
		}
	} LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, readdata_148423)(Streamobj148227* s, Streamobj148227* unused, void* buffer, NI buflen) {
	NI result;
	nimfr("readData", "streams.nim")
	result = 0;
	nimln(120, "streams.nim");
	result = (*s).readdataimpl(s, buffer, buflen);
	popFrame();
	return result;
}

N_NIMCALL(NI, peekdata_148436)(Streamobj148227* s, void* buffer, NI buflen) {
	NI result;
	nimfr("peekData", "streams.nim")
	result = 0;
	nimln(125, "streams.nim");
	result = (*s).peekdataimpl(s, buffer, buflen);
	popFrame();
	return result;
}

N_NIMCALL(void, writedata_148448)(Streamobj148227* s, void* buffer, NI buflen) {
	nimfr("writeData", "streams.nim")
	nimln(130, "streams.nim");
	(*s).writedataimpl(s, buffer, buflen);
	popFrame();
}

N_NIMCALL(void, writedata_148459)(Streamobj148227* s, Streamobj148227* unused, void* buffer, NI buflen) {
	nimfr("writeData", "streams.nim")
	nimln(136, "streams.nim");
	(*s).writedataimpl(s, buffer, buflen);
	popFrame();
}

N_NIMCALL(void, write_148483)(Streamobj148227* s, NimStringDesc* x) {
	nimfr("write", "streams.nim")
	nimln(151, "streams.nim");
	writedata_148448(s, ((void*) (x->data)), (x ? x->Sup.len : 0));
	popFrame();
}

N_NIMCALL(void, writeln_148493)(Streamobj148227* s, NimStringDesc** args, NI argsLen0) {
	nimfr("writeLn", "streams.nim")
	{
		NimStringDesc* str_148506;
		NI i_148510;
		str_148506 = 0;
		nimln(1965, "system.nim");
		i_148510 = ((NI) 0);
		{
			nimln(1966, "system.nim");
			while (1) {
				NI TMP609;
				if (!(i_148510 < argsLen0)) goto LA3;
				nimln(1967, "system.nim");
				if ((NU)(i_148510) >= (NU)(argsLen0)) raiseIndexError();
				str_148506 = args[i_148510];
				nimln(155, "streams.nim");
				write_148483(s, str_148506);
				nimln(1968, "system.nim");
				TMP609 = addInt(i_148510, ((NI) 1));
				i_148510 = (NI)(TMP609);
			} LA3: ;
		}
	}
	nimln(156, "streams.nim");
	write_148483(s, ((NimStringDesc*) &TMP610));
	popFrame();
}

N_NIMCALL(void, writeline_148526)(Streamobj148227* s, NimStringDesc** args, NI argsLen0) {
	nimfr("writeLine", "streams.nim")
	{
		NimStringDesc* str_148539;
		NI i_148543;
		str_148539 = 0;
		nimln(1965, "system.nim");
		i_148543 = ((NI) 0);
		{
			nimln(1966, "system.nim");
			while (1) {
				NI TMP611;
				if (!(i_148543 < argsLen0)) goto LA3;
				nimln(1967, "system.nim");
				if ((NU)(i_148543) >= (NU)(argsLen0)) raiseIndexError();
				str_148539 = args[i_148543];
				nimln(161, "streams.nim");
				write_148483(s, str_148539);
				nimln(1968, "system.nim");
				TMP611 = addInt(i_148543, ((NI) 1));
				i_148543 = (NI)(TMP611);
			} LA3: ;
		}
	}
	nimln(162, "streams.nim");
	write_148483(s, ((NimStringDesc*) &TMP610));
	popFrame();
}

N_NIMCALL(NIM_CHAR, readchar_148584)(Streamobj148227* s) {
	NIM_CHAR result;
	nimfr("readChar", "streams.nim")
	result = 0;
	nimln(177, "streams.nim");
	{
		NI LOC3;
		nimln(349, "system.nim");
		nimln(177, "streams.nim");
		LOC3 = 0;
		LOC3 = readdata_148380(s, ((void*) ((&result))), ((NI) 1));
		if (!!((LOC3 == ((NI) 1)))) goto LA4;
		result = 0;
	}
	LA4: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_CHAR, peekchar_148595)(Streamobj148227* s) {
	NIM_CHAR result;
	nimfr("peekChar", "streams.nim")
	result = 0;
	nimln(182, "streams.nim");
	{
		NI LOC3;
		nimln(349, "system.nim");
		nimln(182, "streams.nim");
		LOC3 = 0;
		LOC3 = peekdata_148436(s, ((void*) ((&result))), ((NI) 1));
		if (!!((LOC3 == ((NI) 1)))) goto LA4;
		result = 0;
	}
	LA4: ;
	popFrame();
	return result;
}

N_NIMCALL(void, read_148611)(Streamobj148227* s, NIM_BOOL* result) {
	nimfr("read", "streams.nim")
	nimln(166, "streams.nim");
	{
		NI LOC3;
		Ioerror4031* LOC6;
		nimln(349, "system.nim");
		nimln(166, "streams.nim");
		LOC3 = 0;
		LOC3 = readdata_148380(s, ((void*) (result)), ((NI) 1));
		if (!!((LOC3 == ((NI) 1)))) goto LA4;
		nimln(167, "streams.nim");
		LOC6 = 0;
		LOC6 = neweio_148205(((NimStringDesc*) &TMP612));
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NIM_BOOL, readbool_148606)(Streamobj148227* s) {
	NIM_BOOL result;
	nimfr("readBool", "streams.nim")
	result = 0;
	nimln(186, "streams.nim");
	read_148611(s, (&result));
	popFrame();
	return result;
}

N_NIMCALL(void, peek_148656)(Streamobj148227* s, NIM_BOOL* result) {
	nimfr("peek", "streams.nim")
	nimln(171, "streams.nim");
	{
		NI LOC3;
		Ioerror4031* LOC6;
		nimln(349, "system.nim");
		nimln(171, "streams.nim");
		LOC3 = 0;
		LOC3 = peekdata_148436(s, ((void*) (result)), ((NI) 1));
		if (!!((LOC3 == ((NI) 1)))) goto LA4;
		nimln(172, "streams.nim");
		LOC6 = 0;
		LOC6 = neweio_148205(((NimStringDesc*) &TMP612));
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NIM_BOOL, peekbool_148651)(Streamobj148227* s) {
	NIM_BOOL result;
	nimfr("peekBool", "streams.nim")
	result = 0;
	nimln(190, "streams.nim");
	peek_148656(s, (&result));
	popFrame();
	return result;
}

N_NIMCALL(void, read_148698)(Streamobj148227* s, NI8* result) {
	nimfr("read", "streams.nim")
	nimln(166, "streams.nim");
	{
		NI LOC3;
		Ioerror4031* LOC6;
		nimln(349, "system.nim");
		nimln(166, "streams.nim");
		LOC3 = 0;
		LOC3 = readdata_148380(s, ((void*) (result)), ((NI) 1));
		if (!!((LOC3 == ((NI) 1)))) goto LA4;
		nimln(167, "streams.nim");
		LOC6 = 0;
		LOC6 = neweio_148205(((NimStringDesc*) &TMP612));
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NI8, readint8_148693)(Streamobj148227* s) {
	NI8 result;
	nimfr("readInt8", "streams.nim")
	result = 0;
	nimln(194, "streams.nim");
	read_148698(s, (&result));
	popFrame();
	return result;
}

N_NIMCALL(void, peek_148743)(Streamobj148227* s, NI8* result) {
	nimfr("peek", "streams.nim")
	nimln(171, "streams.nim");
	{
		NI LOC3;
		Ioerror4031* LOC6;
		nimln(349, "system.nim");
		nimln(171, "streams.nim");
		LOC3 = 0;
		LOC3 = peekdata_148436(s, ((void*) (result)), ((NI) 1));
		if (!!((LOC3 == ((NI) 1)))) goto LA4;
		nimln(172, "streams.nim");
		LOC6 = 0;
		LOC6 = neweio_148205(((NimStringDesc*) &TMP612));
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NI8, peekint8_148738)(Streamobj148227* s) {
	NI8 result;
	nimfr("peekInt8", "streams.nim")
	result = 0;
	nimln(198, "streams.nim");
	peek_148743(s, (&result));
	popFrame();
	return result;
}

N_NIMCALL(void, read_148785)(Streamobj148227* s, NI16* result) {
	nimfr("read", "streams.nim")
	nimln(166, "streams.nim");
	{
		NI LOC3;
		Ioerror4031* LOC6;
		nimln(349, "system.nim");
		nimln(166, "streams.nim");
		LOC3 = 0;
		LOC3 = readdata_148380(s, ((void*) (result)), ((NI) 2));
		if (!!((LOC3 == ((NI) 2)))) goto LA4;
		nimln(167, "streams.nim");
		LOC6 = 0;
		LOC6 = neweio_148205(((NimStringDesc*) &TMP612));
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NI16, readint16_148780)(Streamobj148227* s) {
	NI16 result;
	nimfr("readInt16", "streams.nim")
	result = 0;
	nimln(202, "streams.nim");
	read_148785(s, (&result));
	popFrame();
	return result;
}

N_NIMCALL(void, peek_148830)(Streamobj148227* s, NI16* result) {
	nimfr("peek", "streams.nim")
	nimln(171, "streams.nim");
	{
		NI LOC3;
		Ioerror4031* LOC6;
		nimln(349, "system.nim");
		nimln(171, "streams.nim");
		LOC3 = 0;
		LOC3 = peekdata_148436(s, ((void*) (result)), ((NI) 2));
		if (!!((LOC3 == ((NI) 2)))) goto LA4;
		nimln(172, "streams.nim");
		LOC6 = 0;
		LOC6 = neweio_148205(((NimStringDesc*) &TMP612));
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NI16, peekint16_148825)(Streamobj148227* s) {
	NI16 result;
	nimfr("peekInt16", "streams.nim")
	result = 0;
	nimln(206, "streams.nim");
	peek_148830(s, (&result));
	popFrame();
	return result;
}

N_NIMCALL(void, read_148872)(Streamobj148227* s, NI32* result) {
	nimfr("read", "streams.nim")
	nimln(166, "streams.nim");
	{
		NI LOC3;
		Ioerror4031* LOC6;
		nimln(349, "system.nim");
		nimln(166, "streams.nim");
		LOC3 = 0;
		LOC3 = readdata_148380(s, ((void*) (result)), ((NI) 4));
		if (!!((LOC3 == ((NI) 4)))) goto LA4;
		nimln(167, "streams.nim");
		LOC6 = 0;
		LOC6 = neweio_148205(((NimStringDesc*) &TMP612));
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NI32, readint32_148867)(Streamobj148227* s) {
	NI32 result;
	nimfr("readInt32", "streams.nim")
	result = 0;
	nimln(210, "streams.nim");
	read_148872(s, (&result));
	popFrame();
	return result;
}

N_NIMCALL(void, peek_148917)(Streamobj148227* s, NI32* result) {
	nimfr("peek", "streams.nim")
	nimln(171, "streams.nim");
	{
		NI LOC3;
		Ioerror4031* LOC6;
		nimln(349, "system.nim");
		nimln(171, "streams.nim");
		LOC3 = 0;
		LOC3 = peekdata_148436(s, ((void*) (result)), ((NI) 4));
		if (!!((LOC3 == ((NI) 4)))) goto LA4;
		nimln(172, "streams.nim");
		LOC6 = 0;
		LOC6 = neweio_148205(((NimStringDesc*) &TMP612));
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NI32, peekint32_148912)(Streamobj148227* s) {
	NI32 result;
	nimfr("peekInt32", "streams.nim")
	result = 0;
	nimln(214, "streams.nim");
	peek_148917(s, (&result));
	popFrame();
	return result;
}

N_NIMCALL(void, read_148959)(Streamobj148227* s, NI64* result) {
	nimfr("read", "streams.nim")
	nimln(166, "streams.nim");
	{
		NI LOC3;
		Ioerror4031* LOC6;
		nimln(349, "system.nim");
		nimln(166, "streams.nim");
		LOC3 = 0;
		LOC3 = readdata_148380(s, ((void*) (result)), ((NI) 8));
		if (!!((LOC3 == ((NI) 8)))) goto LA4;
		nimln(167, "streams.nim");
		LOC6 = 0;
		LOC6 = neweio_148205(((NimStringDesc*) &TMP612));
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NI64, readint64_148954)(Streamobj148227* s) {
	NI64 result;
	nimfr("readInt64", "streams.nim")
	result = 0;
	nimln(218, "streams.nim");
	read_148959(s, (&result));
	popFrame();
	return result;
}

N_NIMCALL(void, peek_149004)(Streamobj148227* s, NI64* result) {
	nimfr("peek", "streams.nim")
	nimln(171, "streams.nim");
	{
		NI LOC3;
		Ioerror4031* LOC6;
		nimln(349, "system.nim");
		nimln(171, "streams.nim");
		LOC3 = 0;
		LOC3 = peekdata_148436(s, ((void*) (result)), ((NI) 8));
		if (!!((LOC3 == ((NI) 8)))) goto LA4;
		nimln(172, "streams.nim");
		LOC6 = 0;
		LOC6 = neweio_148205(((NimStringDesc*) &TMP612));
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NI64, peekint64_148999)(Streamobj148227* s) {
	NI64 result;
	nimfr("peekInt64", "streams.nim")
	result = 0;
	nimln(222, "streams.nim");
	peek_149004(s, (&result));
	popFrame();
	return result;
}

N_NIMCALL(void, read_149046)(Streamobj148227* s, NF32* result) {
	nimfr("read", "streams.nim")
	nimln(166, "streams.nim");
	{
		NI LOC3;
		Ioerror4031* LOC6;
		nimln(349, "system.nim");
		nimln(166, "streams.nim");
		LOC3 = 0;
		LOC3 = readdata_148380(s, ((void*) (result)), ((NI) 4));
		if (!!((LOC3 == ((NI) 4)))) goto LA4;
		nimln(167, "streams.nim");
		LOC6 = 0;
		LOC6 = neweio_148205(((NimStringDesc*) &TMP612));
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NF32, readfloat32_149041)(Streamobj148227* s) {
	NF32 result;
	nimfr("readFloat32", "streams.nim")
	result = 0;
	nimln(226, "streams.nim");
	read_149046(s, (&result));
	popFrame();
	return result;
}

N_NIMCALL(void, peek_149091)(Streamobj148227* s, NF32* result) {
	nimfr("peek", "streams.nim")
	nimln(171, "streams.nim");
	{
		NI LOC3;
		Ioerror4031* LOC6;
		nimln(349, "system.nim");
		nimln(171, "streams.nim");
		LOC3 = 0;
		LOC3 = peekdata_148436(s, ((void*) (result)), ((NI) 4));
		if (!!((LOC3 == ((NI) 4)))) goto LA4;
		nimln(172, "streams.nim");
		LOC6 = 0;
		LOC6 = neweio_148205(((NimStringDesc*) &TMP612));
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NF32, peekfloat32_149086)(Streamobj148227* s) {
	NF32 result;
	nimfr("peekFloat32", "streams.nim")
	result = 0;
	nimln(230, "streams.nim");
	peek_149091(s, (&result));
	popFrame();
	return result;
}

N_NIMCALL(void, read_149133)(Streamobj148227* s, NF* result) {
	nimfr("read", "streams.nim")
	nimln(166, "streams.nim");
	{
		NI LOC3;
		Ioerror4031* LOC6;
		nimln(349, "system.nim");
		nimln(166, "streams.nim");
		LOC3 = 0;
		LOC3 = readdata_148380(s, ((void*) (result)), ((NI) 8));
		if (!!((LOC3 == ((NI) 8)))) goto LA4;
		nimln(167, "streams.nim");
		LOC6 = 0;
		LOC6 = neweio_148205(((NimStringDesc*) &TMP612));
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NF, readfloat64_149128)(Streamobj148227* s) {
	NF result;
	nimfr("readFloat64", "streams.nim")
	result = 0;
	nimln(234, "streams.nim");
	read_149133(s, (&result));
	popFrame();
	return result;
}

N_NIMCALL(void, peek_149175)(Streamobj148227* s, NF* result) {
	nimfr("peek", "streams.nim")
	nimln(171, "streams.nim");
	{
		NI LOC3;
		Ioerror4031* LOC6;
		nimln(349, "system.nim");
		nimln(171, "streams.nim");
		LOC3 = 0;
		LOC3 = peekdata_148436(s, ((void*) (result)), ((NI) 8));
		if (!!((LOC3 == ((NI) 8)))) goto LA4;
		nimln(172, "streams.nim");
		LOC6 = 0;
		LOC6 = neweio_148205(((NimStringDesc*) &TMP612));
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NF, peekfloat64_149170)(Streamobj148227* s) {
	NF result;
	nimfr("peekFloat64", "streams.nim")
	result = 0;
	nimln(238, "streams.nim");
	peek_149175(s, (&result));
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, readstr_149212)(Streamobj148227* s, NI length) {
	NimStringDesc* result;
	NI L;
	nimfr("readStr", "streams.nim")
	result = 0;
	nimln(243, "streams.nim");
	result = mnewString(((NI)chckRange(length, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln(244, "streams.nim");
	if ((NU)(((NI) 0)) > (NU)(result->Sup.len)) raiseIndexError();
	L = readdata_148380(s, ((void*) ((&result->data[((NI) 0)]))), length);
	nimln(245, "streams.nim");
	{
		nimln(349, "system.nim");
		if (!!((L == length))) goto LA3;
		nimln(245, "streams.nim");
		result = setLengthStr(result, ((NI)chckRange(L, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	}
	LA3: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, peekstr_149227)(Streamobj148227* s, NI length) {
	NimStringDesc* result;
	NI L;
	nimfr("peekStr", "streams.nim")
	result = 0;
	nimln(250, "streams.nim");
	result = mnewString(((NI)chckRange(length, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln(251, "streams.nim");
	if ((NU)(((NI) 0)) > (NU)(result->Sup.len)) raiseIndexError();
	L = peekdata_148436(s, ((void*) ((&result->data[((NI) 0)]))), length);
	nimln(252, "streams.nim");
	{
		nimln(349, "system.nim");
		if (!!((L == length))) goto LA3;
		nimln(252, "streams.nim");
		result = setLengthStr(result, ((NI)chckRange(L, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	}
	LA3: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, readline_149242)(Streamobj148227* s, NimStringDesc** line) {
	NIM_BOOL result;
	nimfr("readLine", "streams.nim")
{	result = 0;
	nimln(261, "streams.nim");
	(*line) = setLengthStr((*line), ((NI) 0));
	{
		nimln(262, "streams.nim");
		while (1) {
			NIM_CHAR c;
			nimln(263, "streams.nim");
			c = readchar_148584(s);
			nimln(264, "streams.nim");
			{
				if (!((NU8)(c) == (NU8)(13))) goto LA5;
				nimln(265, "streams.nim");
				c = readchar_148584(s);
				nimln(266, "streams.nim");
				goto LA1;
			}
			goto LA3;
			LA5: ;
			{
				nimln(267, "streams.nim");
				if (!((NU8)(c) == (NU8)(10))) goto LA8;
				goto LA1;
			}
			goto LA3;
			LA8: ;
			{
				nimln(268, "streams.nim");
				if (!((NU8)(c) == (NU8)(0))) goto LA11;
				nimln(269, "streams.nim");
				{
					nimln(357, "system.nim");
					nimln(269, "streams.nim");
					if (!(((NI) 0) < ((*line) ? (*line)->Sup.len : 0))) goto LA15;
					goto LA1;
				}
				goto LA13;
				LA15: ;
				{
					nimln(270, "streams.nim");
					result = NIM_FALSE;
					goto BeforeRet;
				}
				LA13: ;
			}
			goto LA3;
			LA11: ;
			LA3: ;
			nimln(271, "streams.nim");
			(*line) = addChar((*line), c);
		}
	} LA1: ;
	nimln(272, "streams.nim");
	result = NIM_TRUE;
	}BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(void, pushSafePoint)(TSafePoint* s) {
	(*s).hasRaiseAction = NIM_FALSE;
	(*s).prev = exchandler_20843;
	exchandler_20843 = s;
}

static N_INLINE(void, popSafePoint)(void) {
	exchandler_20843 = (*exchandler_20843).prev;
}

static N_INLINE(void, setFrame)(TFrame* s) {
	frameptr_20842 = s;
}

N_NIMCALL(NIM_BOOL, peekline_149264)(Streamobj148227* s, NimStringDesc** line) {
	NIM_BOOL volatile result;
	NI pos;
	TSafePoint TMP613;
	nimfr("peekLine", "streams.nim")
	result = 0;
	nimln(281, "streams.nim");
	pos = getposition_148359(s);
	nimln(282, "streams.nim");
	pushSafePoint(&TMP613);
	TMP613.status = setjmp(TMP613.context);
	if (TMP613.status == 0) {
		nimln(283, "streams.nim");
		result = readline_149242(s, line);
		popSafePoint();
	}
	else {
		popSafePoint();
		setFrame((TFrame*)&FR);
	}
	{
		nimln(282, "streams.nim");
		setposition_148338(s, pos);
	}
	if (TMP613.status != 0) reraiseException();
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, readline_149277)(Streamobj148227* s) {
	NimStringDesc* result;
	nimfr("readLine", "streams.nim")
	result = 0;
	nimln(288, "streams.nim");
	result = copyString(((NimStringDesc*) &TMP614));
	{
		nimln(289, "streams.nim");
		while (1) {
			NIM_CHAR c;
			nimln(290, "streams.nim");
			c = readchar_148584(s);
			nimln(291, "streams.nim");
			{
				if (!((NU8)(c) == (NU8)(13))) goto LA5;
				nimln(292, "streams.nim");
				c = readchar_148584(s);
				nimln(293, "streams.nim");
				goto LA1;
			}
			LA5: ;
			nimln(294, "streams.nim");
			{
				NIM_BOOL LOC9;
				LOC9 = 0;
				LOC9 = ((NU8)(c) == (NU8)(10));
				if (LOC9) goto LA10;
				LOC9 = ((NU8)(c) == (NU8)(0));
				LA10: ;
				if (!LOC9) goto LA11;
				nimln(295, "streams.nim");
				goto LA1;
			}
			goto LA7;
			LA11: ;
			{
				nimln(297, "streams.nim");
				result = addChar(result, c);
			}
			LA7: ;
		}
	} LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, peekline_149297)(Streamobj148227* s) {
	NimStringDesc* volatile result;
	NI pos;
	TSafePoint TMP615;
	nimfr("peekLine", "streams.nim")
	result = 0;
	nimln(302, "streams.nim");
	pos = getposition_148359(s);
	nimln(303, "streams.nim");
	pushSafePoint(&TMP615);
	TMP615.status = setjmp(TMP615.context);
	if (TMP615.status == 0) {
		nimln(304, "streams.nim");
		result = readline_149277(s);
		popSafePoint();
	}
	else {
		popSafePoint();
		setFrame((TFrame*)&FR);
	}
	{
		nimln(303, "streams.nim");
		setposition_148338(s, pos);
	}
	if (TMP615.status != 0) reraiseException();
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, ssatend_149322)(Streamobj148227* s_149324) {
	NIM_BOOL result;
	Stringstreamobj149311* s;
	nimfr("ssAtEnd", "streams.nim")
{	result = 0;
	nimln(315, "streams.nim");
	if (s_149324) chckObj((*s_149324).Sup.m_type, (&NTI149311));
	s = ((Stringstreamobj149311*) (s_149324));
	nimln(316, "streams.nim");
	nimln(353, "system.nim");
	nimln(316, "streams.nim");
	result = (((*s).data ? (*s).data->Sup.len : 0) <= (*s).pos);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, sssetposition_149333)(Streamobj148227* s_149335, NI pos) {
	Stringstreamobj149311* s;
	nimfr("ssSetPosition", "streams.nim")
	nimln(319, "streams.nim");
	if (s_149335) chckObj((*s_149335).Sup.m_type, (&NTI149311));
	s = ((Stringstreamobj149311*) (s_149335));
	nimln(320, "streams.nim");
	(*s).pos = clamp_149339(pos, ((NI) 0), ((*s).data ? (*s).data->Sup.len : 0));
	popFrame();
}

N_NIMCALL(NI, ssgetposition_149358)(Streamobj148227* s_149360) {
	NI result;
	Stringstreamobj149311* s;
	nimfr("ssGetPosition", "streams.nim")
{	result = 0;
	nimln(323, "streams.nim");
	if (s_149360) chckObj((*s_149360).Sup.m_type, (&NTI149311));
	s = ((Stringstreamobj149311*) (s_149360));
	nimln(324, "streams.nim");
	result = (*s).pos;
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

N_NIMCALL(NI, ssreaddata_149369)(Streamobj148227* s_149371, void* buffer, NI buflen) {
	NI result;
	Stringstreamobj149311* s;
	NI TMP618;
	nimfr("ssReadData", "streams.nim")
	result = 0;
	nimln(327, "streams.nim");
	if (s_149371) chckObj((*s_149371).Sup.m_type, (&NTI149311));
	s = ((Stringstreamobj149311*) (s_149371));
	nimln(328, "streams.nim");
	TMP618 = subInt(((*s).data ? (*s).data->Sup.len : 0), (*s).pos);
	result = ((buflen <= (NI)(TMP618)) ? buflen : (NI)(TMP618));
	nimln(329, "streams.nim");
	{
		NI TMP619;
		nimln(357, "system.nim");
		if (!(((NI) 0) < result)) goto LA3;
		nimln(330, "streams.nim");
		if ((NU)((*s).pos) > (NU)((*s).data->Sup.len)) raiseIndexError();
		memcpy(buffer, ((void*) ((&(*s).data->data[(*s).pos]))), ((NI)chckRange(result, ((NI) 0), ((NI) IL64(9223372036854775807)))));
		nimln(331, "streams.nim");
		TMP619 = addInt((*s).pos, result);
		(*s).pos = (NI)(TMP619);
	}
	LA3: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, sspeekdata_149396)(Streamobj148227* s_149398, void* buffer, NI buflen) {
	NI result;
	Stringstreamobj149311* s;
	NI TMP620;
	nimfr("ssPeekData", "streams.nim")
	result = 0;
	nimln(334, "streams.nim");
	if (s_149398) chckObj((*s_149398).Sup.m_type, (&NTI149311));
	s = ((Stringstreamobj149311*) (s_149398));
	nimln(335, "streams.nim");
	TMP620 = subInt(((*s).data ? (*s).data->Sup.len : 0), (*s).pos);
	result = ((buflen <= (NI)(TMP620)) ? buflen : (NI)(TMP620));
	nimln(336, "streams.nim");
	{
		nimln(357, "system.nim");
		if (!(((NI) 0) < result)) goto LA3;
		nimln(337, "streams.nim");
		if ((NU)((*s).pos) > (NU)((*s).data->Sup.len)) raiseIndexError();
		memcpy(buffer, ((void*) ((&(*s).data->data[(*s).pos]))), ((NI)chckRange(result, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	}
	LA3: ;
	popFrame();
	return result;
}

N_NIMCALL(void, sswritedata_149414)(Streamobj148227* s_149416, void* buffer, NI buflen) {
	Stringstreamobj149311* s;
	NI TMP623;
	nimfr("ssWriteData", "streams.nim")
{	nimln(340, "streams.nim");
	if (s_149416) chckObj((*s_149416).Sup.m_type, (&NTI149311));
	s = ((Stringstreamobj149311*) (s_149416));
	nimln(341, "streams.nim");
	{
		if (!(buflen <= ((NI) 0))) goto LA3;
		nimln(342, "streams.nim");
		goto BeforeRet;
	}
	LA3: ;
	nimln(343, "streams.nim");
	{
		NI TMP621;
		NI TMP622;
		nimln(357, "system.nim");
		nimln(343, "streams.nim");
		TMP621 = addInt((*s).pos, buflen);
		if (!(((*s).data ? (*s).data->Sup.len : 0) < (NI)(TMP621))) goto LA7;
		nimln(344, "streams.nim");
		TMP622 = addInt((*s).pos, buflen);
		(*s).data = setLengthStr((*s).data, ((NI)chckRange((NI)(TMP622), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	}
	LA7: ;
	nimln(345, "streams.nim");
	if ((NU)((*s).pos) > (NU)((*s).data->Sup.len)) raiseIndexError();
	memcpy(((void*) ((&(*s).data->data[(*s).pos]))), buffer, ((NI)chckRange(buflen, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln(346, "streams.nim");
	TMP623 = addInt((*s).pos, buflen);
	(*s).pos = (NI)(TMP623);
	}BeforeRet: ;
	popFrame();
}

N_NIMCALL(void, ssclose_149436)(Streamobj148227* s_149438) {
	Stringstreamobj149311* s;
	NimStringDesc* LOC1;
	nimfr("ssClose", "streams.nim")
	nimln(349, "streams.nim");
	if (s_149438) chckObj((*s_149438).Sup.m_type, (&NTI149311));
	s = ((Stringstreamobj149311*) (s_149438));
	nimln(350, "streams.nim");
	LOC1 = 0;
	LOC1 = (*s).data; (*s).data = copyStringRC1(NIM_NIL);
	if (LOC1) nimGCunrefNoCycle(LOC1);
	popFrame();
}
N_NIMCALL(void, TMP624)(void* p, NI op) {
	Stringstreamobj149311* a;
	a = (Stringstreamobj149311*)p;
	nimGCvisit((void*)(*a).data, op);
}

N_NIMCALL(Stringstreamobj149311*, newstringstream_149446)(NimStringDesc* s) {
	Stringstreamobj149311* result;
	NimStringDesc* LOC1;
	nimfr("newStringStream", "streams.nim")
	result = 0;
	nimln(354, "streams.nim");
	result = (Stringstreamobj149311*) newObj((&NTI149309), sizeof(Stringstreamobj149311));
	(*result).Sup.Sup.m_type = (&NTI149311);
	nimln(355, "streams.nim");
	LOC1 = 0;
	LOC1 = (*result).data; (*result).data = copyStringRC1(s);
	if (LOC1) nimGCunrefNoCycle(LOC1);
	nimln(356, "streams.nim");
	(*result).pos = ((NI) 0);
	nimln(357, "streams.nim");
	(*result).Sup.closeimpl = ssclose_149436;
	nimln(358, "streams.nim");
	(*result).Sup.atendimpl = ssatend_149322;
	nimln(359, "streams.nim");
	(*result).Sup.setpositionimpl = sssetposition_149333;
	nimln(360, "streams.nim");
	(*result).Sup.getpositionimpl = ssgetposition_149358;
	nimln(361, "streams.nim");
	(*result).Sup.readdataimpl = ssreaddata_149369;
	nimln(362, "streams.nim");
	(*result).Sup.peekdataimpl = sspeekdata_149396;
	nimln(363, "streams.nim");
	(*result).Sup.writedataimpl = sswritedata_149414;
	popFrame();
	return result;
}

N_NIMCALL(void, fsclose_149471)(Streamobj148227* s) {
	nimfr("fsClose", "streams.nim")
	nimln(374, "streams.nim");
	{
		nimln(349, "system.nim");
		if (s) chckObj((*s).Sup.m_type, (&NTI149467));
		if (!!(((*((Filestreamobj149467*) (s))).f == NIM_NIL))) goto LA3;
		nimln(375, "streams.nim");
		if (s) chckObj((*s).Sup.m_type, (&NTI149467));
		fclose((*((Filestreamobj149467*) (s))).f);
		nimln(376, "streams.nim");
		if (s) chckObj((*s).Sup.m_type, (&NTI149467));
		(*((Filestreamobj149467*) (s))).f = NIM_NIL;
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(void, fsflush_149489)(Streamobj148227* s) {
	nimfr("fsFlush", "streams.nim")
	nimln(377, "streams.nim");
	if (s) chckObj((*s).Sup.m_type, (&NTI149467));
	fflush((*((Filestreamobj149467*) (s))).f);
	popFrame();
}

N_NIMCALL(NIM_BOOL, fsatend_149495)(Streamobj148227* s) {
	NIM_BOOL result;
	nimfr("fsAtEnd", "streams.nim")
{	result = 0;
	nimln(378, "streams.nim");
	if (s) chckObj((*s).Sup.m_type, (&NTI149467));
	result = endoffile_16860((*((Filestreamobj149467*) (s))).f);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, fssetposition_149502)(Streamobj148227* s, NI pos) {
	nimfr("fsSetPosition", "streams.nim")
	nimln(379, "streams.nim");
	if (s) chckObj((*s).Sup.m_type, (&NTI149467));
	setfilepos_16987((*((Filestreamobj149467*) (s))).f, ((NI64) (pos)));
	popFrame();
}

N_NIMCALL(NI, fsgetposition_149509)(Streamobj148227* s) {
	NI result;
	NI64 LOC1;
	nimfr("fsGetPosition", "streams.nim")
{	result = 0;
	nimln(380, "streams.nim");
	if (s) chckObj((*s).Sup.m_type, (&NTI149467));
	LOC1 = 0;
	LOC1 = getfilepos_16991((*((Filestreamobj149467*) (s))).f);
	result = ((NI) (LOC1));
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, fsreaddata_149517)(Streamobj148227* s, void* buffer, NI buflen) {
	NI result;
	nimfr("fsReadData", "streams.nim")
	result = 0;
	nimln(383, "streams.nim");
	if (s) chckObj((*s).Sup.m_type, (&NTI149467));
	result = readbuffer_16960((*((Filestreamobj149467*) (s))).f, buffer, ((NI)chckRange(buflen, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	popFrame();
	return result;
}

N_NIMCALL(NI, fspeekdata_149526)(Streamobj148227* s, void* buffer, NI buflen) {
	NI volatile result;
	NI pos;
	TSafePoint TMP625;
	nimfr("fsPeekData", "streams.nim")
	result = 0;
	nimln(386, "streams.nim");
	pos = fsgetposition_149509(s);
	nimln(387, "streams.nim");
	pushSafePoint(&TMP625);
	TMP625.status = setjmp(TMP625.context);
	if (TMP625.status == 0) {
		nimln(388, "streams.nim");
		if (s) chckObj((*s).Sup.m_type, (&NTI149467));
		result = readbuffer_16960((*((Filestreamobj149467*) (s))).f, buffer, ((NI)chckRange(buflen, ((NI) 0), ((NI) IL64(9223372036854775807)))));
		popSafePoint();
	}
	else {
		popSafePoint();
		setFrame((TFrame*)&FR);
	}
	{
		nimln(387, "streams.nim");
		fssetposition_149502(s, pos);
	}
	if (TMP625.status != 0) reraiseException();
	popFrame();
	return result;
}

N_NIMCALL(void, fswritedata_149536)(Streamobj148227* s, void* buffer, NI buflen) {
	nimfr("fsWriteData", "streams.nim")
	nimln(391, "streams.nim");
	{
		NI LOC3;
		Ioerror4031* LOC6;
		nimln(349, "system.nim");
		nimln(391, "streams.nim");
		if (s) chckObj((*s).Sup.m_type, (&NTI149467));
		LOC3 = 0;
		LOC3 = writebuffer_16982((*((Filestreamobj149467*) (s))).f, buffer, ((NI)chckRange(buflen, ((NI) 0), ((NI) IL64(9223372036854775807)))));
		if (!!((LOC3 == buflen))) goto LA4;
		nimln(392, "streams.nim");
		LOC6 = 0;
		LOC6 = neweio_148205(((NimStringDesc*) &TMP626));
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}
N_NIMCALL(void, TMP627)(void* p, NI op) {
	Filestreamobj149467* a;
	a = (Filestreamobj149467*)p;
}

N_NIMCALL(Filestreamobj149467*, newfilestream_149544)(FILE* f) {
	Filestreamobj149467* result;
	nimfr("newFileStream", "streams.nim")
	result = 0;
	nimln(396, "streams.nim");
	result = (Filestreamobj149467*) newObj((&NTI149465), sizeof(Filestreamobj149467));
	(*result).Sup.Sup.m_type = (&NTI149467);
	nimln(397, "streams.nim");
	(*result).f = f;
	nimln(398, "streams.nim");
	(*result).Sup.closeimpl = fsclose_149471;
	nimln(399, "streams.nim");
	(*result).Sup.atendimpl = fsatend_149495;
	nimln(400, "streams.nim");
	(*result).Sup.setpositionimpl = fssetposition_149502;
	nimln(401, "streams.nim");
	(*result).Sup.getpositionimpl = fsgetposition_149509;
	nimln(402, "streams.nim");
	(*result).Sup.readdataimpl = fsreaddata_149517;
	nimln(403, "streams.nim");
	(*result).Sup.peekdataimpl = fspeekdata_149526;
	nimln(404, "streams.nim");
	(*result).Sup.writedataimpl = fswritedata_149536;
	nimln(405, "streams.nim");
	(*result).Sup.flushimpl = fsflush_149489;
	popFrame();
	return result;
}

N_NIMCALL(Filestreamobj149467*, newfilestream_149559)(NimStringDesc* filename, NU8 mode) {
	Filestreamobj149467* result;
	FILE* f;
	nimfr("newFileStream", "streams.nim")
	result = 0;
	f = 0;
	nimln(412, "streams.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = open_16803(&f, filename, mode, ((NI) -1));
		if (!LOC3) goto LA4;
		result = newfilestream_149544(f);
	}
	LA4: ;
	popFrame();
	return result;
}
N_NIMCALL(void, TMP646)(void* p, NI op) {
	Streamobj148227* a;
	a = (Streamobj148227*)p;
}
NIM_EXTERNC N_NOINLINE(void, HEX00_streamsInit000)(void) {
	nimfr("streams", "streams.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, HEX00_streamsDatInit000)(void) {
static TNimNode* TMP616[8];
static TNimNode* TMP617[2];
static TNimNode TMP604[13];
NTI148227.size = sizeof(Streamobj148227);
NTI148227.kind = 17;
NTI148227.base = (&NTI4011);
NTI148227.flags = 1;
TMP616[0] = &TMP604[1];
NTI148228.size = sizeof(TY148228);
NTI148228.kind = 25;
NTI148228.base = 0;
NTI148228.flags = 3;
TMP604[1].kind = 1;
TMP604[1].offset = offsetof(Streamobj148227, closeimpl);
TMP604[1].typ = (&NTI148228);
TMP604[1].name = "closeImpl";
TMP616[1] = &TMP604[2];
NTI148232.size = sizeof(TY148232);
NTI148232.kind = 25;
NTI148232.base = 0;
NTI148232.flags = 3;
TMP604[2].kind = 1;
TMP604[2].offset = offsetof(Streamobj148227, atendimpl);
TMP604[2].typ = (&NTI148232);
TMP604[2].name = "atEndImpl";
TMP616[2] = &TMP604[3];
NTI148236.size = sizeof(TY148236);
NTI148236.kind = 25;
NTI148236.base = 0;
NTI148236.flags = 3;
TMP604[3].kind = 1;
TMP604[3].offset = offsetof(Streamobj148227, setpositionimpl);
TMP604[3].typ = (&NTI148236);
TMP604[3].name = "setPositionImpl";
TMP616[3] = &TMP604[4];
NTI148241.size = sizeof(TY148241);
NTI148241.kind = 25;
NTI148241.base = 0;
NTI148241.flags = 3;
TMP604[4].kind = 1;
TMP604[4].offset = offsetof(Streamobj148227, getpositionimpl);
TMP604[4].typ = (&NTI148241);
TMP604[4].name = "getPositionImpl";
TMP616[4] = &TMP604[5];
NTI148245.size = sizeof(TY148245);
NTI148245.kind = 25;
NTI148245.base = 0;
NTI148245.flags = 3;
TMP604[5].kind = 1;
TMP604[5].offset = offsetof(Streamobj148227, readdataimpl);
TMP604[5].typ = (&NTI148245);
TMP604[5].name = "readDataImpl";
TMP616[5] = &TMP604[6];
NTI148251.size = sizeof(TY148251);
NTI148251.kind = 25;
NTI148251.base = 0;
NTI148251.flags = 3;
TMP604[6].kind = 1;
TMP604[6].offset = offsetof(Streamobj148227, peekdataimpl);
TMP604[6].typ = (&NTI148251);
TMP604[6].name = "peekDataImpl";
TMP616[6] = &TMP604[7];
NTI148257.size = sizeof(TY148257);
NTI148257.kind = 25;
NTI148257.base = 0;
NTI148257.flags = 3;
TMP604[7].kind = 1;
TMP604[7].offset = offsetof(Streamobj148227, writedataimpl);
TMP604[7].typ = (&NTI148257);
TMP604[7].name = "writeDataImpl";
TMP616[7] = &TMP604[8];
NTI148263.size = sizeof(TY148263);
NTI148263.kind = 25;
NTI148263.base = 0;
NTI148263.flags = 3;
TMP604[8].kind = 1;
TMP604[8].offset = offsetof(Streamobj148227, flushimpl);
TMP604[8].typ = (&NTI148263);
TMP604[8].name = "flushImpl";
TMP604[0].len = 8; TMP604[0].kind = 2; TMP604[0].sons = &TMP616[0];
NTI148227.node = &TMP604[0];
NTI149311.size = sizeof(Stringstreamobj149311);
NTI149311.kind = 17;
NTI149311.base = (&NTI148227);
TMP617[0] = &TMP604[10];
TMP604[10].kind = 1;
TMP604[10].offset = offsetof(Stringstreamobj149311, data);
TMP604[10].typ = (&NTI149);
TMP604[10].name = "data";
TMP617[1] = &TMP604[11];
TMP604[11].kind = 1;
TMP604[11].offset = offsetof(Stringstreamobj149311, pos);
TMP604[11].typ = (&NTI108);
TMP604[11].name = "pos";
TMP604[9].len = 2; TMP604[9].kind = 2; TMP604[9].sons = &TMP617[0];
NTI149311.node = &TMP604[9];
NTI149309.size = sizeof(Stringstreamobj149311*);
NTI149309.kind = 22;
NTI149309.base = (&NTI149311);
NTI149309.marker = TMP624;
NTI149467.size = sizeof(Filestreamobj149467);
NTI149467.kind = 17;
NTI149467.base = (&NTI148227);
NTI149467.flags = 1;
TMP604[12].kind = 1;
TMP604[12].offset = offsetof(Filestreamobj149467, f);
TMP604[12].typ = (&NTI16404);
TMP604[12].name = "f";
NTI149467.node = &TMP604[12];
NTI149465.size = sizeof(Filestreamobj149467*);
NTI149465.kind = 22;
NTI149465.base = (&NTI149467);
NTI149465.marker = TMP627;
NTI148225.size = sizeof(Streamobj148227*);
NTI148225.kind = 22;
NTI148225.base = (&NTI148227);
NTI148225.marker = TMP646;
}

