/* Generated by Nim Compiler v0.12.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nim -o /home/marco/saus/advent-of-code-2019/17.nim/nimcache/strtabs.o /home/marco/saus/advent-of-code-2019/17.nim/nimcache/strtabs.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
typedef struct Stringtableobj145212 Stringtableobj145212;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Keyvaluepairseq145210 Keyvaluepairseq145210;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TY109772 TY109772;
typedef struct Keyerror4051 Keyerror4051;
typedef struct Valueerror4049 Valueerror4049;
typedef struct Exception Exception;
typedef struct Cell49347 Cell49347;
typedef struct Cellseq49363 Cellseq49363;
typedef struct Gcheap51418 Gcheap51418;
typedef struct Gcstack51416 Gcstack51416;
typedef struct Cellset49359 Cellset49359;
typedef struct Pagedesc49355 Pagedesc49355;
typedef struct Memregion31291 Memregion31291;
typedef struct Smallchunk31243 Smallchunk31243;
typedef struct Llchunk31285 Llchunk31285;
typedef struct Bigchunk31245 Bigchunk31245;
typedef struct Intset31217 Intset31217;
typedef struct Trunk31213 Trunk31213;
typedef struct Avlnode31289 Avlnode31289;
typedef struct Gcstat51414 Gcstat51414;
typedef struct Slice90857 Slice90857;
typedef struct Basechunk31241 Basechunk31241;
typedef struct Freecell31233 Freecell31233;
typedef N_NIMCALL_PTR(void, TY3889) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3894) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3889 marker;
TY3894 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Stringtableobj145212  {
  TNimObject Sup;
NI counter;
Keyvaluepairseq145210* data;
NU8 mode;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct TY109772 {
NimStringDesc* Field0;
NimStringDesc* Field1;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  Valueerror4049  {
  Exception Sup;
};
struct  Keyerror4051  {
  Valueerror4049 Sup;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Cell49347  {
NI refcount;
TNimType* typ;
};
struct  Cellseq49363  {
NI len;
NI cap;
Cell49347** d;
};
struct  Cellset49359  {
NI counter;
NI max;
Pagedesc49355* head;
Pagedesc49355** data;
};
typedef Smallchunk31243* TY31306[512];
typedef Trunk31213* Trunkbuckets31215[256];
struct  Intset31217  {
Trunkbuckets31215 data;
};
struct  Memregion31291  {
NI minlargeobj;
NI maxlargeobj;
TY31306 freesmallchunks;
Llchunk31285* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk31245* freechunkslist;
Intset31217 chunkstarts;
Avlnode31289* root;
Avlnode31289* deleted;
Avlnode31289* last;
Avlnode31289* freeavlnodes;
};
struct  Gcstat51414  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Gcheap51418  {
Gcstack51416* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq49363 zct;
Cellseq49363 decstack;
Cellset49359 cycleroots;
Cellseq49363 tempstack;
NI recgclock;
Memregion31291 region;
Gcstat51414 stat;
};
struct  Slice90857  {
NI a;
NI b;
};
typedef NU8 TY82458[32];
struct  Gcstack51416  {
Gcstack51416* prev;
Gcstack51416* next;
void* starts;
void* pos;
NI maxstacksize;
};
typedef NI TY31222[8];
struct  Pagedesc49355  {
Pagedesc49355* next;
NI key;
TY31222 bits;
};
struct  Basechunk31241  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk31243  {
  Basechunk31241 Sup;
Smallchunk31243* next;
Smallchunk31243* prev;
Freecell31233* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk31285  {
NI size;
NI acc;
Llchunk31285* next;
};
struct  Bigchunk31245  {
  Basechunk31241 Sup;
Bigchunk31245* next;
Bigchunk31245* prev;
NI align;
NF data;
};
struct  Trunk31213  {
Trunk31213* next;
NI key;
TY31222 bits;
};
typedef Avlnode31289* TY31296[2];
struct  Avlnode31289  {
TY31296 link;
NI key;
NI upperbound;
NI level;
};
struct  Freecell31233  {
Freecell31233* next;
NI zerofield;
};
struct Keyvaluepairseq145210 {
  TGenericSeq Sup;
  TY109772 data[SEQ_DECL_SIZE];
};
N_NIMCALL(NI, nstlen)(Stringtableobj145212* t);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_23601)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NI, myhash_145377)(Stringtableobj145212* t, NimStringDesc* key);
N_NIMCALL(NI, hash_142851)(NimStringDesc* x);
N_NIMCALL(NI, hashignorecase_143139)(NimStringDesc* x);
N_NIMCALL(NI, hashignorestyle_142948)(NimStringDesc* x);
N_NIMCALL(NIM_BOOL, mycmp_145390)(Stringtableobj145212* t, NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(NI, cmp_6577)(NimStringDesc* x, NimStringDesc* y);
N_NIMCALL(NI, nsuCmpIgnoreCase)(NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(NI, nsuCmpIgnoreStyle)(NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(NIM_BOOL, mustrehash_145402)(NI length, NI counter);
N_NIMCALL(void, failedassertimpl_91603)(NimStringDesc* msg);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, nexttry_145607)(NI h, NI maxhash);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NIMCALL(NI, rawget_145618)(Stringtableobj145212* t, NimStringDesc* key);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(NimStringDesc**, nstTake)(Stringtableobj145212* t, NimStringDesc* key);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(Cell49347*, usrtocell_53046)(void* usr);
static N_INLINE(void, rtladdzct_54604)(Cell49347* c);
N_NOINLINE(void, addzct_53017)(Cellseq49363* s, Cell49347* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_NIMCALL(NimStringDesc**, mget_145820)(Stringtableobj145212* t, NimStringDesc* key);
N_NIMCALL(NimStringDesc*, getordefault_146020)(Stringtableobj145212* t, NimStringDesc* key);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(NIM_BOOL, nsthasKey)(Stringtableobj145212* t, NimStringDesc* key);
N_NIMCALL(void, rawinsert_146043)(Stringtableobj145212* t, Keyvaluepairseq145210** data, NimStringDesc* key, NimStringDesc* val);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
N_NIMCALL(void, enlarge_146065)(Stringtableobj145212* t);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP568)(void* p, NI op);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(void, nstPut)(Stringtableobj145212* t, NimStringDesc* key, NimStringDesc* val);
N_NIMCALL(void, raiseformatexception_146165)(NimStringDesc* s);
N_NIMCALL(NimStringDesc*, getvalue_146185)(Stringtableobj145212* t, NU8 flags, NimStringDesc* key);
N_NIMCALL(NimStringDesc*, getenv_132044)(NimStringDesc* key);
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c);
N_NIMCALL(Stringtableobj145212*, nstnewStringTable)(NU8 mode);
N_NIMCALL(void, TMP580)(void* p, NI op);
N_NIMCALL(void*, newSeqRC1)(TNimType* typ, NI len);
N_NIMCALL(void, clear_146257)(Stringtableobj145212* s, NU8 mode);
N_NIMCALL(TGenericSeq*, setLengthSeq)(TGenericSeq* seq, NI elemsize, NI newlen);
static N_INLINE(Slice90857, HEX2EHEX2E_105291)(NI a, NI b);
N_NIMCALL(Stringtableobj145212*, nstnewStringTableWithPairs)(NimStringDesc** keyvaluepairs, NI keyvaluepairsLen0, NU8 mode);
N_NIMCALL(Stringtableobj145212*, nstnewStringTableWithTableConstr)(TY109772* keyvaluepairs, NI keyvaluepairsLen0, NU8 mode);
N_NIMCALL(NimStringDesc*, nstFormat)(NimStringDesc* f, Stringtableobj145212* t, NU8 flags);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start_81416, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_NIMCALL(NimStringDesc*, nstDollar)(Stringtableobj145212* t);
STRING_LITERAL(TMP557, "\012  counter < length ", 20);
STRING_LITERAL(TMP564, "key not found: ", 15);
STRING_LITERAL(TMP565, "", 0);
STRING_LITERAL(TMP571, "format string: key not found: ", 30);
NIM_CONST TY82458 Patternchars_146442 = {
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFF, 0x03,
0xFE, 0xFF, 0xFF, 0x87, 0xFE, 0xFF, 0xFF, 0x07,
0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF}
;
STRING_LITERAL(TMP598, "{:}", 3);
STRING_LITERAL(TMP599, "{", 1);
STRING_LITERAL(TMP600, ", ", 2);
STRING_LITERAL(TMP601, ": ", 2);
STRING_LITERAL(TMP603, "}", 1);
extern TFrame* frameptr_20842;
extern TNimType NTI145804; /* ref KeyError */
extern TNimType NTI4051; /* KeyError */
extern Gcheap51418 gch_51459;
extern TNimType NTI109772; /* tuple[nonDST: string, DST: string] */
TNimType NTI145210; /* KeyValuePairSeq */
extern TNimType NTI25428; /* ref ValueError */
extern TNimType NTI4049; /* ValueError */
extern TNimType NTI4011; /* RootObj */
TNimType NTI145212; /* StringTableObj */
extern TNimType NTI108; /* int */
TNimType NTI145206; /* StringTableMode */
TNimType NTI145214; /* StringTableRef */

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_20842 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_20842).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_20842;
	frameptr_20842 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_23601();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_20842 = (*frameptr_20842).prev;
}

N_NIMCALL(NI, nstlen)(Stringtableobj145212* t) {
	NI result;
	nimfr("len", "strtabs.nim")
	result = 0;
	nimln(39, "strtabs.nim");
	result = (*t).counter;
	popFrame();
	return result;
}

N_NIMCALL(NI, myhash_145377)(Stringtableobj145212* t, NimStringDesc* key) {
	NI result;
	nimfr("myhash", "strtabs.nim")
	result = 0;
	nimln(78, "strtabs.nim");
	switch ((*t).mode) {
	case ((NU8) 0):
	{
		nimln(79, "strtabs.nim");
		result = hash_142851(key);
	}
	break;
	case ((NU8) 1):
	{
		nimln(80, "strtabs.nim");
		result = hashignorecase_143139(key);
	}
	break;
	case ((NU8) 2):
	{
		nimln(81, "strtabs.nim");
		result = hashignorestyle_142948(key);
	}
	break;
	}
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, mycmp_145390)(Stringtableobj145212* t, NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	nimfr("myCmp", "strtabs.nim")
	result = 0;
	nimln(84, "strtabs.nim");
	switch ((*t).mode) {
	case ((NU8) 0):
	{
		NI LOC2;
		nimln(85, "strtabs.nim");
		LOC2 = 0;
		LOC2 = cmp_6577(a, b);
		result = (LOC2 == ((NI) 0));
	}
	break;
	case ((NU8) 1):
	{
		NI LOC4;
		nimln(86, "strtabs.nim");
		LOC4 = 0;
		LOC4 = nsuCmpIgnoreCase(a, b);
		result = (LOC4 == ((NI) 0));
	}
	break;
	case ((NU8) 2):
	{
		NI LOC6;
		nimln(87, "strtabs.nim");
		LOC6 = 0;
		LOC6 = nsuCmpIgnoreStyle(a, b);
		result = (LOC6 == ((NI) 0));
	}
	break;
	}
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

N_NIMCALL(NIM_BOOL, mustrehash_145402)(NI length, NI counter) {
	NIM_BOOL result;
	NIM_BOOL LOC5;
	NI TMP558;
	NI TMP559;
	NI TMP560;
	nimfr("mustRehash", "strtabs.nim")
	result = 0;
	nimln(90, "strtabs.nim");
	{
		if (!!((counter < length))) goto LA3;
		failedassertimpl_91603(((NimStringDesc*) &TMP557));
	}
	LA3: ;
	nimln(91, "strtabs.nim");
	LOC5 = 0;
	TMP558 = mulInt(length, ((NI) 2));
	TMP559 = mulInt(counter, ((NI) 3));
	LOC5 = ((NI)(TMP558) < (NI)(TMP559));
	if (LOC5) goto LA6;
	TMP560 = subInt(length, counter);
	LOC5 = ((NI)(TMP560) < ((NI) 4));
	LA6: ;
	result = LOC5;
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, nexttry_145607)(NI h, NI maxhash) {
	NI result;
	NI TMP561;
	NI TMP562;
	nimfr("nextTry", "strtabs.nim")
	result = 0;
	nimln(94, "strtabs.nim");
	TMP561 = mulInt(((NI) 5), h);
	TMP562 = addInt((NI)(TMP561), ((NI) 1));
	result = (NI)((NI)(TMP562) & maxhash);
	popFrame();
	return result;
}

N_NIMCALL(NI, rawget_145618)(Stringtableobj145212* t, NimStringDesc* key) {
	NI result;
	NI h;
	NI LOC1;
	nimfr("rawGet", "strtabs.nim")
{	result = 0;
	nimln(97, "strtabs.nim");
	LOC1 = 0;
	LOC1 = myhash_145377(t, key);
	h = (NI)(LOC1 & ((*t).data ? ((*t).data->Sup.len-1) : -1));
	{
		nimln(98, "strtabs.nim");
		while (1) {
			if ((NU)(h) >= (NU)((*t).data->Sup.len)) raiseIndexError();
			if (!!((*t).data->data[h].Field0 == 0)) goto LA3;
			nimln(99, "strtabs.nim");
			{
				NIM_BOOL LOC6;
				if ((NU)(h) >= (NU)((*t).data->Sup.len)) raiseIndexError();
				LOC6 = 0;
				LOC6 = mycmp_145390(t, (*t).data->data[h].Field0, key);
				if (!LOC6) goto LA7;
				nimln(100, "strtabs.nim");
				result = h;
				goto BeforeRet;
			}
			LA7: ;
			nimln(101, "strtabs.nim");
			h = nexttry_145607(h, ((*t).data ? ((*t).data->Sup.len-1) : -1));
		} LA3: ;
	}
	nimln(102, "strtabs.nim");
	result = ((NI) -1);
	}BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI)((*src).Sup.len + ((NI) 1)));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(Cell49347*, usrtocell_53046)(void* usr) {
	Cell49347* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(131, "gc.nim");
	result = ((Cell49347*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell49347))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_54604)(Cell49347* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(212, "gc.nim");
	addzct_53017((&gch_51459.zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(264, "gc.nim");
	{
		Cell49347* c;
		nimln(349, "system.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(265, "gc.nim");
		c = usrtocell_53046(src);
		nimln(182, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3: ;
	nimln(267, "gc.nim");
	{
		Cell49347* c;
		nimln(349, "system.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(268, "gc.nim");
		c = usrtocell_53046((*dest));
		nimln(269, "gc.nim");
		{
			nimln(180, "gc.nim");
			(*c).refcount -= ((NI) 8);
			nimln(181, "gc.nim");
			if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA11;
			nimln(270, "gc.nim");
			rtladdzct_54604(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(271, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(NimStringDesc**, nstTake)(Stringtableobj145212* t, NimStringDesc* key) {
	NimStringDesc** result;
	NI index_145659;
	nimfr("[]", "strtabs.nim")
	result = 0;
	nimln(105, "strtabs.nim");
	index_145659 = rawget_145618(t, key);
	nimln(106, "strtabs.nim");
	{
		nimln(353, "system.nim");
		if (!(((NI) 0) <= index_145659)) goto LA3;
		nimln(106, "strtabs.nim");
		if ((NU)(index_145659) >= (NU)((*t).data->Sup.len)) raiseIndexError();
		result = (&(*t).data->data[index_145659].Field1);
	}
	goto LA1;
	LA3: ;
	{
		Keyerror4051* e_145803;
		NimStringDesc* LOC6;
		e_145803 = 0;
		nimln(2507, "system.nim");
		e_145803 = (Keyerror4051*) newObj((&NTI145804), sizeof(Keyerror4051));
		(*e_145803).Sup.Sup.Sup.m_type = (&NTI4051);
		nimln(2508, "system.nim");
		nimln(109, "strtabs.nim");
		LOC6 = 0;
		LOC6 = rawNewString(key->Sup.len + 15);
appendString(LOC6, ((NimStringDesc*) &TMP564));
appendString(LOC6, key);
		asgnRefNoCycle((void**) (&(*e_145803).Sup.Sup.message), LOC6);
		raiseException((Exception*)e_145803, "KeyError");
	}
	LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc**, mget_145820)(Stringtableobj145212* t, NimStringDesc* key) {
	NimStringDesc** result;
	NI index_145827;
	nimfr("mget", "strtabs.nim")
	result = 0;
	nimln(105, "strtabs.nim");
	index_145827 = rawget_145618(t, key);
	nimln(106, "strtabs.nim");
	{
		nimln(353, "system.nim");
		if (!(((NI) 0) <= index_145827)) goto LA3;
		nimln(106, "strtabs.nim");
		if ((NU)(index_145827) >= (NU)((*t).data->Sup.len)) raiseIndexError();
		result = (&(*t).data->data[index_145827].Field1);
	}
	goto LA1;
	LA3: ;
	{
		Keyerror4051* e_146003;
		NimStringDesc* LOC6;
		e_146003 = 0;
		nimln(2507, "system.nim");
		e_146003 = (Keyerror4051*) newObj((&NTI145804), sizeof(Keyerror4051));
		(*e_146003).Sup.Sup.Sup.m_type = (&NTI4051);
		nimln(2508, "system.nim");
		nimln(109, "strtabs.nim");
		LOC6 = 0;
		LOC6 = rawNewString(key->Sup.len + 15);
appendString(LOC6, ((NimStringDesc*) &TMP564));
appendString(LOC6, key);
		asgnRefNoCycle((void**) (&(*e_146003).Sup.Sup.message), LOC6);
		raiseException((Exception*)e_146003, "KeyError");
	}
	LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, getordefault_146020)(Stringtableobj145212* t, NimStringDesc* key) {
	NimStringDesc* result;
	NI index;
	nimfr("getOrDefault", "strtabs.nim")
	result = 0;
	nimln(126, "strtabs.nim");
	index = rawget_145618(t, key);
	nimln(127, "strtabs.nim");
	{
		nimln(353, "system.nim");
		if (!(((NI) 0) <= index)) goto LA3;
		nimln(127, "strtabs.nim");
		if ((NU)(index) >= (NU)((*t).data->Sup.len)) raiseIndexError();
		result = copyString((*t).data->data[index].Field1);
	}
	goto LA1;
	LA3: ;
	{
		nimln(128, "strtabs.nim");
		result = copyString(((NimStringDesc*) &TMP565));
	}
	LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, nsthasKey)(Stringtableobj145212* t, NimStringDesc* key) {
	NIM_BOOL result;
	NI LOC1;
	nimfr("hasKey", "strtabs.nim")
	result = 0;
	nimln(132, "strtabs.nim");
	nimln(353, "system.nim");
	nimln(132, "strtabs.nim");
	LOC1 = 0;
	LOC1 = rawget_145618(t, key);
	result = (((NI) 0) <= LOC1);
	popFrame();
	return result;
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	Cell49347* c;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(246, "gc.nim");
	c = usrtocell_53046(p);
	nimln(248, "gc.nim");
	{
		nimln(180, "gc.nim");
		(*c).refcount -= ((NI) 8);
		nimln(181, "gc.nim");
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3;
		nimln(249, "gc.nim");
		rtladdzct_54604(c);
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(void, rawinsert_146043)(Stringtableobj145212* t, Keyvaluepairseq145210** data, NimStringDesc* key, NimStringDesc* val) {
	NI h;
	NI LOC1;
	NimStringDesc* LOC4;
	NimStringDesc* LOC5;
	nimfr("rawInsert", "strtabs.nim")
	nimln(135, "strtabs.nim");
	LOC1 = 0;
	LOC1 = myhash_145377(t, key);
	h = (NI)(LOC1 & ((*data) ? ((*data)->Sup.len-1) : -1));
	{
		nimln(136, "strtabs.nim");
		while (1) {
			if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
			if (!!((*data)->data[h].Field0 == 0)) goto LA3;
			nimln(137, "strtabs.nim");
			h = nexttry_145607(h, ((*data) ? ((*data)->Sup.len-1) : -1));
		} LA3: ;
	}
	nimln(138, "strtabs.nim");
	if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
	LOC4 = 0;
	LOC4 = (*data)->data[h].Field0; (*data)->data[h].Field0 = copyStringRC1(key);
	if (LOC4) nimGCunrefNoCycle(LOC4);
	nimln(139, "strtabs.nim");
	if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
	LOC5 = 0;
	LOC5 = (*data)->data[h].Field1; (*data)->data[h].Field1 = copyStringRC1(val);
	if (LOC5) nimGCunrefNoCycle(LOC5);
	popFrame();
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (a <= i);
		if (!(LOC3)) goto LA4;
		LOC3 = (i <= b);
		LA4: ;
		if (!LOC3) goto LA5;
		result = i;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	}BeforeRet: ;
	return result;
}
N_NIMCALL(void, TMP568)(void* p, NI op) {
	Keyvaluepairseq145210* a;
	NI LOC1;
	a = (Keyvaluepairseq145210*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1].Field0, op);
	nimGCvisit((void*)a->data[LOC1].Field1, op);
	}
}

N_NIMCALL(void, enlarge_146065)(Stringtableobj145212* t) {
	Keyvaluepairseq145210* n;
	NI TMP566;
	Keyvaluepairseq145210* LOC8;
	nimfr("enlarge", "strtabs.nim")
	n = 0;
	nimln(143, "strtabs.nim");
	TMP566 = mulInt(((*t).data ? (*t).data->Sup.len : 0), ((NI) 2));
	n = (Keyvaluepairseq145210*) newSeq((&NTI145210), ((NI)chckRange((NI)(TMP566), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	{
		NI i_146099;
		NI HEX3Atmp_146113;
		NI res_146116;
		i_146099 = 0;
		HEX3Atmp_146113 = 0;
		nimln(144, "strtabs.nim");
		HEX3Atmp_146113 = ((*t).data ? ((*t).data->Sup.len-1) : -1);
		nimln(1874, "system.nim");
		res_146116 = ((NI) 0);
		{
			nimln(1875, "system.nim");
			while (1) {
				NI TMP569;
				if (!(res_146116 <= HEX3Atmp_146113)) goto LA3;
				nimln(1876, "system.nim");
				i_146099 = res_146116;
				nimln(145, "strtabs.nim");
				{
					if ((NU)(i_146099) >= (NU)((*t).data->Sup.len)) raiseIndexError();
					if (!!((*t).data->data[i_146099].Field0 == 0)) goto LA6;
					if ((NU)(i_146099) >= (NU)((*t).data->Sup.len)) raiseIndexError();
					if ((NU)(i_146099) >= (NU)((*t).data->Sup.len)) raiseIndexError();
					rawinsert_146043(t, (&n), (*t).data->data[i_146099].Field0, (*t).data->data[i_146099].Field1);
				}
				LA6: ;
				nimln(1890, "system.nim");
				TMP569 = addInt(res_146116, ((NI) 1));
				res_146116 = (NI)(TMP569);
			} LA3: ;
		}
	}
	nimln(146, "strtabs.nim");
	LOC8 = 0;
	LOC8 = (*t).data;
	asgnRefNoCycle((void**) (&(*t).data), n);
	n = LOC8;
	popFrame();
}

N_NIMCALL(void, nstPut)(Stringtableobj145212* t, NimStringDesc* key, NimStringDesc* val) {
	NI index;
	nimfr("[]=", "strtabs.nim")
	nimln(150, "strtabs.nim");
	index = rawget_145618(t, key);
	nimln(151, "strtabs.nim");
	{
		NimStringDesc* LOC5;
		nimln(353, "system.nim");
		if (!(((NI) 0) <= index)) goto LA3;
		nimln(152, "strtabs.nim");
		if ((NU)(index) >= (NU)((*t).data->Sup.len)) raiseIndexError();
		LOC5 = 0;
		LOC5 = (*t).data->data[index].Field1; (*t).data->data[index].Field1 = copyStringRC1(val);
		if (LOC5) nimGCunrefNoCycle(LOC5);
	}
	goto LA1;
	LA3: ;
	{
		NI TMP570;
		nimln(154, "strtabs.nim");
		{
			NIM_BOOL LOC9;
			LOC9 = 0;
			LOC9 = mustrehash_145402(((*t).data ? (*t).data->Sup.len : 0), (*t).counter);
			if (!LOC9) goto LA10;
			enlarge_146065(t);
		}
		LA10: ;
		nimln(155, "strtabs.nim");
		rawinsert_146043(t, (&(*t).data), key, val);
		nimln(156, "strtabs.nim");
		TMP570 = addInt((*t).counter, ((NI) 1));
		(*t).counter = (NI)(TMP570);
	}
	LA1: ;
	popFrame();
}

N_NIMCALL(void, raiseformatexception_146165)(NimStringDesc* s) {
	Valueerror4049* e;
	NimStringDesc* LOC1;
	nimfr("raiseFormatException", "strtabs.nim")
	e = 0;
	nimln(160, "strtabs.nim");
	e = (Valueerror4049*) newObj((&NTI25428), sizeof(Valueerror4049));
	(*e).Sup.Sup.m_type = (&NTI4049);
	nimln(161, "strtabs.nim");
	LOC1 = 0;
	LOC1 = rawNewString(s->Sup.len + 30);
appendString(LOC1, ((NimStringDesc*) &TMP571));
appendString(LOC1, s);
	asgnRefNoCycle((void**) (&(*e).Sup.message), LOC1);
	nimln(162, "strtabs.nim");
	raiseException((Exception*)e, "ValueError");
	popFrame();
}

static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c) {
	(*dest).data[((*dest).Sup.len)- 0] = c;
	(*dest).data[((NI)((*dest).Sup.len + ((NI) 1)))- 0] = 0;
	(*dest).Sup.len += ((NI) 1);
}

N_NIMCALL(NimStringDesc*, getvalue_146185)(Stringtableobj145212* t, NU8 flags, NimStringDesc* key) {
	NimStringDesc* result;
	nimfr("getValue", "strtabs.nim")
{	result = 0;
	nimln(165, "strtabs.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = nsthasKey(t, key);
		if (!LOC3) goto LA4;
		result = getordefault_146020(t, key);
		goto BeforeRet;
	}
	LA4: ;
	nimln(167, "strtabs.nim");
	{
		nimln(1098, "system.nim");
		if (!((flags &(1<<((((NU8) 0))&7)))!=0)) goto LA8;
		nimln(167, "strtabs.nim");
		result = getenv_132044(key);
	}
	goto LA6;
	LA8: ;
	{
		nimln(168, "strtabs.nim");
		result = copyString(((NimStringDesc*) &TMP565));
	}
	LA6: ;
	nimln(169, "strtabs.nim");
	{
		if (!((result ? result->Sup.len : 0) == ((NI) 0))) goto LA13;
		nimln(170, "strtabs.nim");
		{
			NimStringDesc* LOC19;
			nimln(1098, "system.nim");
			if (!((flags &(1<<((((NU8) 2))&7)))!=0)) goto LA17;
			nimln(170, "strtabs.nim");
			LOC19 = 0;
			LOC19 = rawNewString(key->Sup.len + 1);
appendChar(LOC19, 36);
appendString(LOC19, key);
			result = LOC19;
		}
		goto LA15;
		LA17: ;
		{
			nimln(1104, "system.nim");
			if (!!(((flags &(1<<((((NU8) 1))&7)))!=0))) goto LA21;
			nimln(171, "strtabs.nim");
			raiseformatexception_146165(key);
		}
		goto LA15;
		LA21: ;
		LA15: ;
	}
	LA13: ;
	}BeforeRet: ;
	popFrame();
	return result;
}
N_NIMCALL(void, TMP580)(void* p, NI op) {
	Stringtableobj145212* a;
	a = (Stringtableobj145212*)p;
	nimGCvisit((void*)(*a).data, op);
}

N_NIMCALL(Stringtableobj145212*, nstnewStringTable)(NU8 mode) {
	Stringtableobj145212* result;
	nimfr("newStringTable", "strtabs.nim")
	result = 0;
	nimln(176, "strtabs.nim");
	result = (Stringtableobj145212*) newObj((&NTI145214), sizeof(Stringtableobj145212));
	(*result).Sup.m_type = (&NTI145212);
	nimln(177, "strtabs.nim");
	(*result).mode = mode;
	nimln(178, "strtabs.nim");
	(*result).counter = ((NI) 0);
	nimln(179, "strtabs.nim");
	if ((*result).data) nimGCunrefNoCycle((*result).data);
	(*result).data = (Keyvaluepairseq145210*) newSeqRC1((&NTI145210), ((NI) 64));
	popFrame();
	return result;
}

static N_INLINE(Slice90857, HEX2EHEX2E_105291)(NI a, NI b) {
	Slice90857 result;
	nimfr("..", "system.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln(270, "system.nim");
	result.a = a;
	nimln(271, "system.nim");
	result.b = b;
	popFrame();
	return result;
}

N_NIMCALL(void, clear_146257)(Stringtableobj145212* s, NU8 mode) {
	nimfr("clear", "strtabs.nim")
	nimln(183, "strtabs.nim");
	(*s).mode = mode;
	nimln(184, "strtabs.nim");
	(*s).counter = ((NI) 0);
	nimln(185, "strtabs.nim");
	(*s).data = (Keyvaluepairseq145210*) setLengthSeq(&((*s).data)->Sup, sizeof(TY109772), ((NI) 64));
	{
		NI i_146305;
		Slice90857 HEX3Atmp_146307;
		i_146305 = 0;
		memset((void*)(&HEX3Atmp_146307), 0, sizeof(HEX3Atmp_146307));
		nimln(3552, "system.nim");
		nimln(3554, "system.nim");
		nimln(186, "strtabs.nim");
		HEX3Atmp_146307 = HEX2EHEX2E_105291(((NI) 0), subInt(((*s).data ? (*s).data->Sup.len : 0), 1));
		{
			NI x_146311;
			NI HEX3Atmp_146313;
			NI HEX3Atmp_146315;
			NI res_146317;
			x_146311 = 0;
			HEX3Atmp_146313 = 0;
			HEX3Atmp_146315 = 0;
			nimln(2026, "system.nim");
			HEX3Atmp_146313 = HEX3Atmp_146307.a;
			HEX3Atmp_146315 = HEX3Atmp_146307.b;
			nimln(1874, "system.nim");
			res_146317 = HEX3Atmp_146313;
			{
				nimln(1875, "system.nim");
				while (1) {
					NI TMP581;
					if (!(res_146317 <= HEX3Atmp_146315)) goto LA4;
					nimln(1876, "system.nim");
					x_146311 = res_146317;
					nimln(2026, "system.nim");
					i_146305 = x_146311;
					nimln(187, "strtabs.nim");
					{
						NimStringDesc* LOC9;
						if ((NU)(i_146305) >= (NU)((*s).data->Sup.len)) raiseIndexError();
						if (!!((*s).data->data[i_146305].Field0 == 0)) goto LA7;
						nimln(188, "strtabs.nim");
						if ((NU)(i_146305) >= (NU)((*s).data->Sup.len)) raiseIndexError();
						LOC9 = 0;
						LOC9 = (*s).data->data[i_146305].Field0; (*s).data->data[i_146305].Field0 = copyStringRC1(NIM_NIL);
						if (LOC9) nimGCunrefNoCycle(LOC9);
					}
					LA7: ;
					nimln(1895, "system.nim");
					TMP581 = addInt(res_146317, ((NI) 1));
					res_146317 = (NI)(TMP581);
				} LA4: ;
			}
		}
	}
	popFrame();
}

N_NIMCALL(Stringtableobj145212*, nstnewStringTableWithPairs)(NimStringDesc** keyvaluepairs, NI keyvaluepairsLen0, NU8 mode) {
	Stringtableobj145212* result;
	NI i;
	nimfr("newStringTable", "strtabs.nim")
	result = 0;
	nimln(197, "strtabs.nim");
	result = nstnewStringTable(mode);
	nimln(198, "strtabs.nim");
	i = ((NI) 0);
	{
		nimln(199, "strtabs.nim");
		while (1) {
			NI TMP582;
			NI TMP583;
			if (!(i < (keyvaluepairsLen0-1))) goto LA2;
			nimln(200, "strtabs.nim");
			if ((NU)(i) >= (NU)(keyvaluepairsLen0)) raiseIndexError();
			TMP582 = addInt(i, ((NI) 1));
			if ((NU)((NI)(TMP582)) >= (NU)(keyvaluepairsLen0)) raiseIndexError();
			nstPut(result, keyvaluepairs[i], keyvaluepairs[(NI)(TMP582)]);
			nimln(201, "strtabs.nim");
			TMP583 = addInt(i, ((NI) 2));
			i = (NI)(TMP583);
		} LA2: ;
	}
	popFrame();
	return result;
}

N_NIMCALL(Stringtableobj145212*, nstnewStringTableWithTableConstr)(TY109772* keyvaluepairs, NI keyvaluepairsLen0, NU8 mode) {
	Stringtableobj145212* result;
	nimfr("newStringTable", "strtabs.nim")
	result = 0;
	nimln(210, "strtabs.nim");
	result = nstnewStringTable(mode);
	{
		NimStringDesc* key_146412;
		NimStringDesc* val_146413;
		NI i_146417;
		key_146412 = 0;
		val_146413 = 0;
		nimln(1965, "system.nim");
		i_146417 = ((NI) 0);
		{
			nimln(1966, "system.nim");
			while (1) {
				NI TMP584;
				if (!(i_146417 < keyvaluepairsLen0)) goto LA3;
				nimln(1967, "system.nim");
				if ((NU)(i_146417) >= (NU)(keyvaluepairsLen0)) raiseIndexError();
				key_146412 = keyvaluepairs[i_146417].Field0;
				if ((NU)(i_146417) >= (NU)(keyvaluepairsLen0)) raiseIndexError();
				val_146413 = keyvaluepairs[i_146417].Field1;
				nimln(211, "strtabs.nim");
				nstPut(result, key_146412, val_146413);
				nimln(1968, "system.nim");
				TMP584 = addInt(i_146417, ((NI) 1));
				i_146417 = (NI)(TMP584);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, nstFormat)(NimStringDesc* f, Stringtableobj145212* t, NU8 flags) {
	NimStringDesc* result;
	NI i;
	nimfr("%", "strtabs.nim")
	result = 0;
	nimln(218, "strtabs.nim");
	result = copyString(((NimStringDesc*) &TMP565));
	nimln(219, "strtabs.nim");
	i = ((NI) 0);
	{
		nimln(220, "strtabs.nim");
		while (1) {
			if (!(i < (f ? f->Sup.len : 0))) goto LA2;
			nimln(221, "strtabs.nim");
			{
				NI TMP585;
				if ((NU)(i) > (NU)(f->Sup.len)) raiseIndexError();
				if (!((NU8)(f->data[i]) == (NU8)(36))) goto LA5;
				nimln(222, "strtabs.nim");
				TMP585 = addInt(i, ((NI) 1));
				if ((NU)((NI)(TMP585)) > (NU)(f->Sup.len)) raiseIndexError();
				switch (((NU8)(f->data[(NI)(TMP585)]))) {
				case 36:
				{
					NI TMP586;
					nimln(224, "strtabs.nim");
					result = addChar(result, 36);
					nimln(225, "strtabs.nim");
					TMP586 = addInt(i, ((NI) 2));
					i = (NI)(TMP586);
				}
				break;
				case 123:
				{
					NI j;
					NI TMP587;
					NI TMP589;
					NI TMP590;
					NimStringDesc* LOC13;
					NimStringDesc* LOC14;
					NI TMP591;
					nimln(227, "strtabs.nim");
					TMP587 = addInt(i, ((NI) 1));
					j = (NI)(TMP587);
					{
						nimln(228, "strtabs.nim");
						while (1) {
							NIM_BOOL LOC11;
							NI TMP588;
							LOC11 = 0;
							LOC11 = (j < (f ? f->Sup.len : 0));
							if (!(LOC11)) goto LA12;
							nimln(349, "system.nim");
							if ((NU)(j) > (NU)(f->Sup.len)) raiseIndexError();
							LOC11 = !(((NU8)(f->data[j]) == (NU8)(125)));
							LA12: ;
							if (!LOC11) goto LA10;
							nimln(228, "strtabs.nim");
							TMP588 = addInt(j, ((NI) 1));
							j = (NI)(TMP588);
						} LA10: ;
					}
					nimln(229, "strtabs.nim");
					TMP589 = addInt(i, ((NI) 2));
					TMP590 = subInt(j, ((NI) 1));
					LOC13 = 0;
					LOC13 = copyStrLast(f, (NI)(TMP589), (NI)(TMP590));
					LOC14 = 0;
					LOC14 = getvalue_146185(t, flags, LOC13);
					result = resizeString(result, LOC14->Sup.len + 0);
appendString(result, LOC14);
					nimln(230, "strtabs.nim");
					TMP591 = addInt(j, ((NI) 1));
					i = (NI)(TMP591);
				}
				break;
				case 97 ... 122:
				case 65 ... 90:
				case 128 ... 255:
				case 95:
				{
					NI j;
					NI TMP592;
					NI TMP594;
					NI TMP595;
					NimStringDesc* LOC20;
					NimStringDesc* LOC21;
					nimln(232, "strtabs.nim");
					TMP592 = addInt(i, ((NI) 1));
					j = (NI)(TMP592);
					{
						nimln(233, "strtabs.nim");
						while (1) {
							NIM_BOOL LOC18;
							NI TMP593;
							LOC18 = 0;
							LOC18 = (j < (f ? f->Sup.len : 0));
							if (!(LOC18)) goto LA19;
							nimln(1098, "system.nim");
							if ((NU)(j) > (NU)(f->Sup.len)) raiseIndexError();
							LOC18 = (((NU8)(f->data[j])) >= ((NU8)(97)) && ((NU8)(f->data[j])) <= ((NU8)(122)) || ((NU8)(f->data[j])) >= ((NU8)(65)) && ((NU8)(f->data[j])) <= ((NU8)(90)) || ((NU8)(f->data[j])) >= ((NU8)(48)) && ((NU8)(f->data[j])) <= ((NU8)(57)) || ((NU8)(f->data[j])) == ((NU8)(95)) || ((NU8)(f->data[j])) >= ((NU8)(128)) && ((NU8)(f->data[j])) <= ((NU8)(255)));
							LA19: ;
							if (!LOC18) goto LA17;
							nimln(233, "strtabs.nim");
							TMP593 = addInt(j, ((NI) 1));
							j = (NI)(TMP593);
						} LA17: ;
					}
					nimln(234, "strtabs.nim");
					TMP594 = addInt(i, ((NI) 1));
					TMP595 = subInt(j, ((NI) 1));
					LOC20 = 0;
					LOC20 = copyStrLast(f, (NI)(TMP594), (NI)(TMP595));
					LOC21 = 0;
					LOC21 = getvalue_146185(t, flags, LOC20);
					result = resizeString(result, LOC21->Sup.len + 0);
appendString(result, LOC21);
					nimln(235, "strtabs.nim");
					i = j;
				}
				break;
				default:
				{
					NI TMP596;
					nimln(237, "strtabs.nim");
					if ((NU)(i) > (NU)(f->Sup.len)) raiseIndexError();
					result = addChar(result, f->data[i]);
					nimln(238, "strtabs.nim");
					TMP596 = addInt(i, ((NI) 1));
					i = (NI)(TMP596);
				}
				break;
				}
			}
			goto LA3;
			LA5: ;
			{
				NI TMP597;
				nimln(240, "strtabs.nim");
				if ((NU)(i) > (NU)(f->Sup.len)) raiseIndexError();
				result = addChar(result, f->data[i]);
				nimln(241, "strtabs.nim");
				TMP597 = addInt(i, ((NI) 1));
				i = (NI)(TMP597);
			}
			LA3: ;
		} LA2: ;
	}
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, nstDollar)(Stringtableobj145212* t) {
	NimStringDesc* result;
	nimfr("$", "strtabs.nim")
	result = 0;
	nimln(245, "strtabs.nim");
	{
		NI LOC3;
		LOC3 = 0;
		LOC3 = nstlen(t);
		if (!(LOC3 == ((NI) 0))) goto LA4;
		nimln(246, "strtabs.nim");
		result = copyString(((NimStringDesc*) &TMP598));
	}
	goto LA1;
	LA4: ;
	{
		nimln(248, "strtabs.nim");
		result = copyString(((NimStringDesc*) &TMP599));
		{
			NimStringDesc* key_146533;
			NimStringDesc* val_146534;
			key_146533 = 0;
			val_146534 = 0;
			{
				NI h_146539;
				NI HEX3Atmp_146541;
				NI res_146543;
				h_146539 = 0;
				HEX3Atmp_146541 = 0;
				nimln(43, "strtabs.nim");
				HEX3Atmp_146541 = ((*t).data ? ((*t).data->Sup.len-1) : -1);
				nimln(1874, "system.nim");
				res_146543 = ((NI) 0);
				{
					nimln(1875, "system.nim");
					while (1) {
						NI TMP602;
						if (!(res_146543 <= HEX3Atmp_146541)) goto LA10;
						nimln(1876, "system.nim");
						h_146539 = res_146543;
						nimln(44, "strtabs.nim");
						{
							if ((NU)(h_146539) >= (NU)((*t).data->Sup.len)) raiseIndexError();
							if (!!((*t).data->data[h_146539].Field0 == 0)) goto LA13;
							nimln(45, "strtabs.nim");
							if ((NU)(h_146539) >= (NU)((*t).data->Sup.len)) raiseIndexError();
							key_146533 = (*t).data->data[h_146539].Field0;
							if ((NU)(h_146539) >= (NU)((*t).data->Sup.len)) raiseIndexError();
							val_146534 = (*t).data->data[h_146539].Field1;
							nimln(250, "strtabs.nim");
							{
								nimln(357, "system.nim");
								nimln(250, "strtabs.nim");
								if (!(((NI) 1) < (result ? result->Sup.len : 0))) goto LA17;
								result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TMP600));
							}
							LA17: ;
							nimln(251, "strtabs.nim");
							result = resizeString(result, key_146533->Sup.len + 0);
appendString(result, key_146533);
							nimln(252, "strtabs.nim");
							result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TMP601));
							nimln(253, "strtabs.nim");
							result = resizeString(result, val_146534->Sup.len + 0);
appendString(result, val_146534);
						}
						LA13: ;
						nimln(1895, "system.nim");
						TMP602 = addInt(res_146543, ((NI) 1));
						res_146543 = (NI)(TMP602);
					} LA10: ;
				}
			}
		}
		nimln(254, "strtabs.nim");
		result = resizeString(result, 1);
appendString(result, ((NimStringDesc*) &TMP603));
	}
	LA1: ;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, HEX00_strtabsInit000)(void) {
	nimfr("strtabs", "strtabs.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, HEX00_strtabsDatInit000)(void) {
static TNimNode* TMP576[3];
static TNimNode* TMP577[3];
NI TMP579;
static char* NIM_CONST TMP578[3] = {
"modeCaseSensitive", 
"modeCaseInsensitive", 
"modeStyleInsensitive"};
static TNimNode TMP529[8];
NTI145210.size = sizeof(Keyvaluepairseq145210*);
NTI145210.kind = 24;
NTI145210.base = (&NTI109772);
NTI145210.flags = 2;
NTI145210.marker = TMP568;
NTI145212.size = sizeof(Stringtableobj145212);
NTI145212.kind = 17;
NTI145212.base = (&NTI4011);
TMP576[0] = &TMP529[1];
TMP529[1].kind = 1;
TMP529[1].offset = offsetof(Stringtableobj145212, counter);
TMP529[1].typ = (&NTI108);
TMP529[1].name = "counter";
TMP576[1] = &TMP529[2];
TMP529[2].kind = 1;
TMP529[2].offset = offsetof(Stringtableobj145212, data);
TMP529[2].typ = (&NTI145210);
TMP529[2].name = "data";
TMP576[2] = &TMP529[3];
NTI145206.size = sizeof(NU8);
NTI145206.kind = 14;
NTI145206.base = 0;
NTI145206.flags = 3;
for (TMP579 = 0; TMP579 < 3; TMP579++) {
TMP529[TMP579+4].kind = 1;
TMP529[TMP579+4].offset = TMP579;
TMP529[TMP579+4].name = TMP578[TMP579];
TMP577[TMP579] = &TMP529[TMP579+4];
}
TMP529[7].len = 3; TMP529[7].kind = 2; TMP529[7].sons = &TMP577[0];
NTI145206.node = &TMP529[7];
TMP529[3].kind = 1;
TMP529[3].offset = offsetof(Stringtableobj145212, mode);
TMP529[3].typ = (&NTI145206);
TMP529[3].name = "mode";
TMP529[0].len = 3; TMP529[0].kind = 2; TMP529[0].sons = &TMP576[0];
NTI145212.node = &TMP529[0];
NTI145214.size = sizeof(Stringtableobj145212*);
NTI145214.kind = 22;
NTI145214.base = (&NTI145212);
NTI145214.marker = TMP580;
}

